# Fermi-GBM Time-Resolved Spectral Analysis Pipeline
Each cell corresponds to one pipeline stage — run them top to bottom, or re-run any single stage independently.

## Cell 1 — Imports & Setup

In [1]:
import os
import logging
import numpy as np
import matplotlib
matplotlib.use('Agg')   # swap to 'inline' if running interactively
import matplotlib.pyplot as plt
from astropy.table import Table
import astropy.units as u

from threeML import (
    silence_logs, download_GBM_trigger_data, TimeSeriesBuilder,
    OGIPLike, DataList, Model, PointSource, BayesianAnalysis, plot_spectra,
)
from threeML.catalogs import FermiGBMBurstCatalog as FermiGBMBurst
from astromodels import Cutoff_powerlaw, Band, Log_uniform_prior, Truncated_gaussian, Blackbody           # add model name here after adding cell for new model
import pynchrotron
silence_logs()
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s  %(levelname)-8s  %(message)s',
    datefmt='%H:%M:%S',
)
log = logging.getLogger('GBM_pipeline')
print('Imports OK')

15:46:08 WARNING   The naima package is not available. Models that depend on it will not be         ]8;id=3618212;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=3618213;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/astromodels/functions/functions_1D/functions.py#43\43]8;;\
                  available

         WARNING   The GSL library or the pygsl wrapper cannot be loaded. Models that depend on it  ]8;id=3618219;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/astromodels/functions/functions_1D/functions.py\functions.py]8;;\:]8;id=3618220;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/astromodels/functions/functions_1D/functions.py#65\65]8;;\
                  will not be available.

         WARNING   The ebltable package is not available. Models that depend on it will not be     ]8;id=3618227;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/astromodels/functions/functions_1D/absorption.py\absorption.py]8;;\:]8;id=3618228;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/astromodels/functions/functions_1D/absorption.py#33\33]8;;\
                  available

15:46:08 INFO      Starting 3ML!                                                                     ]8;id=3618235;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3618236;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/__init__.py#44\44]8;;\

         WARNING   WARNINGs here are NOT errors                                                      ]8;id=3618242;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3618243;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/__init__.py#45\45]8;;\

         WARNING   but are inform you about optional packages that can be installed                  ]8;id=3618249;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3618250;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/__init__.py#46\46]8;;\

         WARNING    to disable these messages, turn off start_warning in your config file            ]8;id=3618256;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3618257;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/__init__.py#47\47]8;;\

         WARNING   ROOT minimizer not available                                                ]8;id=3618264;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=3618265;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/minimizer/minimization.py#1208\1208]8;;\

         WARNING   Multinest minimizer not available                                           ]8;id=3618271;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/minimizer/minimization.py\minimization.py]8;;\:]8;id=3618272;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/minimizer/minimization.py#1218\1218]8;;\

         WARNING   Could not import plugin FermiLATLike.py. Do you have the relative instrument     ]8;id=3618278;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/__init__.py\__init__.py]8;;\:]8;id=3618279;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/__init__.py#126\126]8;;\
                  software installed and configured?

15:46:09 WARNING   No fermitools installed                                              ]8;id=3618286;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/utils/data_builders/fermi/lat_transient_builder.py\lat_transient_builder.py]8;;\:]8;id=3618287;file:///home/void/miniforge3/envs/threeML/lib/python3.11/site-packages/threeML/utils/data_builders/fermi/lat_transient_builder.py#44\44]8;;\

Imports OK

In [2]:
from astropy.coordinates import SkyCoord
import astropy.units as u

# Your input string (note: replacing the special degree symbol with 'd' or 'deg' is sometimes 
# safer, but astropy can usually handle standard unicode degree symbols)
ra_str = "18h33m15.21s"
dec_str = "+62d31m57.1s" # Swapped symbols to standard d, m, s for safety

# Create the SkyCoord object
c = SkyCoord(ra=ra_str, dec=dec_str, frame='icrs')

# Extract the decimal degrees
ra_deg = c.ra.degree
dec_deg = c.dec.degree

print("--- Astropy Conversion ---")
print(f"RA in Degrees:  {ra_deg:.6f}")
print(f"DEC in Degrees: {dec_deg:.6f}")

--- Astropy Conversion ---
RA in Degrees:  278.313375
DEC in Degrees: 62.532528

## Cell 2 — Configuration

In [3]:
# ── Edit this block only ────────────────────────────────────────────
CONFIG = dict(
    grb_name       = 'GRB250919020',  # catalog key      (with 'GRB' prefix)
    # Note: trigger_name, ra, and dec will be automatically fetched from the catalog
    # You can optionally define them here to override the catalog defaults!
    #ra=             # in degrees
    #dec=            # in degrees

    # detector selection
    max_rov        = 60.0,            # keep detectors with ROV < this [deg]

    # Analysis Type Selection
    analysis_type  = 'time_resolved',          # 'time_resolved', 'time_integrated', or 'both'

    # Time-Integrated settings
    ti_t_start     = [0.0, 99.97, 0.0],             # start of time-integrated window(s) [s relative to trigger] (can be a list)
    ti_t_stop      = [55.0, 190.02, 190.0],            # end of time-integrated window(s) (can be a list)

    # Bayesian-blocks settings (Time-resolved)
    bb_t_start     = -10.0,           # start of BB window [s relative to trigger]
    bb_t_stop      =  210.0,           # end   of BB window
    bb_p0          =  0.01,           # false-alarm probability for BB
    min_bin_width  =  0.05,           # seconds; narrower bins are merged away

    # Interval Settings (Auto fetches from catalog, or provide manual strings)
    # Multiple background intervals are supported! (e.g. '-40.0--10.0, 175.0-210.0')
    source_interval = '-100.0-300.0',         # 'auto' or e.g., '-5.0-160.0'
    bkg_interval    = '-100.0--10.0, 200.0-300.0',         # 'auto' or e.g., '-40.0-10.0, 175.0-210.0'

    # spectral energy ranges
    nai_range      = '8-33, 37-900',  # keV  (gap skips K-edge ~34-36 keV)
    bgo_range      = '200-40000',     # keV

    # ── Add new model priors here ────────────────────────────────────────────────────────────
    
    # CutoffPL-function priors
    priors_cutoffpl = dict(
        K     = dict(lower=1e-5, upper=1e1),
        index = dict(lower=-2.0, upper=1.0,  mu=-1.3,  sigma=0.5),
        xc    = dict(lower=10.0, upper=1000, mu=300.0, sigma=200.0)
    ),

    # Band-function priors
    priors_band = dict(
        K     = dict(lower=1e-4, upper=1e1),
        alpha = dict(lower=-1.7, upper=1.0,  mu=-1.0,  sigma=0.5),
        xp    = dict(lower=10.0, upper=1000, mu=300.0, sigma=200.0),
        beta  = dict(lower=-4.0, upper=-1.8, mu=-2.5,  sigma=1.0),
    ),

    # Band+BB-function priors
    priors_bandbb = dict(
        alpha_1 = dict(lower=-1.7, upper=1.0,  mu=-1.0,  sigma=0.5),
        K_1     = dict(lower=1e-5, upper=1e1),
        xp_1    = dict(lower=10.0, upper=1000, mu=300.0, sigma=200.0),
        beta_1  = dict(lower=-4.0, upper=-1.8, mu=-2.5,  sigma=1.0),
        K_2     = dict(lower=1e-10, upper=1e-1),
        kT_2    = dict(lower=0.01,  upper=100.0, mu=10.0,  sigma=5.0),
    ),

    # Cutoff+BB-function priors
    priors_cutoffbb = dict(
        K_1     = dict(lower=1e-6, upper=1e1),
        index_1 = dict(lower=-2.0, upper=1.0,  mu=-1.0,  sigma=0.5),
        xc_1    = dict(lower=10.0, upper=1000, mu=300.0, sigma=200.0),
        K_2     = dict(lower=1e-9, upper=1e-2),
        kT_2    = dict(lower=0.1,  upper=50.0, mu=10.0,  sigma=7.0),
    ),

    # Synchrotron-function priors
    priors_synchrotron = dict(
        index_bounds = (1, 5),
        gamma_min = 1e5,
        gamma_max = 1e8,
        bulk_gamma = 300,
        K = dict(lower=1e-7, upper=1e-1),
        B = dict(lower=1.0, upper=100.0),
        index = dict(lower=2.0, upper=5.0, mu=3.0, sigma=1.0),
        gamma_cool = dict(lower=1e5, upper=1e8),
    ),

    # ──────────────────────────────────────────────────────────────────────────────────────────
    
    # MultiNest settings
    n_live_points       = 1000,             # increase to >=1000 for publication quality
    sampling_efficiency = 0.3,              # 0.8 for parameter estimation, 0.3 for evidence evaluation

    # output
    outdir         = 'gbm_pipeline_output',
)

# ── Create common output directories ──────────────────────────────────
COMMON_PATHS = {
    'root': CONFIG['outdir'],                 # For common .h5 detector files
    'lc':   os.path.join(CONFIG['outdir'], 'lightcurves'), # For shared lightcurves
}

for d in COMMON_PATHS.values():
    os.makedirs(d, exist_ok=True)

# ── Helper to dynamically create model subdirectories ─────────────────
def get_model_paths(model_name):
    """Creates and returns specific paths for a given spectral model."""
    m_dir = os.path.join(COMMON_PATHS['root'], model_name)
    m_paths = {
        'root':    m_dir,
        'spectra': os.path.join(m_dir, 'spectra'),
        'corners': os.path.join(m_dir, 'corners'),
    }
    for d in m_paths.values():
        os.makedirs(d, exist_ok=True)
    return m_paths

print('Config loaded. Common output directories created at:', CONFIG['outdir'])

Config loaded. Common output directories created at: gbm_pipeline_output

## Cell 3 — Helper Function Definitions

In [4]:
def pick_reference_detector(detectors):
    """Select the first NaI detector as the BB reference, fallback to first overall."""
    nai = [d for d in detectors if d.startswith('n')]
    return nai[0] if nai else detectors[0]


def build_cutoffpl_model(ra, dec, priors_cutoffpl):
    """Return a fresh Band-function Model with the configured priors."""
    band  = Cutoff_powerlaw()
    model = Model(PointSource('GBM', ra, dec, spectral_shape=band))
    p = priors_cutoffpl
    model.GBM.spectrum.main.Cutoff_powerlaw.K.prior = Log_uniform_prior(
        lower_bound=p['K']['lower'], upper_bound=p['K']['upper'])
    model.GBM.spectrum.main.Cutoff_powerlaw.index.prior = Truncated_gaussian(
        lower_bound=p['index']['lower'], upper_bound=p['index']['upper'],
        mu=p['index']['mu'], sigma=p['index']['sigma'])
    model.GBM.spectrum.main.Cutoff_powerlaw.xc.prior = Truncated_gaussian(
        lower_bound=p['xc']['lower'], upper_bound=p['xc']['upper'],
        mu=p['xc']['mu'], sigma=p['xc']['sigma'])
    return model

def build_band_model(ra, dec, priors_band):
    """Return a fresh Band-function Model with the configured priors."""
    band  = Band()
    model = Model(PointSource('GBM', ra, dec, spectral_shape=band))
    p = priors_band
    model.GBM.spectrum.main.Band.K.prior = Log_uniform_prior(
        lower_bound=p['K']['lower'], upper_bound=p['K']['upper'])
    model.GBM.spectrum.main.Band.alpha.bounds = (
        p['alpha']['lower'], p['alpha']['upper'])
    model.GBM.spectrum.main.Band.alpha.prior = Truncated_gaussian(
        lower_bound=p['alpha']['lower'], upper_bound=p['alpha']['upper'],
        mu=p['alpha']['mu'], sigma=p['alpha']['sigma'])
    model.GBM.spectrum.main.Band.xp.prior = Truncated_gaussian(
        lower_bound=p['xp']['lower'], upper_bound=p['xp']['upper'],
        mu=p['xp']['mu'], sigma=p['xp']['sigma'])
    model.GBM.spectrum.main.Band.beta.prior = Truncated_gaussian(
        lower_bound=p['beta']['lower'], upper_bound=p['beta']['upper'],
        mu=p['beta']['mu'], sigma=p['beta']['sigma'])
    return model

def build_bandbb_model(ra, dec, p):
    mod = Band() + Blackbody()
    model = Model(PointSource('GBM', ra, dec, spectral_shape=mod))
    model.GBM.spectrum.main.composite.alpha_1.bounds = (-2, 1)
    model.GBM.spectrum.main.composite.K_1.prior = Log_uniform_prior(lower_bound=p['K_1']['lower'], upper_bound=p['K_1']['upper'])
    model.GBM.spectrum.main.composite.alpha_1.prior = Truncated_gaussian(lower_bound=p['alpha_1']['lower'], upper_bound=p['alpha_1']['upper'], mu=p['alpha_1']['mu'], sigma=p['alpha_1']['sigma'])
    model.GBM.spectrum.main.composite.xp_1.prior = Truncated_gaussian(lower_bound=p['xp_1']['lower'], upper_bound=p['xp_1']['upper'], mu=p['xp_1']['mu'], sigma=p['xp_1']['sigma'])
    model.GBM.spectrum.main.composite.beta_1.prior = Truncated_gaussian(lower_bound=p['beta_1']['lower'], upper_bound=p['beta_1']['upper'], mu=p['beta_1']['mu'], sigma=p['beta_1']['sigma'])
    model.GBM.spectrum.main.composite.K_2.prior = Log_uniform_prior(lower_bound=p['K_2']['lower'], upper_bound=p['K_2']['upper'])
    model.GBM.spectrum.main.composite.kT_2.prior = Truncated_gaussian(lower_bound=p['kT_2']['lower'], upper_bound=p['kT_2']['upper'], mu=p['kT_2']['mu'], sigma=p['kT_2']['sigma'])
    return model

def build_cutoffbb_model(ra, dec, p):
    band = Cutoff_powerlaw() + Blackbody()
    model = Model(PointSource('GBM', ra, dec, spectral_shape=band))
    model.GBM.spectrum.main.composite.K_1.prior = Log_uniform_prior(lower_bound=p['K_1']['lower'], upper_bound=p['K_1']['upper'])
    model.GBM.spectrum.main.composite.index_1.prior = Truncated_gaussian(lower_bound=p['index_1']['lower'], upper_bound=p['index_1']['upper'], mu=p['index_1']['mu'], sigma=p['index_1']['sigma'])
    model.GBM.spectrum.main.composite.xc_1.prior = Truncated_gaussian(lower_bound=p['xc_1']['lower'], upper_bound=p['xc_1']['upper'], mu=p['xc_1']['mu'], sigma=p['xc_1']['sigma'])
    model.GBM.spectrum.main.composite.K_2.prior = Log_uniform_prior(lower_bound=p['K_2']['lower'], upper_bound=p['K_2']['upper'])
    model.GBM.spectrum.main.composite.kT_2.prior = Truncated_gaussian(lower_bound=p['kT_2']['lower'], upper_bound=p['kT_2']['upper'], mu=p['kT_2']['mu'], sigma=p['kT_2']['sigma'])
    return model

def build_synchrotron_model(ra, dec, p):
    mod = pynchrotron.SynchrotronNumerical()
    model = Model(PointSource('Synchrotron', ra, dec, spectral_shape=mod))
    model.Synchrotron.spectrum.main.SynchrotronNumerical.index.bounds = p['index_bounds']
    model.Synchrotron.spectrum.main.SynchrotronNumerical.gamma_min.fix = p['gamma_min']
    model.Synchrotron.spectrum.main.SynchrotronNumerical.gamma_max.fix = p['gamma_max']
    model.Synchrotron.spectrum.main.SynchrotronNumerical.bulk_gamma.fix = p['bulk_gamma']
    model.Synchrotron.spectrum.main.SynchrotronNumerical.K.prior = Log_uniform_prior(lower_bound=p['K']['lower'], upper_bound=p['K']['upper'])
    model.Synchrotron.spectrum.main.SynchrotronNumerical.B.prior = Log_uniform_prior(lower_bound=p['B']['lower'], upper_bound=p['B']['upper'])
    model.Synchrotron.spectrum.main.SynchrotronNumerical.index.prior = Truncated_gaussian(lower_bound=p['index']['lower'], upper_bound=p['index']['upper'], mu=p['index']['mu'], sigma=p['index']['sigma'])
    model.Synchrotron.spectrum.main.SynchrotronNumerical.gamma_cool.prior = Log_uniform_prior(lower_bound=p['gamma_cool']['lower'], upper_bound=p['gamma_cool']['upper'])
    return model

print('Helper functions defined.')

Helper functions defined.

## Cell 4 — Detector Selection (ROV < 60°)

In [5]:
log.info('Querying Fermi-GBM catalog for %s ...', CONFIG['grb_name'])

cat = FermiGBMBurst()
cat.query_sources(CONFIG['grb_name'])
grb_info = cat.get_detector_information()[CONFIG['grb_name']]

# ── Auto-derive missing configs ───────────────────────────────────────
if 'trigger_name' not in CONFIG:
    CONFIG['trigger_name'] = CONFIG['grb_name'].replace('GRB', 'bn')
if 'ra' not in CONFIG:
    CONFIG['ra'] = float(grb_info['ra'])
if 'dec' not in CONFIG:
    CONFIG['dec'] = float(grb_info['dec'])

log.info('Auto-derived CONFIG -> trigger: %s, ra: %.3f, dec: %.3f', 
         CONFIG['trigger_name'], CONFIG['ra'], CONFIG['dec'])

# ── Fetch catalog source / background intervals ───────────────────────
if CONFIG.get('source_interval', 'auto') == 'auto':
    source_interval = grb_info['source']['fluence']
else:
    source_interval = CONFIG['source_interval']

if CONFIG.get('bkg_interval', 'auto') == 'auto':
    background_interval = grb_info['background']['full']
else:
    background_interval = CONFIG['bkg_interval']

log.info('Source interval    : %s', source_interval)
log.info('Background interval: %s', background_interval)

# ── Manually Specify Detectors ────────────────────────────────────────
# Valid NaI detectors: 'n0' through 'n9', 'na', 'nb'
# Valid BGO detectors: 'b0', 'b1'
detectors = ['n6', 'n7', 'n8', 'b1']  # <-- Change these to your preferred detectors

log.info('Manually selected detectors done: %s', detectors)


# ── Quick sanity check ────────────────────────────────────────────────
assert len(detectors) > 0, 'No detectors selected. Please add them to the list.'
assert any(d.startswith('n') for d in detectors), 'Need at least one NaI detector for the fit.'

15:46:09  INFO      Querying Fermi-GBM catalog for GRB250919020 ...
15:46:10  INFO      Auto-derived CONFIG -> trigger: bn250919020, ra: 298.554, dec: -48.838
15:46:10  INFO      Source interval    : -100.0-300.0
15:46:10  INFO      Background interval: -100.0--10.0, 200.0-300.0
15:46:10  INFO      Manually selected detectors done: ['n6', 'n7', 'n8', 'b1']

## Cell 5 — Download GBM Data

In [6]:
log.info('Downloading TTE / CSPEC / RSP for: %s', detectors)
dload = download_GBM_trigger_data(CONFIG['trigger_name'], detectors=detectors)

# ── Verify all expected file types are present ────────────────────────
for det in detectors:
    for ftype in ('tte', 'cspec', 'rsp'):
        assert ftype in dload[det], f'Missing {ftype} file for detector {det}'

print('Download complete. Files available for:', list(dload.keys()))

15:46:10  INFO      Downloading TTE / CSPEC / RSP for: ['n6', 'n7', 'n8', 'b1']

Download complete. Files available for: ['n6', 'n7', 'n8', 'b1']

## Cell 6 — Build Time Series & Fit Backgrounds

In [7]:
time_series = {}

for det in detectors:
    log.info('Processing detector %s ...', det)

    # ── Step 6a: fit background polynomial on CSPEC ───────────────────
    ts_cspec = TimeSeriesBuilder.from_gbm_cspec_or_ctime(
        det,
        cspec_or_ctime_file = dload[det]['cspec'],
        rsp_file            = dload[det]['rsp'],
    )
    bkg_segs = [s.strip() for s in background_interval.split(',')]
    ts_cspec.set_background_interval(*bkg_segs)

    bkg_file = os.path.join(COMMON_PATHS['root'], f'{det}_bkg.h5')
    ts_cspec.save_background(bkg_file, overwrite=True)
    log.info('  Background saved to %s', bkg_file)

    # ── Step 6b: load TTE with restored background ────────────────────
    ts_tte = TimeSeriesBuilder.from_gbm_tte(
        det,
        tte_file           = dload[det]['tte'],
        rsp_file           = dload[det]['rsp'],
        restore_background = bkg_file,
    )
    ts_tte.set_active_time_interval(source_interval)
    time_series[det] = ts_tte
    log.info('  TTE loaded and active interval set.')

print('Time series built for:', list(time_series.keys()))

# ── Quick sanity: view lightcurve of first NaI ────────────────────────
first_nai = next(d for d in detectors if d.startswith('n'))
fig = time_series[first_nai].view_lightcurve(-40, 250)

fig.savefig(os.path.join(COMMON_PATHS['lc'], f'{first_nai}_raw_lc.png'), dpi=100, bbox_inches='tight')
plt.close('all')
print(f'Raw lightcurve saved for {first_nai}')

15:46:30  INFO      Processing detector n6 ...

WARNING RuntimeWarning: invalid value encountered in divide

Loading PHAII Spectra:   0%|          | 0/2387 [00:00<?, ?it/s]

WARNING RuntimeWarning: invalid value encountered in divide

Finding best polynomial Order:   0%|          | 0/4 [00:00<?, ?it/s]

Fitting GBM_NAI_06 background:   0%|          | 0/128 [00:00<?, ?it/s]

15:46:35  INFO        Background saved to gbm_pipeline_output/n6_bkg.h5
15:46:36  INFO        TTE loaded and active interval set.
15:46:36  INFO      Processing detector n7 ...

WARNING RuntimeWarning: invalid value encountered in divide

Loading PHAII Spectra:   0%|          | 0/2387 [00:00<?, ?it/s]

WARNING RuntimeWarning: invalid value encountered in divide

Finding best polynomial Order:   0%|          | 0/4 [00:00<?, ?it/s]

Fitting GBM_NAI_07 background:   0%|          | 0/128 [00:00<?, ?it/s]

15:46:40  INFO        Background saved to gbm_pipeline_output/n7_bkg.h5
15:46:41  INFO        TTE loaded and active interval set.
15:46:41  INFO      Processing detector n8 ...

WARNING RuntimeWarning: invalid value encountered in divide

Loading PHAII Spectra:   0%|          | 0/2387 [00:00<?, ?it/s]

WARNING RuntimeWarning: invalid value encountered in divide

Finding best polynomial Order:   0%|          | 0/4 [00:00<?, ?it/s]

Fitting GBM_NAI_08 background:   0%|          | 0/128 [00:00<?, ?it/s]

15:46:45  INFO        Background saved to gbm_pipeline_output/n8_bkg.h5
15:46:45  INFO        TTE loaded and active interval set.
15:46:45  INFO      Processing detector b1 ...

WARNING RuntimeWarning: invalid value encountered in divide

Loading PHAII Spectra:   0%|          | 0/2387 [00:00<?, ?it/s]

WARNING RuntimeWarning: invalid value encountered in divide

Finding best polynomial Order:   0%|          | 0/4 [00:00<?, ?it/s]

Fitting GBM_BGO_01 background:   0%|          | 0/128 [00:00<?, ?it/s]

15:46:49  INFO        Background saved to gbm_pipeline_output/b1_bkg.h5
15:46:49  INFO        TTE loaded and active interval set.

Time series built for: ['n6', 'n7', 'n8', 'b1']
Raw lightcurve saved for n6

## Cell 7 — Bayesian-Block Time Binning

In [8]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    ref_det = pick_reference_detector(detectors)
    ts_ref  = time_series[ref_det]
    log.info('Reference detector for BB: %s', ref_det)

    # ── Run Bayesian blocks ────────────────────────────────────────────────
    ts_ref.create_time_bins(
        CONFIG['bb_t_start'], CONFIG['bb_t_stop'],
        method='bayesblocks', use_background=True, p0=CONFIG['bb_p0'],
    )

    print('Raw BB bins:')
    print('  starts:', ts_ref.bins.starts)
    print('  stops :', ts_ref.bins.stops)
    print('  widths:', ts_ref.bins.widths)

    fig_raw = ts_ref.view_lightcurve(use_binner=True)
    fig_raw.savefig(os.path.join(COMMON_PATHS['lc'], f'{ref_det}_bb_raw.png'), dpi=120, bbox_inches='tight')
    plt.close('all')

15:46:49  INFO      Reference detector for BB: n6

Raw BB bins:
  starts: [-9.999567985534668, -1.7827140092849731, 7.222595930099487, 9.711471915245056, 15.467687964439392, 17.642516911029816, 19.00998604297638, 19.5523379445076, 21.46287202835083, 21.780908942222595, 22.94713795185089, 23.95138704776764, 24.292457938194275, 25.0365469455719, 25.58158791065216, 26.230883955955505, 26.422366976737976, 27.00486797094345, 27.243307948112488, 28.079165935516357, 28.41358995437622, 28.787449955940247, 28.915356993675232, 29.249943912029266, 29.351269960403442, 29.504889011383057, 29.664226949214935, 29.991352021694183, 30.271545946598053, 30.315245985984802, 30.417394995689392, 30.520058929920197, 30.598963916301727, 30.6375949382782, 30.761191964149475, 30.8381609916687, 31.22098398208618, 31.688543915748596, 32.142654955387115, 32.42498803138733, 32.7040199637413, 33.07159787416458, 33.24419695138931, 33.49145096540451, 33.59380489587784, 33.74374395608902, 34.8341109752655, 35.01782989501953, 35.34640097618103, 35.718194007873535, 35.826537013053894, 36.16249090433121, 36.31585496664047, 36.41435497999191, 36.586112916469574, 36.93920397758484, 37.299582958221436, 37.63099592924118, 38.590618908405304, 40.54509389400482, 42.63914793729782, 60.19475495815277, 69.24457800388336, 110.6079329252243, 113.24236696958542, 122.63177293539047, 128.54242193698883, 142.6586139202118, 146.9408239722252, 149.23341393470764, 153.55639493465424, 157.51758289337158, 162.87332797050476, 190.91526597738266]
  stops : [-1.7827140092849731, 7.222595930099487, 9.711471915245056, 15.467687964439392, 17.642516911029816, 19.00998604297638, 19.5523379445076, 21.46287202835083, 21.780908942222595, 22.94713795185089, 23.95138704776764, 24.292457938194275, 25.0365469455719, 25.58158791065216, 26.230883955955505, 26.422366976737976, 27.00486797094345, 27.243307948112488, 28.079165935516357, 28.41358995437622, 28.787449955940247, 28.915356993675232, 29.249943912029266, 29.351269960403442, 29.504889011383057, 29.664226949214935, 29.991352021694183, 30.271545946598053, 30.315245985984802, 30.417394995689392, 30.520058929920197, 30.598963916301727, 30.6375949382782, 30.761191964149475, 30.8381609916687, 31.22098398208618, 31.688543915748596, 32.142654955387115, 32.42498803138733, 32.7040199637413, 33.07159787416458, 33.24419695138931, 33.49145096540451, 33.59380489587784, 33.74374395608902, 34.8341109752655, 35.01782989501953, 35.34640097618103, 35.718194007873535, 35.826537013053894, 36.16249090433121, 36.31585496664047, 36.41435497999191, 36.586112916469574, 36.93920397758484, 37.299582958221436, 37.63099592924118, 38.590618908405304, 40.54509389400482, 42.63914793729782, 60.19475495815277, 69.24457800388336, 110.6079329252243, 113.24236696958542, 122.63177293539047, 128.54242193698883, 142.6586139202118, 146.9408239722252, 149.23341393470764, 153.55639493465424, 157.51758289337158, 162.87332797050476, 190.91526597738266, 209.99907195568085]
  widths: [8.21685398e+00 9.00530994e+00 2.48887599e+00 5.75621605e+00
 2.17482895e+00 1.36746913e+00 5.42351902e-01 1.91053408e+00
 3.18036914e-01 1.16622901e+00 1.00424910e+00 3.41070890e-01
 7.44089007e-01 5.45040965e-01 6.49296045e-01 1.91483021e-01
 5.82500994e-01 2.38439977e-01 8.35857987e-01 3.34424019e-01
 3.73860002e-01 1.27907038e-01 3.34586918e-01 1.01326048e-01
 1.53619051e-01 1.59337938e-01 3.27125072e-01 2.80193925e-01
 4.37000394e-02 1.02149010e-01 1.02663934e-01 7.89049864e-02
 3.86310220e-02 1.23597026e-01 7.69690275e-02 3.82822990e-01
 4.67559934e-01 4.54111040e-01 2.82333076e-01 2.79031932e-01
 3.67577910e-01 1.72599077e-01 2.47254014e-01 1.02353930e-01
 1.49939060e-01 1.09036702e+00 1.83718920e-01 3.28571081e-01
 3.71793032e-01 1.08343005e-01 3.35953891e-01 1.53364062e-01
 9.85000134e-02 1.71757936e-01 3.53091061e-01 3.60378981e-01
 3.31412971e-01 9.59622979e-01 1.95447499e+00 2.09405404e+00
 1.75556070e+01 9.04982305e+00 4.13633549e+01 2.63443404e+00
 9.38940597e+00 5.91064900e+00 1.41161920e+01 4.28221005e+00
 2.29258996e+00 4.32298100e+00 3.96118796e+00 5.35574508e+00
 2.80419380e+01 1.90838060e+01]

## Cell 8 — Merge Sub-Threshold Bins

In [9]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    min_w = CONFIG['min_bin_width']

    bad_bins = {i for i, w in enumerate(ts_ref.bins.widths) if w < min_w}
    print(f'Bins narrower than {min_w} s (to be merged): {sorted(bad_bins)}')

    edges = [ts_ref.bins.starts[0]]
    for i, b in enumerate(ts_ref.bins):
        if i not in bad_bins:
            edges.append(b.stop)

    bb_starts = np.array(edges[:-1])
    bb_stops  = np.array(edges[1:])
    n_bins    = len(bb_starts)

    ts_ref.create_time_bins(bb_starts, bb_stops, method='custom')

    print(f'Clean bins ({n_bins} total):')
    print('  starts:', bb_starts)
    print('  stops :', bb_stops)
    print('  widths:', bb_stops - bb_starts)

    fig_clean = ts_ref.view_lightcurve(use_binner=True)
    fig_clean.savefig(os.path.join(COMMON_PATHS['lc'], f'{ref_det}_bb_clean.png'), dpi=120, bbox_inches='tight')
    plt.close('all')

    assert n_bins > 0, 'Zero bins after merging — check bb_t_start / bb_t_stop or p0'
    print(f'\nReady to fit {n_bins} time bin(s).')

Bins narrower than 0.05 s (to be merged): [28, 32]
Clean bins (72 total):
  starts: [ -9.99956799  -1.78271401   7.22259593   9.71147192  15.46768796
  17.64251691  19.00998604  19.55233794  21.46287203  21.78090894
  22.94713795  23.95138705  24.29245794  25.03654695  25.58158791
  26.23088396  26.42236698  27.00486797  27.24330795  28.07916594
  28.41358995  28.78744996  28.91535699  29.24994391  29.35126996
  29.50488901  29.66422695  29.99135202  30.27154595  30.417395
  30.52005893  30.59896392  30.76119196  30.83816099  31.22098398
  31.68854392  32.14265496  32.42498803  32.70401996  33.07159787
  33.24419695  33.49145097  33.5938049   33.74374396  34.83411098
  35.0178299   35.34640098  35.71819401  35.82653701  36.1624909
  36.31585497  36.41435498  36.58611292  36.93920398  37.29958296
  37.63099593  38.59061891  40.54509389  42.63914794  60.19475496
  69.244578   110.60793293 113.24236697 122.63177294 128.54242194
 142.65861392 146.94082397 149.23341393 153.55639493 157.51758289
 162.87332797 190.91526598]
  stops : [ -1.78271401   7.22259593   9.71147192  15.46768796  17.64251691
  19.00998604  19.55233794  21.46287203  21.78090894  22.94713795
  23.95138705  24.29245794  25.03654695  25.58158791  26.23088396
  26.42236698  27.00486797  27.24330795  28.07916594  28.41358995
  28.78744996  28.91535699  29.24994391  29.35126996  29.50488901
  29.66422695  29.99135202  30.27154595  30.417395    30.52005893
  30.59896392  30.76119196  30.83816099  31.22098398  31.68854392
  32.14265496  32.42498803  32.70401996  33.07159787  33.24419695
  33.49145097  33.5938049   33.74374396  34.83411098  35.0178299
  35.34640098  35.71819401  35.82653701  36.1624909   36.31585497
  36.41435498  36.58611292  36.93920398  37.29958296  37.63099593
  38.59061891  40.54509389  42.63914794  60.19475496  69.244578
 110.60793293 113.24236697 122.63177294 128.54242194 142.65861392
 146.94082397 149.23341393 153.55639493 157.51758289 162.87332797
 190.91526598 209.99907196]
  widths: [ 8.21685398  9.00530994  2.48887599  5.75621605  2.17482895  1.36746913
  0.5423519   1.91053408  0.31803691  1.16622901  1.0042491   0.34107089
  0.74408901  0.54504097  0.64929605  0.19148302  0.58250099  0.23843998
  0.83585799  0.33442402  0.37386     0.12790704  0.33458692  0.10132605
  0.15361905  0.15933794  0.32712507  0.28019392  0.14584905  0.10266393
  0.07890499  0.16222805  0.07696903  0.38282299  0.46755993  0.45411104
  0.28233308  0.27903193  0.36757791  0.17259908  0.24725401  0.10235393
  0.14993906  1.09036702  0.18371892  0.32857108  0.37179303  0.10834301
  0.33595389  0.15336406  0.09850001  0.17175794  0.35309106  0.36037898
  0.33141297  0.95962298  1.95447499  2.09405404 17.55560702  9.04982305
 41.36335492  2.63443404  9.38940597  5.910649   14.11619198  4.28221005
  2.29258996  4.322981    3.96118796  5.35574508 28.04193801 19.08380598]

Ready to fit 72 time bin(s).

## Cell 9 — Sync Detectors & Build Time-Resolved Plugins

In [10]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    time_resolved_plugins = {}   # {det: [plugin_bin_0, plugin_bin_1, ...]}

    for det in detectors:
        ts = time_series[det]
        ts.read_bins(ts_ref)                         # sync to reference bins
        plugin_list = ts.to_spectrumlike(from_bins=True)
        time_resolved_plugins[det] = plugin_list
        log.info('%s  ->  %d time-bin plugins', det, len(plugin_list))

    # ── Sanity: all detectors should have the same number of bins ─────────
    bin_counts = {d: len(v) for d, v in time_resolved_plugins.items()}
    print('Plugin counts per detector:', bin_counts)
    assert len(set(bin_counts.values())) == 1, 'Bin count mismatch across detectors!'
    print('All detectors in sync. Ready for spectral fitting.')

Creating plugins:   0%|          | 0/72 [00:00<?, ?it/s]

15:51:47  INFO      n6  ->  72 time-bin plugins

Creating plugins:   0%|          | 0/72 [00:00<?, ?it/s]

15:51:51  INFO      n7  ->  72 time-bin plugins

Creating plugins:   0%|          | 0/72 [00:00<?, ?it/s]

15:51:54  INFO      n8  ->  72 time-bin plugins

Creating plugins:   0%|          | 0/72 [00:00<?, ?it/s]

15:51:58  INFO      b1  ->  72 time-bin plugins

Plugin counts per detector: {'n6': 72, 'n7': 72, 'n8': 72, 'b1': 72}
All detectors in sync. Ready for spectral fitting.

## Cell 10 — Time-Resolved Spectral Fitting (CutoffPLModel)

In [11]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    MODEL_PATHS = get_model_paths('cutoffpl')                             # Change this for each new model

    PARAM_NAMES = [
        'B_K',     'B_K_n_err',     'B_K_p_err',     'B_K_avg_err',
        'B_alpha', 'B_alpha_n_err', 'B_alpha_p_err',  'B_alpha_avg_err',
        'E_c',  'E_c_n_err',  'E_c_p_err',   'E_c_avg_err',
        'flux',    'flux_low',      'flux_hi', 'DIC', 'PDIC', 'BIC'
    ]

    fit_rows = []

    for i in range(n_bins):
        log.info('==== Time bin %d / %d ====', i + 1, n_bins)

        # ── Assemble per-detector plugins for this bin ────────────────────
        det_plugins = []
        for det in detectors:
            p = time_resolved_plugins[det][i]
            if det.startswith('b'):
                p.set_active_measurements(CONFIG['bgo_range'])
            else:
                ranges = [r.strip() for r in CONFIG['nai_range'].split(',')]
                p.set_active_measurements(*ranges)
            det_plugins.append(p)

        data_list = DataList(*det_plugins)

        # ── Fresh Band model per bin ──────────────────────────────────────
        model = build_cutoffpl_model(CONFIG['ra'], CONFIG['dec'], CONFIG['priors_cutoffpl'])

        # ── Bayesian fit with MultiNest ───────────────────────────────────
        bayes = BayesianAnalysis(model, data_list)
        bayes.set_sampler('multinest')
        bayes.sampler.setup(n_live_points=CONFIG['n_live_points'], sampling_efficiency=CONFIG['sampling_efficiency'], auto_clean=True)
        bayes.sample()

        # ── νFν spectrum plot ─────────────────────────────────────────────
        fig_spec = plot_spectra(
            bayes.results,
            ene_min=1.0, ene_max=1e5, num_ene=200,
            contour_colors='white',
            contour_style_kwargs=dict(alpha=0.2),
            use_components=True, components_to_use=['total'],
            flux_unit='keV2/(cm2 s keV)',
        )
        ax = plt.gca()
        ax.set_xlabel('Energy (keV)', fontsize=16)
        ax.set_ylabel(r'$\nu\,F_\nu\;[\mathrm{keV\,cm^{-2}\,s^{-1}}]$', fontsize=16)
        ax.set_title(f"{CONFIG['trigger_name']}  bin {i+1}/{n_bins}  "
                     f"[{bb_starts[i]:.3f}, {bb_stops[i]:.3f}] s", fontsize=13)
        fig_spec.savefig(
            os.path.join(MODEL_PATHS['spectra'], f'cutoffpl_spec_bin{i+1:03d}.png'),
            dpi=120, bbox_inches='tight')
        plt.close('all')

        # ── Corner plot ───────────────────────────────────────────────────
        fig_corner = bayes.results.corner_plot()
        fig_corner.savefig(
            os.path.join(MODEL_PATHS['corners'], f'cutoffpl_corner_bin{i+1:03d}.png'),
            dpi=100, bbox_inches='tight')
        plt.close('all')

        # ── Integrated flux ───────────────────────────────────────────────
        flux_df = bayes.results.get_point_source_flux(10 * u.keV, 10 * u.MeV)
        log.info('  10 keV-10 MeV flux = %s', flux_df)

        # Extract the raw floats by stripping the astropy units (.value)
        f_val = flux_df['flux'].iloc[0].value
        f_low = flux_df['low bound'].iloc[0].value
        f_hi  = flux_df['hi bound'].iloc[0].value

        # ── Collect parameters ────────────────────────────────────────────
        df  = bayes.results.get_data_frame('equal tail')
        df  = df.drop('unit', axis=1, errors='ignore')
        param_array = df.to_numpy().flatten()

        stat_df = bayes.results.get_statistic_measure_frame()
        dic_val = stat_df.loc['DIC'].iloc[0] if 'DIC' in stat_df.index else np.nan
        pdic_val = stat_df.loc['PDIC'].iloc[0] if 'PDIC' in stat_df.index else np.nan
        bic_val = stat_df.loc['BIC'].iloc[0] if 'BIC' in stat_df.index else np.nan

        full_row = np.append(param_array, [f_val, f_low, f_hi, dic_val, pdic_val, bic_val])
        fit_rows.append(full_row)
        log.info('  Bin %d / %d complete.', i + 1, n_bins)

    print(f'\nAll {n_bins} bins fitted successfully.')

15:51:58  INFO      ==== Time bin 1 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2472.6590440216714      +/-   2.0478402846801833E-002
 Total Likelihood Evaluations:         9979
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,(0.0010 +0.0028 +1.3) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.2 -0.6 +0.4,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.5 -0.9 +2.8) x 10^2,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval0      -633.754726
n7_interval0      -638.614177
n8_interval0      -629.781485
b1_interval0      -549.490493
total            -2451.640881

Values of statistical measures:

        statistical measures
AIC              4909.331866
BIC              4921.821812
DIC              4939.871026
PDIC               -4.442207
log(Z)          -1073.862178

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:52:10  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.1838960470538144e-10 erg / (s cm2)

                                       low bound  \
GBM: total  3.2622047533397695e-12 erg / (s cm2)

                                       hi bound
GBM: total  2.879838362364324e-09 erg / (s cm2)
15:52:10  INFO        Bin 1 / 72 complete.
15:52:10  INFO      ==== Time bin 2 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2642.5046051885961      +/-   8.7770834840049369E-002
 Total Likelihood Evaluations:        30961
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,(4.5 -0.8 +1.8) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-8.6 -1.0 +0.5) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.5 -0.4 +1.1) x 10^2,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval1      -698.237200
n7_interval1      -691.981362
n8_interval1      -692.439149
b1_interval1      -574.383320
total            -2657.041031

Values of statistical measures:

        statistical measures
AIC              5320.132166
BIC              5332.622112
DIC              5281.807373
PDIC                0.030856
log(Z)          -1147.625168

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:52:29  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.404538801286024e-07 erg / (s cm2)

                                     low bound  \
GBM: total  4.94928497073534e-07 erg / (s cm2)

                                      hi bound
GBM: total  5.92428184891391e-07 erg / (s cm2)
15:52:29  INFO        Bin 2 / 72 complete.
15:52:29  INFO      ==== Time bin 3 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1745.1651156529856      +/-   9.1684448115506009E-002
 Total Likelihood Evaluations:        32408
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,(6.6 -0.8 +3.0) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-7.5 -1.0 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.70 -0.23 +0.8) x 10^2,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval2      -472.193919
n7_interval2      -476.546884
n8_interval2      -467.065188
b1_interval2      -345.354727
total            -1761.160718

Values of statistical measures:

        statistical measures
AIC              3528.371540
BIC              3540.861486
DIC              3486.650212
PDIC               -0.005075
log(Z)           -757.915580

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:52:49  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.0545415016832213e-06 erg / (s cm2)

                                      low bound  \
GBM: total  9.753237378171596e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.1386233614787353e-06 erg / (s cm2)
15:52:49  INFO        Bin 3 / 72 complete.
15:52:49  INFO      ==== Time bin 4 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2324.3852297160615      +/-   9.2742552624604929E-002
 Total Likelihood Evaluations:        31110
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,(7.1 -1.0 +3.1) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-8.4 -1.1 +0.5) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.17 -0.18 +0.6) x 10^2,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval3      -609.716300
n7_interval3      -616.508223
n8_interval3      -612.264360
b1_interval3      -501.517141
total            -2340.006023

Values of statistical measures:

        statistical measures
AIC              4686.062151
BIC              4698.552097
DIC              4644.577620
PDIC                0.019165
log(Z)          -1009.467679

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:53:10  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.454400828201097e-07 erg / (s cm2)

                                     low bound  \
GBM: total  5.09926537426156e-07 erg / (s cm2)

                                       hi bound
GBM: total  5.843756131941761e-07 erg / (s cm2)
15:53:10  INFO        Bin 4 / 72 complete.
15:53:10  INFO      ==== Time bin 5 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1622.8388677621315      +/-   9.1443166922208122E-002
 Total Likelihood Evaluations:        31063
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.49 -0.17 +0.7,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-8.84 -1.1 +0.34) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.34 -0.18 +0.7) x 10^2,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval4      -443.425979
n7_interval4      -449.827314
n8_interval4      -447.917018
b1_interval4      -300.086386
total            -1641.256697

Values of statistical measures:

        statistical measures
AIC              3288.563498
BIC              3301.053443
DIC              3243.581852
PDIC                0.355658
log(Z)           -704.789965

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:53:29  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  9.967858318530163e-07 erg / (s cm2)

                                     low bound  \
GBM: total  9.27627192504994e-07 erg / (s cm2)

                                       hi bound
GBM: total  1.074017128026668e-06 erg / (s cm2)
15:53:29  INFO        Bin 5 / 72 complete.
15:53:29  INFO      ==== Time bin 6 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -1360.7415167093686      +/-   9.4684920531656683E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        35125
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.64 -0.20 +0.5,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-8.1 -0.7 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.80 -0.21 +0.5) x 10^2,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval5      -390.291032
n7_interval5      -381.413718
n8_interval5      -369.422016
b1_interval5      -238.207046
total            -1379.333811

Values of statistical measures:

        statistical measures
AIC              2764.717727
BIC              2777.207673
DIC              2719.583380
PDIC                1.419066
log(Z)           -590.962532

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:53:50  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  1.96065547966444e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.8546810302814422e-06 erg / (s cm2)

                                        hi bound
GBM: total  2.0752512229338493e-06 erg / (s cm2)
15:53:50  INFO        Bin 6 / 72 complete.
15:53:50  INFO      ==== Time bin 7 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -677.99803132378156      +/-   9.6853814215072109E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        34107
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.06 -0.15 +0.5,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-6.0 -1.0 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.13 -0.15 +0.4) x 10^2,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval6      -202.997384
n7_interval6      -216.847795
n8_interval6      -217.701635
b1_interval6       -59.177433
total             -696.724246

Values of statistical measures:

        statistical measures
AIC              1399.498597
BIC              1411.988543
DIC              1351.988479
PDIC               -0.045020
log(Z)           -294.450804

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:54:11  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.7260100860164614e-06 erg / (s cm2)

                                       low bound  \
GBM: total  2.5652906441861446e-06 erg / (s cm2)

                                       hi bound
GBM: total  2.897165650706161e-06 erg / (s cm2)
15:54:11  INFO        Bin 7 / 72 complete.
15:54:11  INFO      ==== Time bin 8 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -1584.7953784682343      +/-   9.5964494149342577E-002
 Total Likelihood Evaluations:        37675
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.95 -0.23 +0.7,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-8.5 -0.9 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.00 -0.16 +0.4) x 10^2,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval7      -435.569936
n7_interval7      -442.924169
n8_interval7      -433.948574
b1_interval7      -291.556173
total            -1603.998853

Values of statistical measures:

        statistical measures
AIC              3214.047810
BIC              3226.537755
DIC              3167.113318
PDIC                0.930763
log(Z)           -688.267888

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:54:32  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2585168599989241e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.1957478872480051e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.3268860799175609e-06 erg / (s cm2)
15:54:32  INFO        Bin 8 / 72 complete.
15:54:32  INFO      ==== Time bin 9 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -316.85841460262446      +/-   8.7348810587300721E-002
 Total Likelihood Evaluations:        30835
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.80 -0.29 +0.9,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-7.8 -1.1 +0.5) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.7 -0.4 +1.2) x 10^2,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval8      -123.403724
n7_interval8      -128.697931
n8_interval8      -125.355715
b1_interval8        39.740675
total             -337.716696

Values of statistical measures:

        statistical measures
AIC               681.483496
BIC               693.973441
DIC               634.360930
PDIC                0.516203
log(Z)           -137.609861

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:54:51  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  3.6633370910426093e-06 erg / (s cm2)

                                      low bound  \
GBM: total  3.352963683453301e-06 erg / (s cm2)

                                      hi bound
GBM: total  4.04161877234281e-06 erg / (s cm2)
15:54:51  INFO        Bin 9 / 72 complete.
15:54:51  INFO      ==== Time bin 10 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -1350.8773908031667      +/-  0.10626358022914591
 Total Likelihood Evaluations:        39886
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.70 -0.19 +0.26,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-6.26 -0.4 +0.32) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.55 -0.15 +0.20) x 10^2,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval9      -383.269304
n7_interval9      -399.490146
n8_interval9      -372.177113
b1_interval9      -214.137433
total            -1369.073996

Values of statistical measures:

        statistical measures
AIC              2744.198096
BIC              2756.688042
DIC              2697.042588
PDIC                2.343068
log(Z)           -586.678597

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:55:14  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.897953353202876e-06 erg / (s cm2)

                                      low bound  \
GBM: total  4.743776461191066e-06 erg / (s cm2)

                                       hi bound
GBM: total  5.057050349576911e-06 erg / (s cm2)
15:55:14  INFO        Bin 10 / 72 complete.
15:55:14  INFO      ==== Time bin 11 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1158.0866581964776      +/-   9.3692137568296530E-002
 Total Likelihood Evaluations:        33799
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,3.1 -0.4 +0.9,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-8.97 -0.7 +0.35) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.80 -0.23 +0.6) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval10      -319.879080
n7_interval10      -331.761969
n8_interval10      -331.905823
b1_interval10      -195.283976
total             -1178.830848

Values of statistical measures:

        statistical measures
AIC              2363.711801
BIC              2376.201747
DIC              2315.671035
PDIC                1.405694
log(Z)           -502.950645

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:55:35  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.3789009480388596e-06 erg / (s cm2)

                                       low bound  \
GBM: total  2.2413932867134726e-06 erg / (s cm2)

                                        hi bound
GBM: total  2.5283418932569502e-06 erg / (s cm2)
15:55:35  INFO        Bin 11 / 72 complete.
15:55:35  INFO      ==== Time bin 12 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -414.24035311810286      +/-   9.4497848288687000E-002
 Total Likelihood Evaluations:        34606
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.95 -0.23 +0.7,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-6.83 -0.8 +0.32) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.44 -0.24 +0.7) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval11      -163.802340
n7_interval11      -158.967186
n8_interval11      -150.579149
b1_interval11        38.575497
total              -434.773178

Values of statistical measures:

        statistical measures
AIC               875.596461
BIC               888.086407
DIC               827.710961
PDIC                1.431670
log(Z)           -179.902300

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:55:56  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.191821131045563e-06 erg / (s cm2)

                                       low bound  \
GBM: total  5.8160761192934355e-06 erg / (s cm2)

                                       hi bound
GBM: total  6.616130757074584e-06 erg / (s cm2)
15:55:56  INFO        Bin 12 / 72 complete.
15:55:56  INFO      ==== Time bin 13 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -1073.4459008525416      +/-  0.10575787522133934
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        41979
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.69 -0.16 +0.24,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-5.91 -0.35 +0.24) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.87 -0.18 +0.29) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval12      -316.823659
n7_interval12      -319.064882
n8_interval12      -327.629391
b1_interval12      -128.943708
total             -1092.461639

Values of statistical measures:

        statistical measures
AIC              2190.973383
BIC              2203.463328
DIC              2142.789409
PDIC                2.402135
log(Z)           -466.191631

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:56:19  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.068098946047082e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.0343282476285487e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.1025502156444036e-05 erg / (s cm2)
15:56:19  INFO        Bin 13 / 72 complete.
15:56:19  INFO      ==== Time bin 14 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -869.85303311363691      +/-  0.10499222356630199
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        41333
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,2.42 -0.23 +0.35,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-6.32 -0.34 +0.25) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.53 -0.24 +0.4) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval13      -287.100958
n7_interval13      -274.006990
n8_interval13      -264.500621
b1_interval13       -65.105824
total              -890.714392

Values of statistical measures:

        statistical measures
AIC              1787.478889
BIC              1799.968835
DIC              1737.171581
PDIC                2.705437
log(Z)           -377.772372

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:56:41  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.4895335634170644e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.4393803146635858e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.5465881536528926e-05 erg / (s cm2)
15:56:41  INFO        Bin 14 / 72 complete.
15:56:41  INFO      ==== Time bin 15 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -955.86821977754278      +/-  0.10371670681570737
 Total Likelihood Evaluations:        44178
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.66 -0.18 +0.30,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-5.79 -0.4 +0.31) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.06 -0.17 +0.26) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval14      -277.003714
n7_interval14      -304.127949
n8_interval14      -290.346560
b1_interval14      -103.457144
total              -974.935368

Values of statistical measures:

        statistical measures
AIC              1955.920841
BIC              1968.410786
DIC              1908.097379
PDIC                2.193068
log(Z)           -415.128293

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:57:04  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.000950127851436e-06 erg / (s cm2)

                                     low bound  \
GBM: total  7.73117107949206e-06 erg / (s cm2)

                                       hi bound
GBM: total  8.298387476559133e-06 erg / (s cm2)
15:57:04  INFO        Bin 15 / 72 complete.
15:57:04  INFO      ==== Time bin 16 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -153.58634940247535      +/-   9.8941634168761478E-002
 Total Likelihood Evaluations:        35361
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.94 -0.29 +0.5,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-5.6 -0.6 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.96 -0.29 +0.6) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval15       -88.203511
n7_interval15      -107.686267
n8_interval15       -86.356861
b1_interval15       107.309741
total              -174.936898

Values of statistical measures:

        statistical measures
AIC               355.923900
BIC               368.413846
DIC               305.638961
PDIC                1.633280
log(Z)            -66.701704

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:57:24  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.5354570532557215e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.4526615440591262e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.6247990143596944e-05 erg / (s cm2)
15:57:24  INFO        Bin 16 / 72 complete.
15:57:24  INFO      ==== Time bin 17 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -850.41866798934268      +/-  0.10195436944396029
 Total Likelihood Evaluations:        38737
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,2.49 -0.26 +0.5,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-6.74 -0.5 +0.30) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.99 -0.17 +0.33) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval16      -259.311573
n7_interval16      -275.966450
n8_interval16      -256.620008
b1_interval16       -78.550584
total              -870.448615

Values of statistical measures:

        statistical measures
AIC              1746.947334
BIC              1759.437280
DIC              1698.332268
PDIC                2.263533
log(Z)           -369.332135

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:57:45  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.843266107791319e-06 erg / (s cm2)

                                      low bound  \
GBM: total  6.584515790734185e-06 erg / (s cm2)

                                       hi bound
GBM: total  7.104909945837979e-06 erg / (s cm2)
15:57:45  INFO        Bin 17 / 72 complete.
15:57:45  INFO      ==== Time bin 18 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -262.15182785580015      +/-  0.10003216316770637
 Total Likelihood Evaluations:        39283
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.50 -0.20 +0.4,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-5.1 -0.6 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.41 -0.23 +0.4) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval17      -115.071974
n7_interval17      -123.585542
n8_interval17      -136.339743
b1_interval17        92.555496
total              -282.441764

Values of statistical measures:

        statistical measures
AIC               570.933632
BIC               583.423578
DIC               521.959521
PDIC                1.676878
log(Z)           -113.851092

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:58:08  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2508539063163097e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.191764610142865e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.3139112814178864e-05 erg / (s cm2)
15:58:08  INFO        Bin 18 / 72 complete.
15:58:08  INFO      ==== Time bin 19 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1284.4089068490489      +/-  0.11463477135750112
 Total Likelihood Evaluations:        40191
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.80 -0.11 +0.19,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-4.81 -0.24 +0.16) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.95 -0.12 +0.18) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval18      -383.465860
n7_interval18      -375.256641
n8_interval18      -384.302074
b1_interval18      -160.047811
total             -1303.072386

Values of statistical measures:

        statistical measures
AIC              2612.194876
BIC              2624.684822
DIC              2561.929307
PDIC                2.749296
log(Z)           -557.811701

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:58:31  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.2503154667560692e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.2064070291248527e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.2973552531274614e-05 erg / (s cm2)
15:58:31  INFO        Bin 19 / 72 complete.
15:58:31  INFO      ==== Time bin 20 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -509.36961872749310      +/-  0.10509554356422512
 Total Likelihood Evaluations:        42468

 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,2.28 -0.25 +0.5,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-5.32 -0.5 +0.30) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.48 -0.12 +0.22) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval19      -177.617378
n7_interval19      -196.132703
n8_interval19      -188.821487
b1_interval19        32.472757
total              -530.098811

Values of statistical measures:

        statistical measures
AIC              1066.247727
BIC              1078.737672
DIC              1015.491353
PDIC                2.189183
log(Z)           -221.216415

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:58:54  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.0577467395626933e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.0246752815356826e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.0938789563053353e-05 erg / (s cm2)
15:58:54  INFO        Bin 20 / 72 complete.
15:58:54  INFO      ==== Time bin 21 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -702.38905633130707      +/-  0.10966136518391922
 Total Likelihood Evaluations:        46193
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.99 -0.16 +0.28,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-4.61 -0.32 +0.20) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.99 -0.14 +0.25) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval20      -237.064790
n7_interval20      -237.001136
n8_interval20      -241.143390
b1_interval20        -7.657688
total              -722.867004

Values of statistical measures:

        statistical measures
AIC              1451.784112
BIC              1464.274058
DIC              1400.344494
PDIC                2.589281
log(Z)           -305.043691

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:59:17  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.8484548255664582e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.7713600553407965e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.9280593426366638e-05 erg / (s cm2)
15:59:17  INFO        Bin 21 / 72 complete.
15:59:17  INFO      ==== Time bin 22 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -5.0174539874771176      +/-  0.10682682842176511
 Total Likelihood Evaluations:        41931
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.68 -0.20 +0.34,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-3.67 -0.4 +0.30) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.35 -0.23 +0.34) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval21       -65.175603
n7_interval21       -64.365634
n8_interval21       -57.011785
b1_interval21       159.355654
total               -27.197369

Values of statistical measures:

        statistical measures
AIC                60.444842
BIC                72.934787
DIC                 7.007481
PDIC                2.188496
log(Z)             -2.179053

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

15:59:39  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  4.9175608982128074e-05 erg / (s cm2)

                                      low bound  \
GBM: total  4.736341056924994e-05 erg / (s cm2)

                                       hi bound
GBM: total  5.112917068669371e-05 erg / (s cm2)
15:59:39  INFO        Bin 22 / 72 complete.
15:59:39  INFO      ==== Time bin 23 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -780.81475309430323      +/-  0.11730237157752534
 Total Likelihood Evaluations:        43663
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.85 -0.12 +0.19,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-3.17 -0.23 +0.15) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.14 -0.11 +0.15) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval22      -259.949484
n7_interval22      -266.076806
n8_interval22      -254.170584
b1_interval22       -21.333077
total              -801.529951

Values of statistical measures:

        statistical measures
AIC              1609.110007
BIC              1621.599952
DIC              1554.848897
PDIC                2.733799
log(Z)           -339.103539

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:00:02  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.810207259910474e-05 erg / (s cm2)

                                      low bound  \
GBM: total  6.686227678469899e-05 erg / (s cm2)

                                       hi bound
GBM: total  6.932526965040569e-05 erg / (s cm2)
16:00:02  INFO        Bin 23 / 72 complete.
16:00:02  INFO      ==== Time bin 24 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   253.49350940540359      +/-  0.10421779254544196
 Total Likelihood Evaluations:        41592
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,2.68 -0.35 +0.7,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-4.2 -0.6 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.69 -0.15 +0.26) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval23        10.493563
n7_interval23       -11.155410
n8_interval23        11.765177
b1_interval23       219.525039
total               230.628368

Values of statistical measures:

        statistical measures
AIC              -455.206632
BIC              -442.716687
DIC              -509.133920
PDIC                1.899711
log(Z)            110.090832

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:00:25  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.6080899001192643e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.5077861535478504e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.7187776028584687e-05 erg / (s cm2)
16:00:25  INFO        Bin 24 / 72 complete.
16:00:25  INFO      ==== Time bin 25 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   22.667201292231038      +/-  0.10651638158281899
 Total Likelihood Evaluations:        45969
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,2.07 -0.28 +0.6,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-3.8 -0.7 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(1.74 -0.09 +0.18) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval24       -60.944634
n7_interval24       -56.692799
n8_interval24       -51.607308
b1_interval24       169.251888
total                 0.007147

Values of statistical measures:

        statistical measures
AIC                 6.035810
BIC                18.525755
DIC               -48.764993
PDIC                1.501880
log(Z)              9.844240

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:00:48  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2371832111438892e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.193641252628199e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.281568221356613e-05 erg / (s cm2)
16:00:48  INFO        Bin 25 / 72 complete.
16:00:48  INFO      ==== Time bin 26 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   86.083049365919493      +/-   9.5624854565610914E-002
 Total Likelihood Evaluations:        34353
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,5.7 -0.7 +1.9,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-7.4 -0.8 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.28 -0.18 +0.4) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval25       -35.353591
n7_interval25       -50.879482
n8_interval25       -28.929521
b1_interval25       176.982440
total                61.819846

Values of statistical measures:

        statistical measures
AIC              -117.589588
BIC              -105.099642
DIC              -171.536020
PDIC                1.436667
log(Z)             37.385393

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:01:07  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  7.642960101802654e-06 erg / (s cm2)

                                      low bound  \
GBM: total  7.255247678055825e-06 erg / (s cm2)

                                       hi bound
GBM: total  8.063061185881757e-06 erg / (s cm2)
16:01:07  INFO        Bin 26 / 72 complete.
16:01:07  INFO      ==== Time bin 27 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -414.80223884404842      +/-   9.7479886087390430E-002
 Total Likelihood Evaluations:        34989
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,6.0 -0.8 +1.6,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-8.3 -0.7 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.00 -0.15 +0.33) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval26      -135.070950
n7_interval26      -169.842985
n8_interval26      -166.975611
b1_interval26        33.573712
total              -438.315835

Values of statistical measures:

        statistical measures
AIC               882.681774
BIC               895.171719
DIC               829.674810
PDIC                1.748560
log(Z)           -180.146323

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:01:27  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.398616797023705e-06 erg / (s cm2)

                                       low bound  \
GBM: total  4.2003058173748405e-06 erg / (s cm2)

                                       hi bound
GBM: total  4.612894589202106e-06 erg / (s cm2)
16:01:27  INFO        Bin 27 / 72 complete.
16:01:27  INFO      ==== Time bin 28 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -388.90978286608646      +/-  0.10023301480384778
 Total Likelihood Evaluations:        37034
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,2.95 -0.33 +0.7,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-6.35 -0.6 +0.31) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.98 -0.18 +0.4) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval27      -147.979432
n7_interval27      -158.039033
n8_interval27      -145.691890
b1_interval27        41.323918
total              -410.386436

Values of statistical measures:

        statistical measures
AIC               826.822977
BIC               839.312923
DIC               776.220894
PDIC                1.962639
log(Z)           -168.901373

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:01:47  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.0096096166092214e-05 erg / (s cm2)

                                     low bound  \
GBM: total  9.68259196795132e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.0559586702677892e-05 erg / (s cm2)
16:01:47  INFO        Bin 28 / 72 complete.
16:01:47  INFO      ==== Time bin 29 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -87.670044692607533      +/-  0.10639998537261658
 Total Likelihood Evaluations:        46832
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,3.17 -0.31 +0.5,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-5.50 -0.4 +0.23) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(6.12 -0.30 +0.6) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval28       -83.340331
n7_interval28       -74.482303
n8_interval28       -85.379096
b1_interval28       129.087546
total              -114.114183

Values of statistical measures:

        statistical measures
AIC               234.278470
BIC               246.768416
DIC               174.998598
PDIC                2.477247
log(Z)            -38.074617

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:02:08  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.994481074952095e-05 erg / (s cm2)

                                      low bound  \
GBM: total  4.785117161109889e-05 erg / (s cm2)

                                       hi bound
GBM: total  5.210408056717117e-05 erg / (s cm2)
16:02:08  INFO        Bin 29 / 72 complete.
16:02:08  INFO      ==== Time bin 30 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   50.443136426689108      +/-  0.11034509609578316
 Total Likelihood Evaluations:        42305
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.98 -0.24 +0.31,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-3.10 -0.35 +0.30) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.10 -0.20 +0.26) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval29       -49.130680
n7_interval29       -61.966628
n8_interval29       -57.994854
b1_interval29       196.888315
total                27.796154

Values of statistical measures:

        statistical measures
AIC               -49.542204
BIC               -37.052258
DIC              -104.723404
PDIC                2.302277
log(Z)             21.907176

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:02:29  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  7.505936606136106e-05 erg / (s cm2)

                                      low bound  \
GBM: total  7.271336042016238e-05 erg / (s cm2)

                                       hi bound
GBM: total  7.757464508181049e-05 erg / (s cm2)
16:02:29  INFO        Bin 30 / 72 complete.
16:02:29  INFO      ==== Time bin 31 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=   170.74653340826484      +/-  0.11025399342365143
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        45640
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,2.58 -0.31 +0.4,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-3.31 -0.32 +0.29) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.99 -0.25 +0.30) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval30       -11.831865
n7_interval30       -13.540359
n8_interval30       -18.435481
b1_interval30       189.761020
total               145.953315

Values of statistical measures:

        statistical measures
AIC              -285.856526
BIC              -273.366580
DIC              -344.234257
PDIC                2.340447
log(Z)             74.154277

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:02:50  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  0.00011934416670299895 erg / (s cm2)

                                       low bound  \
GBM: total  0.00011546138158564478 erg / (s cm2)

                                        hi bound
GBM: total  0.00012352718902133733 erg / (s cm2)
16:02:50  INFO        Bin 31 / 72 complete.
16:02:50  INFO      ==== Time bin 32 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -445.09061377724464      +/-  0.11053167794868561
 Total Likelihood Evaluations:        46192
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,4.9 -0.4 +0.6,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-4.88 -0.27 +0.20) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(5.07 -0.21 +0.31) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval31      -135.020095
n7_interval31      -169.518519
n8_interval31      -140.518609
b1_interval31       -25.286445
total              -470.343667

Values of statistical measures:

        statistical measures
AIC               946.737438
BIC               959.227384
DIC               888.021000
PDIC                2.702423
log(Z)           -193.300398

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:03:12  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.706869657056889e-05 erg / (s cm2)

                                      low bound  \
GBM: total  8.461199063529456e-05 erg / (s cm2)

                                       hi bound
GBM: total  8.957978277099703e-05 erg / (s cm2)
16:03:12  INFO        Bin 32 / 72 complete.
16:03:12  INFO      ==== Time bin 33 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=   430.56145243927267      +/-  0.10250798514133608
 Total Likelihood Evaluations:        37509
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,3.3 -0.4 +1.0,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-4.52 -0.7 +0.35) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.60 -0.15 +0.31) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval32        32.447529
n7_interval32        45.706294
n8_interval32        41.003821
b1_interval32       287.719644
total               406.877287

Values of statistical measures:

        statistical measures
AIC              -807.704470
BIC              -795.214525
DIC              -862.571537
PDIC                1.690305
log(Z)            186.990463

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:03:33  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.560614189058644e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.4549839798412944e-05 erg / (s cm2)

                                      hi bound
GBM: total  2.67192854956632e-05 erg / (s cm2)
16:03:33  INFO        Bin 33 / 72 complete.
16:03:33  INFO      ==== Time bin 34 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -695.27544767131337      +/-  0.10647649025442203
 Total Likelihood Evaluations:        46299
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,5.1 -0.4 +0.7,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-6.36 -0.4 +0.21) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.72 -0.11 +0.19) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval33      -224.434372
n7_interval33      -245.009425
n8_interval33      -238.496106
b1_interval33        -9.805771
total              -717.745674

Values of statistical measures:

        statistical measures
AIC              1441.541453
BIC              1454.031399
DIC              1387.978476
PDIC                2.487970
log(Z)           -301.954290

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:03:54  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.5255506083909909e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.4878601690371047e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.5645328945237094e-05 erg / (s cm2)
16:03:54  INFO        Bin 34 / 72 complete.
16:03:54  INFO      ==== Time bin 35 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -733.99273916123741      +/-  0.10246263561639092
 Total Likelihood Evaluations:        36820
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,9.1 -1.2 +0.5,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-8.99 -0.15 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.65 -0.24 +0.14) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval34      -235.905947
n7_interval34      -251.260967
n8_interval34      -238.491814
b1_interval34       -31.863478
total              -757.522205

Values of statistical measures:

        statistical measures
AIC              1521.094515
BIC              1533.584460
DIC              1466.955963
PDIC                2.306982
log(Z)           -318.768996

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:04:13  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.290028161483241e-06 erg / (s cm2)

                                      low bound  \
GBM: total  6.077165028704016e-06 erg / (s cm2)

                                        hi bound
GBM: total  6.5247683523332754e-06 erg / (s cm2)
16:04:13  INFO        Bin 35 / 72 complete.
16:04:13  INFO      ==== Time bin 36 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -651.49983317581791      +/-   9.6810656437621975E-002
 Total Likelihood Evaluations:        37304
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,7.3 -0.9 +1.4,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-9.1 -0.5 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.47 -0.18 +0.4) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval35      -220.161560
n7_interval35      -225.943829
n8_interval35      -205.910755
b1_interval35       -23.170432
total              -675.186575

Values of statistical measures:

        statistical measures
AIC              1356.423255
BIC              1368.913201
DIC              1303.591730
PDIC                2.084153
log(Z)           -282.942783

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:04:32  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.573775654207962e-06 erg / (s cm2)

                                      low bound  \
GBM: total  4.374871007274838e-06 erg / (s cm2)

                                       hi bound
GBM: total  4.782802433741357e-06 erg / (s cm2)
16:04:32  INFO        Bin 36 / 72 complete.
16:04:32  INFO      ==== Time bin 37 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -444.71419732710046      +/-  0.10001763683196702
 Total Likelihood Evaluations:        39499
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,4.7 -0.5 +0.8,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-7.23 -0.4 +0.28) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.15 -0.27 +0.4) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval36      -168.427570
n7_interval36      -165.815050
n8_interval36      -178.236337
b1_interval36        44.583388
total              -467.895569

Values of statistical measures:

        statistical measures
AIC               941.841242
BIC               954.331188
DIC               889.302648
PDIC                2.440374
log(Z)           -193.136922

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:04:52  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.500263980103197e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.4414668469612207e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.565348078249357e-05 erg / (s cm2)
16:04:52  INFO        Bin 37 / 72 complete.
16:04:52  INFO      ==== Time bin 38 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -527.03440309054849      +/-  0.10528306268029544
 Total Likelihood Evaluations:        40919
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,4.1 -0.4 +0.5,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-6.16 -0.31 +0.26) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.41 -0.24 +0.33) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval37      -186.345709
n7_interval37      -200.501757
n8_interval37      -196.563604
b1_interval37        33.464626
total              -549.946444

Values of statistical measures:

        statistical measures
AIC              1105.942993
BIC              1118.432939
DIC              1052.240032
PDIC                2.569701
log(Z)           -228.888133

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:05:13  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.6523762329768386e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.5650058967077718e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.7479000119438834e-05 erg / (s cm2)
16:05:13  INFO        Bin 38 / 72 complete.
16:05:13  INFO      ==== Time bin 39 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -785.43907578028836      +/-  0.11130133328097452
 Total Likelihood Evaluations:        43423
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,3.91 -0.29 +0.4,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-5.56 -0.21 +0.19) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.91 -0.19 +0.23) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval38      -255.973457
n7_interval38      -272.911138
n8_interval38      -248.155963
b1_interval38       -31.365553
total              -808.406111

Values of statistical measures:

        statistical measures
AIC              1622.862327
BIC              1635.352273
DIC              1567.327273
PDIC                2.771586
log(Z)           -341.111856

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:05:34  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.268456556977962e-05 erg / (s cm2)

                                      low bound  \
GBM: total  4.164997048945944e-05 erg / (s cm2)

                                      hi bound
GBM: total  4.37265875283344e-05 erg / (s cm2)
16:05:34  INFO        Bin 39 / 72 complete.
16:05:34  INFO      ==== Time bin 40 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -249.83068257399964      +/-  0.10972007894908979
 Total Likelihood Evaluations:        40219
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,3.34 -0.29 +0.5,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-4.78 -0.31 +0.21) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.83 -0.20 +0.31) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval39      -125.402565
n7_interval39      -137.477796
n8_interval39      -127.960983
b1_interval39       117.522405
total              -273.318938

Values of statistical measures:

        statistical measures
AIC               552.687981
BIC               565.177926
DIC               496.923555
PDIC                2.729099
log(Z)           -108.500087

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:05:56  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.819942440974346e-05 erg / (s cm2)

                                      low bound  \
GBM: total  5.645334266049658e-05 erg / (s cm2)

                                        hi bound
GBM: total  5.9919569569191914e-05 erg / (s cm2)
16:05:56  INFO        Bin 40 / 72 complete.
16:05:56  INFO      ==== Time bin 41 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -639.43067650381636      +/-  0.11494264413365925
 Total Likelihood Evaluations:        47283
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,3.09 -0.23 +0.28,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-3.88 -0.21 +0.17) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.43 -0.14 +0.18) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval40      -214.606263
n7_interval40      -223.777924
n8_interval40      -223.107800
b1_interval40        -0.527489
total              -662.019477

Values of statistical measures:

        statistical measures
AIC              1330.089058
BIC              1342.579004
DIC              1273.920436
PDIC                2.814779
log(Z)           -277.701214

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:06:18  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.227952722120515e-05 erg / (s cm2)

                                      low bound  \
GBM: total  8.057534950831735e-05 erg / (s cm2)

                                       hi bound
GBM: total  8.400015220939637e-05 erg / (s cm2)
16:06:18  INFO        Bin 41 / 72 complete.
16:06:18  INFO      ==== Time bin 42 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=   129.32834019111547      +/-  0.10639958902410425
 Total Likelihood Evaluations:        43862
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,3.7 -0.4 +0.7,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-4.33 -0.4 +0.29) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.33 -0.15 +0.24) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval41       -30.727372
n7_interval41       -46.787280
n8_interval41       -33.621993
b1_interval41       216.851395
total               105.714750

Values of statistical measures:

        statistical measures
AIC              -205.379396
BIC              -192.889451
DIC              -260.710350
PDIC                2.368041
log(Z)             56.166584

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:06:40  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  4.7398820826549054e-05 erg / (s cm2)

                                      low bound  \
GBM: total  4.594219116320035e-05 erg / (s cm2)

                                       hi bound
GBM: total  4.894721912984728e-05 erg / (s cm2)
16:06:40  INFO        Bin 42 / 72 complete.
16:06:40  INFO      ==== Time bin 43 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -39.235929315381902      +/-  0.10689358410402887
 Total Likelihood Evaluations:        45223
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,4.0 -0.4 +0.7,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-4.79 -0.4 +0.30) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.47 -0.12 +0.18) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval42       -70.196908
n7_interval42       -99.061298
n8_interval42       -77.282820
b1_interval42       184.001187
total               -62.539840

Values of statistical measures:

        statistical measures
AIC               131.129784
BIC               143.619730
DIC                76.098439
PDIC                2.352381
log(Z)            -17.039948

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:07:01  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.4975550586773548e-05 erg / (s cm2)

                                      low bound  \
GBM: total  2.426741597770793e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.574339745811379e-05 erg / (s cm2)
16:07:01  INFO        Bin 43 / 72 complete.
16:07:01  INFO      ==== Time bin 44 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1484.8902986116871      +/-  0.11158843620994560
 Total Likelihood Evaluations:        45664
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,6.8 -0.4 +0.5,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-7.32 -0.18 +0.13) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.66 -0.10 +0.17) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval43      -427.547153
n7_interval43      -438.030542
n8_interval43      -425.219017
b1_interval43      -215.737173
total             -1506.533885

Values of statistical measures:

        statistical measures
AIC              3019.117875
BIC              3031.607820
DIC              2965.701375
PDIC                2.967522
log(Z)           -644.879663

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:07:23  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.743582220859218e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.7121019758898227e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.774750591001894e-05 erg / (s cm2)
16:07:23  INFO        Bin 44 / 72 complete.
16:07:23  INFO      ==== Time bin 45 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -209.32627891224124      +/-  0.10480559310112385
 Total Likelihood Evaluations:        41343
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,4.4 -0.4 +0.7,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-5.63 -0.4 +0.25) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.57 -0.16 +0.29) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval44      -121.996384
n7_interval44      -120.089617
n8_interval44      -111.159967
b1_interval44       120.850289
total              -232.395679

Values of statistical measures:

        statistical measures
AIC               470.841462
BIC               483.331408
DIC               416.945526
PDIC                2.471254
log(Z)            -90.909248

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:07:44  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.8915820415340464e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.7996048311017822e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.9878113604375813e-05 erg / (s cm2)
16:07:44  INFO        Bin 45 / 72 complete.
16:07:44  INFO      ==== Time bin 46 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -569.03998457481714      +/-  0.10501617351590364
 Total Likelihood Evaluations:        43480
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,5.5 -0.5 +0.8,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-6.57 -0.4 +0.23) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.77 -0.12 +0.22) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval45      -207.348789
n7_interval45      -215.898102
n8_interval45      -201.041839
b1_interval45        32.472871
total              -591.815860

Values of statistical measures:

        statistical measures
AIC              1189.681825
BIC              1202.171770
DIC              1136.288341
PDIC                2.589913
log(Z)           -247.130925

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:08:05  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.5102970180910255e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.467691872909947e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.554832698394148e-05 erg / (s cm2)
16:08:05  INFO        Bin 46 / 72 complete.
16:08:05  INFO      ==== Time bin 47 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -598.96474073932291      +/-  0.10494887647969954
 Total Likelihood Evaluations:        41020
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,4.1 -0.4 +0.7,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-6.47 -0.5 +0.30) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.36 -0.13 +0.20) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval46      -204.028130
n7_interval46      -212.692708
n8_interval46      -203.413242
b1_interval46        -0.757829
total              -620.891909

Values of statistical measures:

        statistical measures
AIC              1247.833923
BIC              1260.323868
DIC              1195.342303
PDIC                2.235521
log(Z)           -260.127082

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:08:26  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  9.489541266377855e-06 erg / (s cm2)

                                      low bound  \
GBM: total  9.197166876570368e-06 erg / (s cm2)

                                       hi bound
GBM: total  9.784346467259738e-06 erg / (s cm2)
16:08:26  INFO        Bin 47 / 72 complete.
16:08:26  INFO      ==== Time bin 48 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=   415.67234039295317      +/-   9.0453159045951581E-002
 Total Likelihood Evaluations:        29147
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,6.3 -0.9 +2.5,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-8.3 -1.0 +0.5) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.17 -0.22 +0.6) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval47        59.862914
n7_interval47        43.519084
n8_interval47        54.165217
b1_interval47       232.966976
total               390.514191

Values of statistical measures:

        statistical measures
AIC              -774.978277
BIC              -762.488332
DIC              -829.271590
PDIC                1.069918
log(Z)            180.524204

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:08:43  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  5.15366918723873e-06 erg / (s cm2)

                                      low bound  \
GBM: total  4.772575593775221e-06 erg / (s cm2)

                                       hi bound
GBM: total  5.628309734126032e-06 erg / (s cm2)
16:08:43  INFO        Bin 48 / 72 complete.
16:08:43  INFO      ==== Time bin 49 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -492.63628324548000      +/-  0.10263685986909747
 Total Likelihood Evaluations:        36869
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,5.0 -0.5 +0.9,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-7.03 -0.5 +0.32) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.51 -0.16 +0.24) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval48      -184.010057
n7_interval48      -180.674670
n8_interval48      -183.137627
b1_interval48        32.710737
total              -515.111617

Values of statistical measures:

        statistical measures
AIC              1036.273338
BIC              1048.763284
DIC               983.726323
PDIC                2.258142
log(Z)           -213.949219

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:09:04  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  9.12962116487203e-06 erg / (s cm2)

                                      low bound  \
GBM: total  8.827402967674163e-06 erg / (s cm2)

                                       hi bound
GBM: total  9.466396376034292e-06 erg / (s cm2)
16:09:04  INFO        Bin 49 / 72 complete.
16:09:04  INFO      ==== Time bin 50 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -48.346345196355315      +/-  0.10205213960678342
 Total Likelihood Evaluations:        35256
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,3.4 -0.4 +0.7,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-5.77 -0.5 +0.32) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.98 -0.25 +0.4) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval49       -72.875607
n7_interval49       -85.068627
n8_interval49       -73.396343
b1_interval49       160.218114
total               -71.122463

Values of statistical measures:

        statistical measures
AIC               148.295030
BIC               160.784975
DIC                95.504914
PDIC                2.197270
log(Z)            -20.996551

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:09:24  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.4291927337956054e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.3203896184944994e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.538324298370515e-05 erg / (s cm2)
16:09:24  INFO        Bin 50 / 72 complete.
16:09:24  INFO      ==== Time bin 51 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   172.19569938734571      +/-  0.10392455347273387
 Total Likelihood Evaluations:        41117
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,3.1 -0.4 +0.6,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-4.93 -0.4 +0.30) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(5.04 -0.29 +0.5) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval50       -16.045170
n7_interval50       -35.641532
n8_interval50       -24.814235
b1_interval50       224.018374
total               147.517437

Values of statistical measures:

        statistical measures
AIC              -288.984769
BIC              -276.494824
DIC              -345.129736
PDIC                2.258892
log(Z)             74.783642

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:09:45  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.241570874949469e-05 erg / (s cm2)

                                       low bound  \
GBM: total  5.0115070992047815e-05 erg / (s cm2)

                                        hi bound
GBM: total  5.4808158550878536e-05 erg / (s cm2)
16:09:45  INFO        Bin 51 / 72 complete.
16:09:45  INFO      ==== Time bin 52 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -115.63143056552204      +/-  0.10708846164452944
 Total Likelihood Evaluations:        41325
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,2.54 -0.26 +0.6,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-4.28 -0.5 +0.29) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.37 -0.12 +0.21) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval51       -88.933509
n7_interval51       -94.716312
n8_interval51       -94.301105
b1_interval51       140.157675
total              -137.793252

Values of statistical measures:

        statistical measures
AIC               281.636607
BIC               294.126553
DIC               228.030554
PDIC                2.122461
log(Z)            -50.218092

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:10:06  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.9582275976616265e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.8966547642467142e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.028156255852263e-05 erg / (s cm2)
16:10:06  INFO        Bin 52 / 72 complete.
16:10:06  INFO      ==== Time bin 53 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -597.76669715284856      +/-  0.10432217831111176
 Total Likelihood Evaluations:        44744
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,4.7 -0.5 +0.6,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-6.48 -0.4 +0.31) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.64 -0.14 +0.18) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval52      -210.409447
n7_interval52      -224.858033
n8_interval52      -197.033113
b1_interval52        12.180381
total              -620.120211

Values of statistical measures:

        statistical measures
AIC              1246.290526
BIC              1258.780472
DIC              1193.664844
PDIC                2.517932
log(Z)           -259.606778

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:10:27  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2425321459994197e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.2072876798814025e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.2801058011580482e-05 erg / (s cm2)
16:10:27  INFO        Bin 53 / 72 complete.
16:10:27  INFO      ==== Time bin 54 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -537.96262314892363      +/-  0.10394973205128118
 Total Likelihood Evaluations:        37509
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,5.4 -0.6 +1.0,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-7.12 -0.5 +0.34) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.16 -0.12 +0.22) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval53      -175.410786
n7_interval53      -195.584737
n8_interval53      -197.109453
b1_interval53         7.460331
total              -560.644645

Values of statistical measures:

        statistical measures
AIC              1127.339395
BIC              1139.829341
DIC              1074.199980
PDIC                2.327835
log(Z)           -233.634199

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:10:48  INFO        10 keV-10 MeV flux =                                         flux  \
GBM: total  7.864469311575e-06 erg / (s cm2)

                                      low bound  \
GBM: total  7.619622394272681e-06 erg / (s cm2)

                                       hi bound
GBM: total  8.134839636699937e-06 erg / (s cm2)
16:10:48  INFO        Bin 54 / 72 complete.
16:10:48  INFO      ==== Time bin 55 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -378.45551204941791      +/-  0.10153304206106169
 Total Likelihood Evaluations:        38165
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,9.99 -1.8 -0.21,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-9.71 +0.04 +0.6) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(1.75 -0.25 +0.06) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval54      -132.517869
n7_interval54      -156.704465
n8_interval54      -145.407167
b1_interval54        32.146275
total              -402.483226

Values of statistical measures:

        statistical measures
AIC               811.016556
BIC               823.506501
DIC               756.384290
PDIC                2.155254
log(Z)           -164.361141

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:11:08  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.9972579219820913e-06 erg / (s cm2)

                                     low bound  \
GBM: total  2.86407514835465e-06 erg / (s cm2)

                                        hi bound
GBM: total  3.1376949577457095e-06 erg / (s cm2)
16:11:08  INFO        Bin 55 / 72 complete.
16:11:08  INFO      ==== Time bin 56 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -1096.7054709844758      +/-   9.8061579379417008E-002
 Total Likelihood Evaluations:        36810
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,10.00 -1.9 -0.25,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.176 +0.005 +0.07,
GBM.spectrum.main.Cutoff_powerlaw.xc,(1.94 -0.30 +0.10) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval55      -326.729851
n7_interval55      -319.123261
n8_interval55      -309.229634
b1_interval55      -165.484526
total             -1120.567274

Values of statistical measures:

        statistical measures
AIC              2247.184651
BIC              2259.674597
DIC              2193.615568
PDIC                2.058548
log(Z)           -476.293134

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:11:28  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2719199773194263e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.2107295352186937e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.3344267939020236e-06 erg / (s cm2)
16:11:28  INFO        Bin 56 / 72 complete.
16:11:28  INFO      ==== Time bin 57 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -1586.7002152548785      +/-   8.9412116080812884E-002
 Total Likelihood Evaluations:        30995
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,9.60 -2.0 +0.05,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.358 -0.005 +0.08,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.5 -0.9 +0.4) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval56      -425.291717
n7_interval56      -450.718100
n8_interval56      -437.797584
b1_interval56      -297.832963
total             -1611.640365

Values of statistical measures:

        statistical measures
AIC              3229.330833
BIC              3241.820779
DIC              3176.350319
PDIC                1.941481
log(Z)           -689.095148

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:11:47  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.026322596702862e-07 erg / (s cm2)

                                      low bound  \
GBM: total  7.456493972389183e-07 erg / (s cm2)

                                       hi bound
GBM: total  8.642735229757657e-07 erg / (s cm2)
16:11:47  INFO        Bin 57 / 72 complete.
16:11:47  INFO      ==== Time bin 58 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -1615.2630919067917      +/-   7.8492390840284157E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        26301
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,4.1 -0.5 +2.3,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.29 -0.14 +0.04,
GBM.spectrum.main.Cutoff_powerlaw.xc,(2.75 -0.34 +1.8) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval57      -459.099806
n7_interval57      -439.768188
n8_interval57      -429.378260
b1_interval57      -310.475554
total             -1638.721808

Values of statistical measures:

        statistical measures
AIC              3283.493720
BIC              3295.983666
DIC              3235.121823
PDIC                0.845340
log(Z)           -701.499848

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:12:03  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  4.1756086460869635e-07 erg / (s cm2)

                                      low bound  \
GBM: total  3.740232788195009e-07 erg / (s cm2)

                                        hi bound
GBM: total  4.6607223261319287e-07 erg / (s cm2)
16:12:03  INFO        Bin 58 / 72 complete.
16:12:03  INFO      ==== Time bin 59 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3171.1330273892659      +/-   8.5872409805109309E-002
 Total Likelihood Evaluations:        32267

 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,3.6 -0.5 +0.9,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.45 -0.06 +0.04,
GBM.spectrum.main.Cutoff_powerlaw.xc,(5.0 -0.9 +1.8) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval58      -823.379663
n7_interval58      -830.306896
n8_interval58      -827.947957
b1_interval58      -713.573488
total             -3195.208004

Values of statistical measures:

        statistical measures
AIC              6396.466113
BIC              6408.956058
DIC              6347.273441
PDIC                2.481406
log(Z)          -1377.205575

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:12:23  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.5302918438443256e-07 erg / (s cm2)

                                       low bound  \
GBM: total  2.3087846037093154e-07 erg / (s cm2)

                                        hi bound
GBM: total  2.7674107820725993e-07 erg / (s cm2)
16:12:23  INFO        Bin 59 / 72 complete.
16:12:23  INFO      ==== Time bin 60 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -2654.9666422017999      +/-   6.4796653482842970E-002
 Total Likelihood Evaluations:        19471
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.37 -0.34 +2.0,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.47 -0.26 +0.07,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.6 -1.0 +2.1) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval59      -704.539202
n7_interval59      -699.489774
n8_interval59      -699.238566
b1_interval59      -573.492464
total             -2676.760006

Values of statistical measures:

        statistical measures
AIC              5359.570116
BIC              5372.060061
DIC              5317.013775
PDIC                0.417561
log(Z)          -1153.037362

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:12:38  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.414575036781649e-08 erg / (s cm2)

                                       low bound  \
GBM: total  5.0497253576318554e-08 erg / (s cm2)

                                       hi bound
GBM: total  8.034679077869742e-08 erg / (s cm2)
16:12:38  INFO        Bin 60 / 72 complete.
16:12:38  INFO      ==== Time bin 61 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3771.1425812047319      +/-   2.5501603994625692E-002
 Total Likelihood Evaluations:         5144
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,(0.010 +0.017 +4) x 10^-3,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.26 -0.5 +0.34,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.0 -1.5 +2.1) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval60      -969.555319
n7_interval60      -964.824504
n8_interval60      -966.489857
b1_interval60      -848.585196
total             -3749.454876

Values of statistical measures:

        statistical measures
AIC              7504.959856
BIC              7517.449802
DIC              7534.735859
PDIC               -4.067069
log(Z)          -1637.786413

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:12:46  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  3.0398634371042546e-11 erg / (s cm2)

                                      low bound  \
GBM: total  1.882724029285971e-12 erg / (s cm2)

                                        hi bound
GBM: total  3.7871371486814553e-10 erg / (s cm2)
16:12:46  INFO        Bin 61 / 72 complete.
16:12:46  INFO      ==== Time bin 62 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -1721.0907601004992      +/-   6.0411956098099996E-002
 Total Likelihood Evaluations:        16673
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,(0.26 +0.08 +2.8) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-5.5 -6 -0.7) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.1 -0.5 +2.5) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval61      -457.182863
n7_interval61      -478.094990
n8_interval61      -460.278706
b1_interval61      -336.015553
total             -1731.572112

Values of statistical measures:

        statistical measures
AIC              3469.194329
BIC              3481.684274
DIC              3436.402998
PDIC               -8.344578
log(Z)           -747.460220

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:13:00  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2900928677166186e-07 erg / (s cm2)

                                      low bound  \
GBM: total  8.815217130887993e-08 erg / (s cm2)

                                        hi bound
GBM: total  1.8638438638819653e-07 erg / (s cm2)
16:13:00  INFO        Bin 62 / 72 complete.
16:13:00  INFO      ==== Time bin 63 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -2690.5995861651368      +/-   8.9537033452658371E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        29593
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,(4.1 -0.6 +1.7) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-8.5 -0.9 +0.4) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.4 -0.5 +1.3) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval62      -704.283708
n7_interval62      -713.831206
n8_interval62      -705.139508
b1_interval62      -582.209267
total             -2705.463690

Values of statistical measures:

        statistical measures
AIC              5416.977484
BIC              5429.467429
DIC              5378.688008
PDIC                0.796343
log(Z)          -1168.512553

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:13:18  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.697381375299298e-07 erg / (s cm2)

                                      low bound  \
GBM: total  6.113343791221405e-07 erg / (s cm2)

                                       hi bound
GBM: total  7.391815699183438e-07 erg / (s cm2)
16:13:18  INFO        Bin 63 / 72 complete.
16:13:18  INFO      ==== Time bin 64 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -2378.5256356376185      +/-   9.0894622229716809E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        30702
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.18 -0.13 +0.35,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,(-9.92 -0.7 +0.30) x 10^-1,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.3 -0.4 +1.2) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval63      -627.337238
n7_interval63      -632.503485
n8_interval63      -636.118522
b1_interval63      -500.487291
total             -2396.446536

Values of statistical measures:

        statistical measures
AIC              4798.943176
BIC              4811.433122
DIC              4756.560907
PDIC                1.721936
log(Z)          -1032.980559

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:13:36  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.580838028910636e-07 erg / (s cm2)

                                      low bound  \
GBM: total  7.913312384345238e-07 erg / (s cm2)

                                       hi bound
GBM: total  9.263074891685907e-07 erg / (s cm2)
16:13:36  INFO        Bin 64 / 72 complete.
16:13:36  INFO      ==== Time bin 65 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3073.0813789040590      +/-  0.10214812850641732
 Total Likelihood Evaluations:        43589
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,4.17 -0.25 +0.4,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.134 -0.025 +0.018,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.71 -0.31 +0.5) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval64      -806.612156
n7_interval64      -809.215014
n8_interval64      -806.614100
b1_interval64      -671.311200
total             -3093.752470

Values of statistical measures:

        statistical measures
AIC              6193.555045
BIC              6206.044991
DIC              6144.397194
PDIC                2.690653
log(Z)          -1334.622285

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:13:57  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.4677877102515299e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.4213632913174116e-06 erg / (s cm2)

                                       hi bound
GBM: total  1.520029602431438e-06 erg / (s cm2)
16:13:57  INFO        Bin 65 / 72 complete.
16:13:57  INFO      ==== Time bin 66 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -2160.4045758421903      +/-   9.0672470297117919E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        33544
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,4.0 -0.4 +0.9,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.173 -0.06 +0.032,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.8 -0.4 +1.0) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval65      -572.253778
n7_interval65      -580.633227
n8_interval65      -574.313309
b1_interval65      -454.751247
total             -2181.951561

Values of statistical measures:

        statistical measures
AIC              4369.953227
BIC              4382.443173
DIC              4322.298261
PDIC                1.974285
log(Z)           -938.251786

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:14:16  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  9.57307097171332e-07 erg / (s cm2)

                                      low bound  \
GBM: total  8.987286440073267e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.0249371331733521e-06 erg / (s cm2)
16:14:16  INFO        Bin 66 / 72 complete.
16:14:16  INFO      ==== Time bin 67 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -1742.4700529669071      +/-   9.3779949536250518E-002
 Total Likelihood Evaluations:        29685
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,5.8 -0.6 +1.1,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.148 -0.05 +0.034,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.8 -0.4 +0.8) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval66      -472.841817
n7_interval66      -475.507627
n8_interval66      -475.516337
b1_interval66      -341.008083
total             -1764.873863

Values of statistical measures:

        statistical measures
AIC              3535.797831
BIC              3548.287776
DIC              3486.150640
PDIC                2.176562
log(Z)           -756.745129

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:14:35  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.5635522107633398e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.4783319965273516e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.6608069630444807e-06 erg / (s cm2)
16:14:35  INFO        Bin 67 / 72 complete.
16:14:35  INFO      ==== Time bin 68 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
 ln(ev)=  -2163.9772305473293      +/-   9.2274466659382062E-002
 Total Likelihood Evaluations:        33707
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,6.8 -0.6 +1.2,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.272 -0.05 +0.029,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.9 -0.5 +0.9) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval67      -569.848439
n7_interval67      -589.461230
n8_interval67      -583.463679
b1_interval67      -444.560969
total             -2187.334317

Values of statistical measures:

        statistical measures
AIC              4380.718738
BIC              4393.208683
DIC              4330.132393
PDIC                2.280729
log(Z)           -939.803370

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:14:55  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  9.874681241708394e-07 erg / (s cm2)

                                    low bound  \
GBM: total  9.3337286198101e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.0434080456839887e-06 erg / (s cm2)
16:14:55  INFO        Bin 68 / 72 complete.
16:14:55  INFO      ==== Time bin 69 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2067.1861583717100      +/-   8.8058706369699341E-002
 Total Likelihood Evaluations:        30402
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,5.7 -0.7 +1.2,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.33 -0.06 +0.04,
GBM.spectrum.main.Cutoff_powerlaw.xc,(4.7 -0.6 +1.5) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval68      -542.176326
n7_interval68      -567.352092
n8_interval68      -552.450892
b1_interval68      -429.792800
total             -2091.772110

Values of statistical measures:

        statistical measures
AIC              4189.594325
BIC              4202.084271
DIC              4138.595708
PDIC                2.233792
log(Z)           -897.767542

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:15:13  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.997640422019173e-07 erg / (s cm2)

                                      low bound  \
GBM: total  6.509420310457633e-07 erg / (s cm2)

                                       hi bound
GBM: total  7.599409329552545e-07 erg / (s cm2)
16:15:13  INFO        Bin 69 / 72 complete.
16:15:13  INFO      ==== Time bin 70 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2242.1729979167603      +/-   8.3730124921715846E-002
 Total Likelihood Evaluations:        26151
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,4.7 -0.6 +1.4,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.38 -0.08 +0.04,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.7 -0.5 +1.7) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval69      -593.519548
n7_interval69      -606.049844
n8_interval69      -581.514654
b1_interval69      -484.588644
total             -2265.672690

Values of statistical measures:

        statistical measures
AIC              4537.395485
BIC              4549.885430
DIC              4488.789124
PDIC                1.821903
log(Z)           -973.763360

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:15:31  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  3.792161226971516e-07 erg / (s cm2)

                                      low bound  \
GBM: total  3.455773391538768e-07 erg / (s cm2)

                                       hi bound
GBM: total  4.168596590756984e-07 erg / (s cm2)
16:15:31  INFO        Bin 70 / 72 complete.
16:15:31  INFO      ==== Time bin 71 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -3434.5017073520617      +/-   8.1619086100827770E-002
 Total Likelihood Evaluations:        27797
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,2.24 -0.31 +0.8,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.38 -0.10 +0.04,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.5 -0.5 +1.8) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval70      -896.060842
n7_interval70      -893.828172
n8_interval70      -874.359629
b1_interval70      -791.004786
total             -3455.253429

Values of statistical measures:

        statistical measures
AIC              6916.556963
BIC              6929.046909
DIC              6872.150448
PDIC                1.400520
log(Z)          -1491.585140

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:15:49  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.7449260608780476e-07 erg / (s cm2)

                                       low bound  \
GBM: total  1.5897896797763862e-07 erg / (s cm2)

                                       hi bound
GBM: total  1.913525581643235e-07 erg / (s cm2)
16:15:49  INFO        Bin 71 / 72 complete.
16:15:49  INFO      ==== Time bin 72 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    3
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3027.0813135684489      +/-   6.7603718134816054E-002
 Total Likelihood Evaluations:        19741
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.Cutoff_powerlaw.K,1.02 -0.28 +1.0,1 / (keV s cm2)
GBM.spectrum.main.Cutoff_powerlaw.index,-1.43 -0.19 +0.08,
GBM.spectrum.main.Cutoff_powerlaw.xc,(3.5 -0.9 +2.2) x 10^2,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval71      -771.612139
n7_interval71      -782.442745
n8_interval71      -775.538880
b1_interval71      -717.502496
total             -3047.096260

Values of statistical measures:

        statistical measures
AIC              6100.242624
BIC              6112.732570
DIC              6060.019168
PDIC                0.940487
log(Z)          -1314.644711

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:16:05  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  5.8651911857265776e-08 erg / (s cm2)

                                      low bound  \
GBM: total  4.807534505839048e-08 erg / (s cm2)

                                       hi bound
GBM: total  7.083513678137137e-08 erg / (s cm2)
16:16:05  INFO        Bin 72 / 72 complete.

All 72 bins fitted successfully.

## Cell 11 — Save Results to CSV

In [12]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    fit_array = np.array(fit_rows)
    cutoffpl_fit_param = Table(fit_array, names=PARAM_NAMES)

    # ── Attach bin edges as extra columns ────────────────────────────────
    cutoffpl_fit_param['t_start'] = bb_starts
    cutoffpl_fit_param['t_stop']  = bb_stops
    cutoffpl_fit_param['dt']      = bb_stops - bb_starts

    csv_path = os.path.join(MODEL_PATHS['root'], 'fit_params.csv')
    cutoffpl_fit_param.write(csv_path, overwrite=True)

    print(f'Results saved to: {csv_path}')
    print(f'Shape: {fit_array.shape}  ({n_bins} bins x 16 parameters)')
    cutoffpl_fit_param

Results saved to: gbm_pipeline_output/cutoffpl/fit_params.csv
Shape: (72, 18)  (72 bins x 16 parameters)

## Cell 10 — Time-Resolved Spectral Fitting (Band Model)

In [13]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    MODEL_PATHS = get_model_paths('band')

    PARAM_NAMES = [
        'B_K',     'B_K_n_err',     'B_K_p_err',     'B_K_avg_err',
        'B_alpha', 'B_alpha_n_err', 'B_alpha_p_err',  'B_alpha_avg_err',
        'E_peak',  'E_peak_n_err',  'E_peak_p_err',   'E_peak_avg_err',
        'beta',    'beta_n_err',    'beta_p_err',      'beta_avg_err',
        'flux',    'flux_low',      'flux_hi', 'DIC', 'PDIC', 'BIC'
    ]

    fit_rows = []

    for i in range(n_bins):
        log.info('==== Time bin %d / %d ====', i + 1, n_bins)

        # ── Assemble per-detector plugins for this bin ────────────────────
        det_plugins = []
        for det in detectors:
            p = time_resolved_plugins[det][i]
            if det.startswith('b'):
                p.set_active_measurements(CONFIG['bgo_range'])
            else:
                ranges = [r.strip() for r in CONFIG['nai_range'].split(',')]
                p.set_active_measurements(*ranges)
            det_plugins.append(p)

        data_list = DataList(*det_plugins)

        # ── Fresh Band model per bin ──────────────────────────────────────
        model = build_band_model(CONFIG['ra'], CONFIG['dec'], CONFIG['priors_band'])

        # ── Bayesian fit with MultiNest ───────────────────────────────────
        bayes = BayesianAnalysis(model, data_list)
        bayes.set_sampler('multinest')
        bayes.sampler.setup(n_live_points=CONFIG['n_live_points'], sampling_efficiency=CONFIG['sampling_efficiency'], auto_clean=True)
        bayes.sample()

        # ── νFν spectrum plot ─────────────────────────────────────────────
        fig_spec = plot_spectra(
            bayes.results,
            ene_min=1.0, ene_max=1e5, num_ene=200,
            contour_colors='white',
            contour_style_kwargs=dict(alpha=0.2),
            use_components=True, components_to_use=['total'],
            flux_unit='keV2/(cm2 s keV)',
        )
        ax = plt.gca()
        ax.set_xlabel('Energy (keV)', fontsize=16)
        ax.set_ylabel(r'$\nu\,F_\nu\;[\mathrm{keV\,cm^{-2}\,s^{-1}}]$', fontsize=16)
        ax.set_title(f"{CONFIG['trigger_name']}  bin {i+1}/{n_bins}  "
                     f"[{bb_starts[i]:.3f}, {bb_stops[i]:.3f}] s", fontsize=13)
        fig_spec.savefig(
            os.path.join(MODEL_PATHS['spectra'], f'band_spec_bin{i+1:03d}.png'),
            dpi=120, bbox_inches='tight')
        plt.close('all')

        # ── Corner plot ───────────────────────────────────────────────────
        fig_corner = bayes.results.corner_plot()
        fig_corner.savefig(
            os.path.join(MODEL_PATHS['corners'], f'band_corner_bin{i+1:03d}.png'),
            dpi=100, bbox_inches='tight')
        plt.close('all')

        # ── Integrated flux ───────────────────────────────────────────────
        flux_df = bayes.results.get_point_source_flux(10 * u.keV, 10 * u.MeV)
        log.info('  10 keV-10 MeV flux = %s', flux_df)

        # Extract the raw floats by stripping the astropy units (.value)
        f_val = flux_df['flux'].iloc[0].value
        f_low = flux_df['low bound'].iloc[0].value
        f_hi  = flux_df['hi bound'].iloc[0].value

        # ── Collect parameters ────────────────────────────────────────────
        df  = bayes.results.get_data_frame('equal tail')
        df  = df.drop('unit', axis=1, errors='ignore')
        param_array = df.to_numpy().flatten()

        stat_df = bayes.results.get_statistic_measure_frame()
        dic_val = stat_df.loc['DIC'].iloc[0] if 'DIC' in stat_df.index else np.nan
        pdic_val = stat_df.loc['PDIC'].iloc[0] if 'PDIC' in stat_df.index else np.nan
        bic_val = stat_df.loc['BIC'].iloc[0] if 'BIC' in stat_df.index else np.nan

        full_row = np.append(param_array, [f_val, f_low, f_hi, dic_val, pdic_val, bic_val])
        fit_rows.append(full_row)
        log.info('  Bin %d / %d complete.', i + 1, n_bins)

    print(f'\nAll {n_bins} bins fitted successfully.')

16:16:05  INFO      ==== Time bin 1 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2474.3184871741792      +/-   4.6148681448063805E-002
 Total Likelihood Evaluations:        13802
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K      (1.00 +0.26 +3.0) x 10^-4  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha     (-8.7 -2.0 +7) x 10^-1
GBM.spectrum.main.Band.xp        (3.0 -1.1 +2.5) x 10^2              keV
GBM.spectrum.main.Band.beta              -2.6 -0.8 +0.5

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval0      -636.706107
n7_interval0      -641.210928
n8_interval0      -632.767568
b1_interval0      -552.183703
total            -2462.868307

Values of statistical measures:

        statistical measures
AIC              4933.820295
BIC              4950.456680
DIC              4945.553814
PDIC                1.649835
log(Z)          -1074.582865

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:16:23  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.588032046218118e-08 erg / (s cm2)

                                      low bound  \
GBM: total  6.268353798548171e-09 erg / (s cm2)

                                       hi bound
GBM: total  3.932011652418344e-08 erg / (s cm2)
16:16:23  INFO        Bin 1 / 72 complete.
16:16:23  INFO      ==== Time bin 2 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2641.4012390319931      +/-   8.4429034805120692E-002
 Total Likelihood Evaluations:        28116
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                result             unit
parameter
GBM.spectrum.main.Band.K         (8.9 +/- 1.0) x 10^-3  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-8.3 -1.0 +0.8) x 10^-1
GBM.spectrum.main.Band.xp       (3.5 -0.4 +0.9) x 10^2              keV
GBM.spectrum.main.Band.beta           -2.24 -0.9 +0.14

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval1      -694.815291
n7_interval1      -687.812522
n8_interval1      -688.696313
b1_interval1      -570.121775
total            -2641.445901

Values of statistical measures:

        statistical measures
AIC              5290.975484
BIC              5307.611869
DIC              5276.468759
PDIC                3.029222
log(Z)          -1147.145983

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:16:45  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.783297242567012e-07 erg / (s cm2)

                                      low bound  \
GBM: total  5.682986364949868e-07 erg / (s cm2)

                                       hi bound
GBM: total  8.475274328680121e-07 erg / (s cm2)
16:16:45  INFO        Bin 2 / 72 complete.
16:16:45  INFO      ==== Time bin 3 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1743.4357555466918      +/-   8.9261494281702519E-002
 Total Likelihood Evaluations:        33043
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K      (2.85 -0.8 +0.17) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha   (-5.5 -2.3 +0.5) x 10^-1
GBM.spectrum.main.Band.xp      (2.27 -0.08 +1.1) x 10^2              keV
GBM.spectrum.main.Band.beta          -1.999 -1.0 +0.018

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval2      -468.783602
n7_interval2      -472.760980
n8_interval2      -463.719573
b1_interval2      -343.130801
total            -1748.394955

Values of statistical measures:

        statistical measures
AIC              3504.873593
BIC              3521.509978
DIC              3478.104449
PDIC               -0.044762
log(Z)           -757.164528

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:17:10  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.4647818843807594e-06 erg / (s cm2)

                                     low bound  \
GBM: total  1.16956138092014e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.8485303892503734e-06 erg / (s cm2)
16:17:10  INFO        Bin 3 / 72 complete.
16:17:10  INFO      ==== Time bin 4 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2323.7013801911608      +/-   8.9233772626172408E-002
 Total Likelihood Evaluations:        31589
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.46 -0.14 +0.18) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha      (-8.5 +/- 0.8) x 10^-1
GBM.spectrum.main.Band.xp      (2.55 -0.28 +0.30) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.88 -0.7 +0.35

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval3      -606.146189
n7_interval3      -612.823867
n8_interval3      -608.626695
b1_interval3      -497.501965
total            -2325.098716

Values of statistical measures:

        statistical measures
AIC              4658.281114
BIC              4674.917499
DIC              4640.845133
PDIC                3.461863
log(Z)          -1009.170687

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:17:34  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.183983738375176e-07 erg / (s cm2)

                                      low bound  \
GBM: total  5.596711954587808e-07 erg / (s cm2)

                                       hi bound
GBM: total  7.132118351416929e-07 erg / (s cm2)
16:17:34  INFO        Bin 4 / 72 complete.
16:17:34  INFO      ==== Time bin 5 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1620.6039156454553      +/-   9.1668077846185025E-002

 Total Likelihood Evaluations:        34284
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                result             unit
parameter
GBM.spectrum.main.Band.K       (3.1 -0.6 +0.5) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-7.7 -1.4 +0.9) x 10^-1
GBM.spectrum.main.Band.xp     (1.98 -0.19 +0.6) x 10^2              keV
GBM.spectrum.main.Band.beta           -2.09 -0.6 +0.09

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval4      -438.799289
n7_interval4      -446.269487
n8_interval4      -443.446315
b1_interval4      -296.169136
total            -1624.684227

Values of statistical measures:

        statistical measures
AIC              3257.452136
BIC              3274.088520
DIC              3233.315136
PDIC                1.616816
log(Z)           -703.819338

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:17:59  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.4576909063470979e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.1600383798211145e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.7895097676296442e-06 erg / (s cm2)
16:17:59  INFO        Bin 5 / 72 complete.
16:17:59  INFO      ==== Time bin 6 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -1360.7481196537440      +/-   9.1665808255616349E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        32293
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K      (3.96 -0.31 +0.4) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha   (-8.1 -0.6 +0.7) x 10^-1
GBM.spectrum.main.Band.xp     (3.23 -0.33 +0.35) x 10^2              keV
GBM.spectrum.main.Band.beta              -3.0 -0.7 +0.4

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval5      -386.745452
n7_interval5      -377.953573
n8_interval5      -365.766224
b1_interval5      -235.527052
total            -1365.992300

Values of statistical measures:

        statistical measures
AIC              2740.068283
BIC              2756.704668
DIC              2716.038253
PDIC                3.337255
log(Z)           -590.965400

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:18:22  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.160554263890905e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.9908614826121864e-06 erg / (s cm2)

                                       hi bound
GBM: total  2.428824782828256e-06 erg / (s cm2)
16:18:22  INFO        Bin 6 / 72 complete.
16:18:22  INFO      ==== Time bin 7 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -676.16253108558431      +/-   9.1079147398100413E-002
 Total Likelihood Evaluations:        31809
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                result             unit
parameter
GBM.spectrum.main.Band.K       (7.3 -1.0 +0.8) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-5.4 -1.2 +0.8) x 10^-1
GBM.spectrum.main.Band.xp     (2.65 -0.21 +0.4) x 10^2              keV
GBM.spectrum.main.Band.beta           -2.47 -0.9 +0.14

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval6      -199.936124
n7_interval6      -213.508247
n8_interval6      -214.249350
b1_interval6       -56.872091
total             -684.565811

Values of statistical measures:

        statistical measures
AIC              1377.215304
BIC              1393.851689
DIC              1348.311025
PDIC                3.056346
log(Z)           -293.653656

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:18:46  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  3.3078684152250224e-06 erg / (s cm2)

                                       low bound  \
GBM: total  2.8862960640149644e-06 erg / (s cm2)

                                       hi bound
GBM: total  3.950580382774183e-06 erg / (s cm2)
16:18:46  INFO        Bin 7 / 72 complete.
16:18:46  INFO      ==== Time bin 8 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1581.0848389288890      +/-   9.9227861783921581E-002
 Total Likelihood Evaluations:        41109
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K        (5.5 -1.1 +1.0) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha   (-6.5 -1.4 +1.0) x 10^-1
GBM.spectrum.main.Band.xp     (1.62 -0.16 +0.33) x 10^2              keV
GBM.spectrum.main.Band.beta           -2.10 -0.27 +0.08

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval7      -430.950220
n7_interval7      -437.941788
n8_interval7      -429.476374
b1_interval7      -288.600658
total            -1586.969040

Values of statistical measures:

        statistical measures
AIC              3182.021761
BIC              3198.658146
DIC              3152.453466
PDIC                1.089272
log(Z)           -686.656421

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:19:13  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.9924726699238875e-06 erg / (s cm2)

                                      low bound  \
GBM: total  1.686855366759396e-06 erg / (s cm2)

                                        hi bound
GBM: total  2.2944920021749117e-06 erg / (s cm2)
16:19:13  INFO        Bin 8 / 72 complete.
16:19:13  INFO      ==== Time bin 9 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -316.03270319953043      +/-   8.4578937368806451E-002
 Total Likelihood Evaluations:        24960
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                result             unit
parameter
GBM.spectrum.main.Band.K       (5.0 -0.4 +0.6) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-7.9 -0.7 +1.0) x 10^-1
GBM.spectrum.main.Band.xp       (4.3 -0.6 +0.8) x 10^2              keV
GBM.spectrum.main.Band.beta           -2.32 -1.0 +0.18

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval8      -120.398670
n7_interval8      -124.860860
n8_interval8      -121.974715
b1_interval8        43.295789
total             -323.938457

Values of statistical measures:

        statistical measures
AIC               655.960595
BIC               672.596980
DIC               629.807461
PDIC                3.213147
log(Z)           -137.251259

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:19:34  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.485054112557051e-06 erg / (s cm2)

                                       low bound  \
GBM: total  3.8183976690379586e-06 erg / (s cm2)

                                        hi bound
GBM: total  5.5608628804305685e-06 erg / (s cm2)
16:19:34  INFO        Bin 9 / 72 complete.
16:19:34  INFO      ==== Time bin 10 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -1345.3481187542970      +/-  0.10390634321762007
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        41047
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.07 -0.07 +0.08) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-5.4 -0.6 +0.5) x 10^-1
GBM.spectrum.main.Band.xp      (3.01 -0.19 +0.26) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.40 -0.33 +0.11

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval9      -378.975175
n7_interval9      -396.117152
n8_interval9      -367.511759
b1_interval9      -209.961338
total            -1352.565424

Values of statistical measures:

        statistical measures
AIC              2713.214531
BIC              2729.850916
DIC              2682.936389
PDIC                3.714458
log(Z)           -584.277264

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:20:01  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  6.39938889948774e-06 erg / (s cm2)

                                      low bound  \
GBM: total  5.786120450104825e-06 erg / (s cm2)

                                       hi bound
GBM: total  7.004522788647178e-06 erg / (s cm2)
16:20:01  INFO        Bin 10 / 72 complete.
16:20:01  INFO      ==== Time bin 11 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1154.8540334312906      +/-   9.4754360206681418E-002
 Total Likelihood Evaluations:        39522
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                result             unit
parameter
GBM.spectrum.main.Band.K       (6.0 -0.7 +0.6) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-7.9 -0.9 +0.6) x 10^-1
GBM.spectrum.main.Band.xp     (2.42 -0.22 +0.4) x 10^2              keV
GBM.spectrum.main.Band.beta           -2.17 -0.4 +0.09

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval10      -316.089392
n7_interval10      -327.644424
n8_interval10      -327.301002
b1_interval10      -189.339406
total             -1160.374224

Values of statistical measures:

        statistical measures
AIC              2328.832129
BIC              2345.468514
DIC              2303.659432
PDIC                3.543268
log(Z)           -501.546734

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:20:27  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  3.32468938579458e-06 erg / (s cm2)

                                     low bound  \
GBM: total  2.81503562311504e-06 erg / (s cm2)

                                       hi bound
GBM: total  3.823318864963866e-06 erg / (s cm2)
16:20:27  INFO        Bin 11 / 72 complete.
16:20:27  INFO      ==== Time bin 12 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -413.46584797093533      +/-   9.2240183771343798E-002
 Total Likelihood Evaluations:        30062
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                              result             unit
parameter
GBM.spectrum.main.Band.K       (8.6 +/- 0.6) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-6.7 +/- 0.6) x 10^-1
GBM.spectrum.main.Band.xp     (4.3 -0.4 +0.5) x 10^2              keV
GBM.spectrum.main.Band.beta         -2.73 -0.7 +0.21

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval11      -160.794571
n7_interval11      -155.908854
n8_interval11      -147.835215
b1_interval11        41.924261
total              -422.614378

Values of statistical measures:

        statistical measures
AIC               853.312439
BIC               869.948823
DIC               823.361988
PDIC                3.388224
log(Z)           -179.565936

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:20:49  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.984673729735087e-06 erg / (s cm2)

                                      low bound  \
GBM: total  6.370899263196219e-06 erg / (s cm2)

                                      hi bound
GBM: total  7.77262636281254e-06 erg / (s cm2)
16:20:49  INFO        Bin 12 / 72 complete.
16:20:49  INFO      ==== Time bin 13 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1072.7957034189853      +/-  0.10615612433455136
 Total Likelihood Evaluations:        43146
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                    result             unit
parameter
GBM.spectrum.main.Band.K      (1.109 -0.031 +0.04) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha   (-5.94 -0.27 +0.34) x 10^-1
GBM.spectrum.main.Band.xp        (5.44 -0.26 +0.22) x 10^2              keV
GBM.spectrum.main.Band.beta               -3.32 -0.4 +0.29

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval12      -314.929924
n7_interval12      -316.991128
n8_interval12      -325.813852
b1_interval12      -126.217923
total             -1083.952827

Values of statistical measures:

        statistical measures
AIC              2175.989336
BIC              2192.625720
DIC              2138.981095
PDIC                3.659210
log(Z)           -465.909254

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:21:15  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.150041285357188e-05 erg / (s cm2)

                                     low bound  \
GBM: total  1.10180258817229e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.2108425982497191e-05 erg / (s cm2)
16:21:15  INFO        Bin 13 / 72 complete.
16:21:15  INFO      ==== Time bin 14 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -870.98941702844866      +/-  0.10725678228798295
 Total Likelihood Evaluations:        42840
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                    result             unit
parameter
GBM.spectrum.main.Band.K      (1.331 -0.035 +0.05) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha   (-6.24 -0.28 +0.32) x 10^-1
GBM.spectrum.main.Band.xp        (6.06 -0.32 +0.28) x 10^2              keV
GBM.spectrum.main.Band.beta               -3.49 -0.30 +0.4

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval13      -285.419595
n7_interval13      -272.350964
n8_interval13      -262.772682
b1_interval13       -64.264025
total              -884.807266

Values of statistical measures:

        statistical measures
AIC              1777.698213
BIC              1794.334598
DIC              1735.903449
PDIC                3.433387
log(Z)           -378.265898

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:21:42  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.574101524213719e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.513700789449126e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.645899015662635e-05 erg / (s cm2)
16:21:42  INFO        Bin 14 / 72 complete.
16:21:42  INFO      ==== Time bin 15 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -954.28312033972384      +/-  0.10167813033839908
 Total Likelihood Evaluations:        34698
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K        (1.20 +/- 0.06) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha   (-5.5 -0.5 +0.4) x 10^-1
GBM.spectrum.main.Band.xp     (4.07 -0.24 +0.27) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.83 -0.5 +0.25

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval14      -274.042635
n7_interval14      -301.533031
n8_interval14      -287.269555
b1_interval14      -100.536812
total              -963.382033

Values of statistical measures:

        statistical measures
AIC              1934.847748
BIC              1951.484132
DIC              1902.443509
PDIC                3.643097
log(Z)           -414.439893

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:22:06  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  9.168940460336187e-06 erg / (s cm2)

                                      low bound  \
GBM: total  8.543592879111735e-06 erg / (s cm2)

                                       hi bound
GBM: total  9.994887224163344e-06 erg / (s cm2)
16:22:06  INFO        Bin 15 / 72 complete.
16:22:06  INFO      ==== Time bin 16 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -149.01944343874317      +/-   9.7609033437931425E-002
 Total Likelihood Evaluations:        36751
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.59 -0.10 +0.13) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-5.0 -0.6 +0.7) x 10^-1
GBM.spectrum.main.Band.xp         (4.9 -0.5 +0.6) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.40 -0.4 +0.15

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval15       -85.386809
n7_interval15      -105.047492
n8_interval15       -83.433628
b1_interval15       112.552676
total              -161.315253

Values of statistical measures:

        statistical measures
AIC               330.714188
BIC               347.350573
DIC               294.940841
PDIC                3.778557
log(Z)            -64.718322

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:22:32  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.9089994407134178e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.735972426469045e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.096487638469772e-05 erg / (s cm2)
16:22:32  INFO        Bin 16 / 72 complete.
16:22:32  INFO      ==== Time bin 17 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -848.81982647353675      +/-   9.8184182475519313E-002
 Total Likelihood Evaluations:        36999
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.13 -0.05 +0.07) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-6.7 -0.4 +0.5) x 10^-1
GBM.spectrum.main.Band.xp      (3.84 -0.27 +0.26) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.78 -0.6 +0.21

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval16      -256.016619
n7_interval16      -273.000766
n8_interval16      -253.523700
b1_interval16       -74.959866
total              -857.500950

Values of statistical measures:

        statistical measures
AIC              1723.085582
BIC              1739.721966
DIC              1692.329364
PDIC                3.564364
log(Z)           -368.637767

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:22:56  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  7.793291504217496e-06 erg / (s cm2)

                                       low bound  \
GBM: total  7.2235937059530485e-06 erg / (s cm2)

                                       hi bound
GBM: total  8.594939434437516e-06 erg / (s cm2)
16:22:56  INFO        Bin 17 / 72 complete.
16:22:56  INFO      ==== Time bin 18 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -261.50401039692377      +/-   9.6764960356621868E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        34444
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                result             unit
parameter
GBM.spectrum.main.Band.K       (1.51 +/- 0.11) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-4.6 -0.7 +0.6) x 10^-1
GBM.spectrum.main.Band.xp       (4.5 -0.4 +0.5) x 10^2              keV
GBM.spectrum.main.Band.beta           -2.69 -0.7 +0.17

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval17      -112.512659
n7_interval17      -120.539841
n8_interval17      -134.549482
b1_interval17        93.866451
total              -273.735531

Values of statistical measures:

        statistical measures
AIC               555.554744
BIC               572.191129
DIC               519.865914
PDIC                3.415373
log(Z)           -113.569749

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:23:20  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.4046921257708505e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.296668155833755e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.541217881080867e-05 erg / (s cm2)
16:23:20  INFO        Bin 18 / 72 complete.
16:23:20  INFO      ==== Time bin 19 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -1284.6497034525241      +/-  0.11522387410805192
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        48999
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                    result             unit
parameter
GBM.spectrum.main.Band.K      (1.984 -0.034 +0.05) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha   (-4.73 -0.19 +0.24) x 10^-1
GBM.spectrum.main.Band.xp        (5.87 -0.20 +0.15) x 10^2              keV
GBM.spectrum.main.Band.beta              -3.53 -0.28 +0.31

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval18      -382.068918
n7_interval18      -374.221100
n8_interval18      -382.845188
b1_interval18      -159.829756
total             -1298.964961

Values of statistical measures:

        statistical measures
AIC              2606.013605
BIC              2622.649989
DIC              2560.920499
PDIC                3.510766
log(Z)           -557.916277

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:23:47  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.373423157722377e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.3110426056101228e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.4492161923977026e-05 erg / (s cm2)
16:23:47  INFO        Bin 19 / 72 complete.
16:23:47  INFO      ==== Time bin 20 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -508.14532559257896      +/-  0.10070698995523490
 Total Likelihood Evaluations:        37111
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (2.01 -0.10 +0.13) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-5.2 -0.4 +0.5) x 10^-1
GBM.spectrum.main.Band.xp      (3.51 -0.21 +0.20) x 10^2              keV
GBM.spectrum.main.Band.beta             -3.00 -0.6 +0.26

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval19      -175.002190
n7_interval19      -193.554901
n8_interval19      -186.117354
b1_interval19        34.919560
total              -519.754884

Values of statistical measures:

        statistical measures
AIC              1047.593450
BIC              1064.229835
DIC              1011.616768
PDIC                3.549579
log(Z)           -220.684711

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:24:11  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.1759916509857216e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.1062569292309879e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.2753373901449873e-05 erg / (s cm2)
16:24:12  INFO        Bin 20 / 72 complete.
16:24:12  INFO      ==== Time bin 21 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -700.78178543315062      +/-  0.11068306787747451
 Total Likelihood Evaluations:        46534
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                   result             unit
parameter
GBM.spectrum.main.Band.K       (2.44 -0.08 +0.05) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-4.39 -0.33 +0.24) x 10^-1
GBM.spectrum.main.Band.xp       (5.84 -0.18 +0.30) x 10^2              keV
GBM.spectrum.main.Band.beta              -3.23 -0.4 +0.24

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval20      -234.769572
n7_interval20      -235.823039
n8_interval20      -239.646940
b1_interval20        -5.855584
total              -716.095135

Values of statistical measures:

        statistical measures
AIC              1440.273953
BIC              1456.910337
DIC              1395.676778
PDIC                3.709275
log(Z)           -304.345662

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:24:38  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  3.055414487933861e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.9464895438939808e-05 erg / (s cm2)

                                       hi bound
GBM: total  3.177109889736737e-05 erg / (s cm2)
16:24:38  INFO        Bin 21 / 72 complete.
16:24:38  INFO      ==== Time bin 22 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   2.4972561154683541      +/-  0.10917573492084770
 Total Likelihood Evaluations:        46896
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (3.29 -0.14 +0.12) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-3.0 -0.5 +0.4) x 10^-1
GBM.spectrum.main.Band.xp       (6.31 -0.33 +0.4) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.70 -0.24 +0.14

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval21       -63.761309
n7_interval21       -62.782668
n8_interval21       -56.756776
b1_interval21       167.370600
total               -15.930153

Values of statistical measures:

        statistical measures
AIC                39.943987
BIC                56.580372
DIC                -8.583243
PDIC                3.956103
log(Z)              1.084545

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:25:06  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.652608875841017e-05 erg / (s cm2)

                                      low bound  \
GBM: total  5.376387747099944e-05 erg / (s cm2)

                                       hi bound
GBM: total  5.948756948063589e-05 erg / (s cm2)
16:25:06  INFO        Bin 22 / 72 complete.
16:25:06  INFO      ==== Time bin 23 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -777.04449264632638      +/-  0.12037592778572173
 Total Likelihood Evaluations:        53224
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                   result             unit
parameter
GBM.spectrum.main.Band.K       (4.41 -0.11 +0.06) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-2.90 -0.25 +0.19) x 10^-1
GBM.spectrum.main.Band.xp       (6.62 -0.12 +0.23) x 10^2              keV
GBM.spectrum.main.Band.beta              -3.33 -0.4 +0.12

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval22      -259.119170
n7_interval22      -267.022451
n8_interval22      -253.505317
b1_interval22       -17.138823
total              -796.785761

Values of statistical measures:

        statistical measures
AIC              1601.655204
BIC              1618.291588
DIC              1547.286588
PDIC                3.831785
log(Z)           -337.466135

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:25:34  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  7.184429025662974e-05 erg / (s cm2)

                                      low bound  \
GBM: total  7.020482386691583e-05 erg / (s cm2)

                                       hi bound
GBM: total  7.373614573768041e-05 erg / (s cm2)
16:25:34  INFO        Bin 23 / 72 complete.
16:25:34  INFO      ==== Time bin 24 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=   255.27189913514019      +/-   9.9877209432555195E-002
 Total Likelihood Evaluations:        37752
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (4.02 -0.25 +0.21) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-3.8 -0.7 +0.4) x 10^-1
GBM.spectrum.main.Band.xp      (3.96 -0.19 +0.31) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.93 -0.6 +0.19

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval23        12.749998
n7_interval23        -9.118337
n8_interval23        14.228314
b1_interval23       221.557738
total               239.417714

Values of statistical measures:

        statistical measures
AIC              -470.751746
BIC              -454.115362
DIC              -512.817097
PDIC                3.618958
log(Z)            110.863177

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:25:58  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.911879303424508e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.7394193126020332e-05 erg / (s cm2)

                                       hi bound
GBM: total  3.134516740594135e-05 erg / (s cm2)
16:25:58  INFO        Bin 24 / 72 complete.
16:25:58  INFO      ==== Time bin 25 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   26.466506005480184      +/-  0.10229470088965192
 Total Likelihood Evaluations:        38112
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K      (3.99 -0.4 +0.34) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha   (-3.0 -0.8 +0.7) x 10^-1
GBM.spectrum.main.Band.xp     (2.51 -0.14 +0.21) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.66 -0.4 +0.15

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval24       -56.121548
n7_interval24       -53.276189
n8_interval24       -49.972239
b1_interval24       170.610461
total                11.240485

Values of statistical measures:

        statistical measures
AIC               -14.397289
BIC                 2.239096
DIC               -56.217904
PDIC                3.692347
log(Z)             11.494258

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:26:24  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.4925385091117796e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.3662044096140609e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.6399959004578393e-05 erg / (s cm2)
16:26:24  INFO        Bin 25 / 72 complete.
16:26:24  INFO      ==== Time bin 26 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=   88.543102145963331      +/-   9.2731869921965956E-002
 Total Likelihood Evaluations:        36119
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K        (2.09 +/- 0.24) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha     (-6.8 +/- 0.8) x 10^-1
GBM.spectrum.main.Band.xp     (2.51 -0.22 +0.34) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.58 -0.5 +0.17

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval25       -31.902160
n7_interval25       -46.743990
n8_interval25       -25.628450
b1_interval25       181.296713
total                77.022112

Values of statistical measures:

        statistical measures
AIC              -145.960542
BIC              -129.324158
DIC              -179.653356
PDIC                3.391249
log(Z)             38.453781

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:26:48  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  9.019358719444336e-06 erg / (s cm2)

                                      low bound  \
GBM: total  8.161752246589015e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.0173127474857688e-05 erg / (s cm2)
16:26:48  INFO        Bin 26 / 72 complete.
16:26:48  INFO      ==== Time bin 27 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -414.34724509505082      +/-   9.5489889914436632E-002
 Total Likelihood Evaluations:        33426
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.43 -0.17 +0.11) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-7.9 -0.8 +0.5) x 10^-1
GBM.spectrum.main.Band.xp      (2.17 -0.14 +0.27) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.81 -0.7 +0.20

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval26      -131.419974
n7_interval26      -166.432918
n8_interval26      -162.741412
b1_interval26        36.583533
total              -424.010770

Values of statistical measures:

        statistical measures
AIC               856.105223
BIC               872.741607
DIC               824.365801
PDIC                3.345455
log(Z)           -179.948722

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:27:11  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.890369637129038e-06 erg / (s cm2)

                                      low bound  \
GBM: total  4.545234509208326e-06 erg / (s cm2)

                                        hi bound
GBM: total  5.4340448983040586e-06 erg / (s cm2)
16:27:11  INFO        Bin 27 / 72 complete.
16:27:11  INFO      ==== Time bin 28 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -386.02889520941613      +/-   9.6238024250929990E-002
 Total Likelihood Evaluations:        37034
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.67 -0.12 +0.09) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-6.1 -0.6 +0.5) x 10^-1
GBM.spectrum.main.Band.xp       (3.76 -0.22 +0.4) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.55 -0.6 +0.17

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval27      -145.152601
n7_interval27      -155.070273
n8_interval27      -143.153343
b1_interval27        46.788011
total              -396.588206

Values of statistical measures:

        statistical measures
AIC               801.260094
BIC               817.896479
DIC               768.283690
PDIC                3.644455
log(Z)           -167.650219

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:27:36  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2207553180433733e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.1023208076299745e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.368648357452392e-05 erg / (s cm2)
16:27:36  INFO        Bin 28 / 72 complete.
16:27:36  INFO      ==== Time bin 29 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -81.112217602565352      +/-  0.11152924171493267
 Total Likelihood Evaluations:        51917

 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (2.70 -0.10 +0.09) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-4.78 -0.5 +0.32) x 10^-1
GBM.spectrum.main.Band.xp         (7.4 -0.4 +0.6) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.54 -0.26 +0.10

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval28       -81.980227
n7_interval28       -72.244153
n8_interval28       -83.031699
b1_interval28       136.365083
total              -100.890996

Values of statistical measures:

        statistical measures
AIC               209.865675
BIC               226.502060
DIC               158.606688
PDIC                3.879545
log(Z)            -35.226589

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:28:05  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.581453966055929e-05 erg / (s cm2)

                                       low bound  \
GBM: total  5.3029454531512583e-05 erg / (s cm2)

                                       hi bound
GBM: total  5.868570457008436e-05 erg / (s cm2)
16:28:05  INFO        Bin 29 / 72 complete.
16:28:05  INFO      ==== Time bin 30 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   55.568801620238524      +/-  0.11029925565963787
 Total Likelihood Evaluations:        48755
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (5.18 -0.28 +0.12) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-2.23 -0.5 +0.34) x 10^-1
GBM.spectrum.main.Band.xp       (5.98 -0.21 +0.5) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.83 -0.4 +0.12

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval29       -47.805161
n7_interval29       -58.579923
n8_interval29       -59.427335
b1_interval29       201.220342
total                35.407923

Values of statistical measures:

        statistical measures
AIC               -62.732164
BIC               -46.095779
DIC              -114.110824
PDIC                3.907833
log(Z)             24.133224

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:28:33  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.223500856134077e-05 erg / (s cm2)

                                      low bound  \
GBM: total  7.876785639610553e-05 erg / (s cm2)

                                       hi bound
GBM: total  8.603787501327995e-05 erg / (s cm2)
16:28:33  INFO        Bin 30 / 72 complete.
16:28:33  INFO      ==== Time bin 31 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   195.72987210481651      +/-  0.11624274345091615
 Total Likelihood Evaluations:        50975
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (6.14 -0.22 +0.21) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha      (-2.4 +/- 0.4) x 10^-1
GBM.spectrum.main.Band.xp       (6.97 -0.35 +0.4) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.57 -0.15 +0.10

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval30       -11.555082
n7_interval30       -10.451701
n8_interval30       -15.454253
b1_interval30       210.789579
total               173.328543

Values of statistical measures:

        statistical measures
AIC              -338.573404
BIC              -321.937020
DIC              -395.320073
PDIC                4.073572
log(Z)             85.004403

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:29:03  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  0.0001378679225090803 erg / (s cm2)

                                       low bound  \
GBM: total  0.00013229920913595725 erg / (s cm2)

                                        hi bound
GBM: total  0.00014331324097281543 erg / (s cm2)
16:29:03  INFO        Bin 31 / 72 complete.
16:29:03  INFO      ==== Time bin 32 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -341.23070564641461      +/-  0.11790282920054501
 Total Likelihood Evaluations:        48486
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                   result             unit
parameter
GBM.spectrum.main.Band.K       (6.09 -0.18 +0.22) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-3.47 -0.31 +0.35) x 10^-1
GBM.spectrum.main.Band.xp       (5.67 -0.28 +0.27) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.19 -0.05 +0.06

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval31      -127.955103
n7_interval31      -166.619142
n8_interval31      -135.649640
b1_interval31        72.372859
total              -357.851025

Values of statistical measures:

        statistical measures
AIC               723.785733
BIC               740.422118
DIC               674.870826
PDIC                3.947382
log(Z)           -148.194613

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:29:33  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  0.00011439340119099973 erg / (s cm2)

                                      low bound  \
GBM: total  0.0001109382949717019 erg / (s cm2)

                                        hi bound
GBM: total  0.00011783969027567495 erg / (s cm2)
16:29:33  INFO        Bin 32 / 72 complete.
16:29:33  INFO      ==== Time bin 33 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   431.41184901051537      +/-   9.8110524257303863E-002
 Total Likelihood Evaluations:        36208
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (4.13 -0.22 +0.29) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-4.5 -0.5 +0.6) x 10^-1
GBM.spectrum.main.Band.xp      (3.92 -0.25 +0.26) x 10^2              keV
GBM.spectrum.main.Band.beta             -3.22 -0.5 +0.29

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval32        34.366061
n7_interval32        47.943502
n8_interval32        42.878289
b1_interval32       289.762084
total               414.949936

Values of statistical measures:

        statistical measures
AIC              -821.816190
BIC              -805.179806
DIC              -864.367808
PDIC                3.538366
log(Z)            187.359785

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:29:57  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.7775130713647674e-05 erg / (s cm2)

                                      low bound  \
GBM: total  2.628454086840744e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.9689985502335943e-05 erg / (s cm2)
16:29:57  INFO        Bin 33 / 72 complete.
16:29:57  INFO      ==== Time bin 34 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -688.08075532827377      +/-  0.10644445697462061
 Total Likelihood Evaluations:        43268
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (3.03 -0.17 +0.16) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha      (-5.7 +/- 0.4) x 10^-1
GBM.spectrum.main.Band.xp      (3.23 -0.16 +0.23) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.51 -0.25 +0.10

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval33      -219.719592
n7_interval33      -240.530330
n8_interval33      -232.680658
b1_interval33        -5.786962
total              -698.717542

Values of statistical measures:

        statistical measures
AIC              1405.518767
BIC              1422.155151
DIC              1369.464393
PDIC                3.907890
log(Z)           -298.829675

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:30:24  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.8876304422929546e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.769678504160672e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.0143896567536335e-05 erg / (s cm2)
16:30:24  INFO        Bin 34 / 72 complete.
16:30:24  INFO      ==== Time bin 35 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -729.10677243400698      +/-  0.10194832731119964
 Total Likelihood Evaluations:        41578
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.82 -0.23 +0.17) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-7.6 -0.8 +0.5) x 10^-1
GBM.spectrum.main.Band.xp       (2.17 -0.16 +0.4) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.22 -0.29 +0.06

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval34      -231.310260
n7_interval34      -244.717166
n8_interval34      -230.903206
b1_interval34       -31.087619
total              -738.018250

Values of statistical measures:

        statistical measures
AIC              1484.120183
BIC              1500.756568
DIC              1451.413168
PDIC                3.304444
log(Z)           -316.647048

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:30:51  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.596683494220064e-06 erg / (s cm2)

                                      low bound  \
GBM: total  7.708171405956296e-06 erg / (s cm2)

                                       hi bound
GBM: total  9.451424384391095e-06 erg / (s cm2)
16:30:51  INFO        Bin 35 / 72 complete.
16:30:51  INFO      ==== Time bin 36 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -649.62438050389062      +/-   9.7511510082401109E-002
 Total Likelihood Evaluations:        32977
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.29 -0.16 +0.13) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-8.3 -0.8 +0.7) x 10^-1
GBM.spectrum.main.Band.xp       (2.27 -0.20 +0.4) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.43 -0.6 +0.15

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval35      -214.773257
n7_interval35      -220.477110
n8_interval35      -201.535938
b1_interval35       -20.845583
total              -657.631888

Values of statistical measures:

        statistical measures
AIC              1323.347458
BIC              1339.983842
DIC              1293.383561
PDIC                3.187753
log(Z)           -282.128284

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:31:17  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.629874081876177e-06 erg / (s cm2)

                                      low bound  \
GBM: total  4.972859690020525e-06 erg / (s cm2)

                                       hi bound
GBM: total  6.356210325692263e-06 erg / (s cm2)
16:31:17  INFO        Bin 36 / 72 complete.
16:31:17  INFO      ==== Time bin 37 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -443.13165377623881      +/-   9.8789468174197093E-002
 Total Likelihood Evaluations:        37522
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.77 -0.09 +0.08) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-6.86 -0.5 +0.31) x 10^-1
GBM.spectrum.main.Band.xp       (4.82 -0.28 +0.5) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.68 -0.5 +0.20

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval36      -165.442884
n7_interval36      -162.852797
n8_interval36      -174.722127
b1_interval36        48.573238
total              -454.444570

Values of statistical measures:

        statistical measures
AIC               916.972822
BIC               933.609207
DIC               882.272001
PDIC                3.729311
log(Z)           -192.449632

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:31:41  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.7139788576228808e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.5853994813273454e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.866604052340861e-05 erg / (s cm2)
16:31:41  INFO        Bin 37 / 72 complete.
16:31:41  INFO      ==== Time bin 38 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -521.82917121976550      +/-  0.10609230935732253
 Total Likelihood Evaluations:        42135
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (2.51 -0.09 +0.10) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-5.73 -0.34 +0.4) x 10^-1
GBM.spectrum.main.Band.xp       (5.49 -0.31 +0.4) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.71 -0.30 +0.16

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval37      -183.239103
n7_interval37      -197.904038
n8_interval37      -194.066323
b1_interval37        40.159813
total              -535.049651

Values of statistical measures:

        statistical measures
AIC              1078.182985
BIC              1094.819369
DIC              1038.458194
PDIC                3.912768
log(Z)           -226.627530

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:32:09  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  3.0324064653801335e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.8689986712062597e-05 erg / (s cm2)

                                        hi bound
GBM: total  3.1988250795945974e-05 erg / (s cm2)
16:32:09  INFO        Bin 38 / 72 complete.
16:32:09  INFO      ==== Time bin 39 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -782.94545739396312      +/-  0.11414500088776967
 Total Likelihood Evaluations:        51540
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                   result             unit
parameter
GBM.spectrum.main.Band.K          (3.10 +/- 0.07) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-5.31 -0.22 +0.24) x 10^-1
GBM.spectrum.main.Band.xp       (6.66 -0.24 +0.28) x 10^2              keV
GBM.spectrum.main.Band.beta              -3.15 -0.4 +0.19

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval38      -254.009744
n7_interval38      -271.976328
n8_interval38      -246.178248
b1_interval38       -27.799374
total              -799.963695

Values of statistical measures:

        statistical measures
AIC              1608.011071
BIC              1624.647456
DIC              1559.965952
PDIC                3.898448
log(Z)           -340.028892

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:32:37  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.538381556185429e-05 erg / (s cm2)

                                      low bound  \
GBM: total  4.395751461724709e-05 erg / (s cm2)

                                        hi bound
GBM: total  4.6988340665534435e-05 erg / (s cm2)
16:32:37  INFO        Bin 39 / 72 complete.
16:32:37  INFO      ==== Time bin 40 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -249.65418816425145      +/-  0.11322491227956126
 Total Likelihood Evaluations:        53047
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                   result             unit
parameter
GBM.spectrum.main.Band.K       (3.76 -0.09 +0.10) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-4.62 -0.29 +0.28) x 10^-1
GBM.spectrum.main.Band.xp       (7.06 -0.26 +0.33) x 10^2              keV
GBM.spectrum.main.Band.beta              -3.31 -0.4 +0.22

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval39      -124.372841
n7_interval39      -136.877783
n8_interval39      -127.344181
b1_interval39       118.171396
total              -270.423409

Values of statistical measures:

        statistical measures
AIC               548.930499
BIC               565.566884
DIC               495.343637
PDIC                3.691020
log(Z)           -108.423436

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:33:05  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.141581966567913e-05 erg / (s cm2)

                                      low bound  \
GBM: total  5.926341460013164e-05 erg / (s cm2)

                                       hi bound
GBM: total  6.373902161408782e-05 erg / (s cm2)
16:33:05  INFO        Bin 40 / 72 complete.
16:33:05  INFO      ==== Time bin 41 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -615.58655829337511      +/-  0.11960699170264621
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        56261
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                   result             unit
parameter
GBM.spectrum.main.Band.K       (5.47 -0.12 +0.10) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-3.32 -0.25 +0.20) x 10^-1
GBM.spectrum.main.Band.xp       (6.45 -0.17 +0.22) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.83 -0.13 +0.10

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval40      -213.378536
n7_interval40      -223.598265
n8_interval40      -221.513656
b1_interval40        24.546670
total              -633.943787

Values of statistical measures:

        statistical measures
AIC              1275.971256
BIC              1292.607641
DIC              1223.946987
PDIC                4.000847
log(Z)           -267.345845

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:33:35  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  9.23353623204669e-05 erg / (s cm2)

                                      low bound  \
GBM: total  8.985191752757641e-05 erg / (s cm2)

                                       hi bound
GBM: total  9.492239024752224e-05 erg / (s cm2)
16:33:35  INFO        Bin 41 / 72 complete.
16:33:35  INFO      ==== Time bin 42 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   129.43198468239754      +/-  0.10651239166715987
 Total Likelihood Evaluations:        40257
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (5.10 -0.17 +0.20) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-4.23 -0.34 +0.4) x 10^-1
GBM.spectrum.main.Band.xp      (5.09 -0.23 +0.22) x 10^2              keV
GBM.spectrum.main.Band.beta            -3.44 -0.33 +0.31

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval41       -29.297721
n7_interval41       -45.592437
n8_interval41       -32.033034
b1_interval41       218.202661
total               111.279468

Values of statistical measures:

        statistical measures
AIC              -214.475254
BIC              -197.838870
DIC              -262.188295
PDIC                3.618420
log(Z)             56.211597

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:34:01  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  5.05131460330111e-05 erg / (s cm2)

                                      low bound  \
GBM: total  4.850005298531762e-05 erg / (s cm2)

                                      hi bound
GBM: total  5.27927665337688e-05 erg / (s cm2)
16:34:01  INFO        Bin 42 / 72 complete.
16:34:01  INFO      ==== Time bin 43 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -37.555308461674962      +/-  0.10386934403335249
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        39038
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (4.63 -0.23 +0.25) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-4.5 -0.4 +0.5) x 10^-1
GBM.spectrum.main.Band.xp         (3.58 +/- 0.18) x 10^2              keV
GBM.spectrum.main.Band.beta             -3.11 -0.5 +0.22

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval42       -67.403616
n7_interval42       -97.307980
n8_interval42       -74.350007
b1_interval42       186.427231
total               -52.634373

Values of statistical measures:

        statistical measures
AIC               113.352427
BIC               129.988812
DIC                71.276104
PDIC                3.613653
log(Z)            -16.310063

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:34:25  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.725217386940732e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.5974457933011083e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.878479217864428e-05 erg / (s cm2)
16:34:25  INFO        Bin 43 / 72 complete.
16:34:25  INFO      ==== Time bin 44 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1471.9292941345379      +/-  0.11427295458692974
 Total Likelihood Evaluations:        49834
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                   result             unit
parameter
GBM.spectrum.main.Band.K       (2.49 -0.06 +0.07) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-6.86 -0.19 +0.21) x 10^-1
GBM.spectrum.main.Band.xp          (4.13 +/- 0.15) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.58 -0.13 +0.09

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval43      -420.416501
n7_interval43      -435.171636
n8_interval43      -419.539455
b1_interval43      -204.980103
total             -1480.107695

Values of statistical measures:

        statistical measures
AIC              2968.299071
BIC              2984.935456
DIC              2933.267043
PDIC                3.895455
log(Z)           -639.250770

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:34:53  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.0899079632978672e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.0186306631651378e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.1676496666029854e-05 erg / (s cm2)
16:34:53  INFO        Bin 44 / 72 complete.
16:34:53  INFO      ==== Time bin 45 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -208.77056159548749      +/-  0.10381137635937172
 Total Likelihood Evaluations:        40423
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (3.33 -0.13 +0.11) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-5.50 +/- 0.34) x 10^-1
GBM.spectrum.main.Band.xp      (4.95 -0.23 +0.26) x 10^2              keV
GBM.spectrum.main.Band.beta             -3.19 -0.5 +0.27

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval44      -119.741983
n7_interval44      -118.297069
n8_interval44      -108.982450
b1_interval44       123.238578
total              -223.782924

Values of statistical measures:

        statistical measures
AIC               455.649529
BIC               472.285914
DIC               413.385188
PDIC                3.451368
log(Z)            -90.667903

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:35:18  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  3.1155753452885676e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.9787809325379515e-05 erg / (s cm2)

                                       hi bound
GBM: total  3.281497851944318e-05 erg / (s cm2)
16:35:18  INFO        Bin 45 / 72 complete.
16:35:18  INFO      ==== Time bin 46 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -569.58196936859179      +/-  0.10431998114187022
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        40658
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (2.75 -0.11 +0.12) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-6.40 -0.4 +0.32) x 10^-1
GBM.spectrum.main.Band.xp      (3.60 -0.16 +0.18) x 10^2              keV
GBM.spectrum.main.Band.beta             -3.31 -0.4 +0.28

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval45      -204.639793
n7_interval45      -213.448049
n8_interval45      -198.015343
b1_interval45        34.393103
total              -581.710081

Values of statistical measures:

        statistical measures
AIC              1171.503844
BIC              1188.140229
DIC              1133.614894
PDIC                3.605252
log(Z)           -247.366306

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:35:43  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.6048355217358016e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.5474504154202954e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.6836139322241003e-05 erg / (s cm2)
16:35:43  INFO        Bin 46 / 72 complete.
16:35:43  INFO      ==== Time bin 47 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -594.44489196919312      +/-  0.10228451659496578
 Total Likelihood Evaluations:        40906
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (2.32 -0.19 +0.10) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-5.8 -0.6 +0.4) x 10^-1
GBM.spectrum.main.Band.xp      (2.83 -0.11 +0.25) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.62 -0.4 +0.12

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval46      -200.549703
n7_interval46      -209.230649
n8_interval46      -199.756974
b1_interval46         4.718042
total              -604.819284

Values of statistical measures:

        statistical measures
AIC              1217.722251
BIC              1234.358635
DIC              1183.315385
PDIC                3.877512
log(Z)           -258.164136

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:36:10  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.1342600159670409e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.0525439440784452e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.2202517319863555e-05 erg / (s cm2)
16:36:10  INFO        Bin 47 / 72 complete.
16:36:10  INFO      ==== Time bin 48 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   417.72328916623945      +/-   8.6499770021695996E-002
 Total Likelihood Evaluations:        28728
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.48 -0.21 +0.27) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-8.0 -1.0 +1.1) x 10^-1
GBM.spectrum.main.Band.xp       (2.33 -0.30 +0.4) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.46 -0.7 +0.16

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval47        63.607328
n7_interval47        47.676265
n8_interval47        57.505163
b1_interval47       238.128222
total               406.916978

Values of statistical measures:

        statistical measures
AIC              -805.750275
BIC              -789.113890
DIC              -836.850205
PDIC                3.132586
log(Z)            181.414919

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:36:33  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  6.2919478785807835e-06 erg / (s cm2)

                                       low bound  \
GBM: total  5.4906566344909825e-06 erg / (s cm2)

                                        hi bound
GBM: total  7.4677960526980445e-06 erg / (s cm2)
16:36:33  INFO        Bin 48 / 72 complete.
16:36:33  INFO      ==== Time bin 49 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -490.65710324749227      +/-   9.9965922475773086E-002
 Total Likelihood Evaluations:        38460
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (2.08 -0.16 +0.10) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-6.55 -0.6 +0.34) x 10^-1
GBM.spectrum.main.Band.xp      (2.97 -0.12 +0.28) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.77 -0.6 +0.12

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval48      -180.620859
n7_interval48      -177.523875
n8_interval48      -178.587062
b1_interval48        35.769919
total              -500.961877

Values of statistical measures:

        statistical measures
AIC              1010.007437
BIC              1026.643822
DIC               976.291042
PDIC                3.639369
log(Z)           -213.089672

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:36:58  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.0273140304017376e-05 erg / (s cm2)

                                      low bound  \
GBM: total  9.624282742532735e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.1067781521054946e-05 erg / (s cm2)
16:36:58  INFO        Bin 49 / 72 complete.
16:36:58  INFO      ==== Time bin 50 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -46.790790081422742      +/-  0.10018227583319628
 Total Likelihood Evaluations:        36365
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (2.47 -0.13 +0.10) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-5.5 -0.5 +0.4) x 10^-1
GBM.spectrum.main.Band.xp       (5.27 -0.29 +0.5) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.91 -0.5 +0.24

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval49       -70.500413
n7_interval49       -82.558491
n8_interval49       -71.486678
b1_interval49       163.329046
total               -61.216536

Values of statistical measures:

        statistical measures
AIC               130.516754
BIC               147.153138
DIC                90.706340
PDIC                3.731645
log(Z)            -20.320982

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:37:22  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.695965317851143e-05 erg / (s cm2)

                                      low bound  \
GBM: total  2.523361567069683e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.891623528987818e-05 erg / (s cm2)
16:37:22  INFO        Bin 50 / 72 complete.
16:37:22  INFO      ==== Time bin 51 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=   174.00924239111859      +/-  0.10643653715456491
 Total Likelihood Evaluations:        50450
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (3.33 -0.12 +0.13) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha      (-4.6 +/- 0.4) x 10^-1
GBM.spectrum.main.Band.xp           (7.0 +/- 0.4) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.90 -0.5 +0.15

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval50       -14.668784
n7_interval50       -35.324148
n8_interval50       -23.895832
b1_interval50       227.427366
total               153.538601

Values of statistical measures:

        statistical measures
AIC              -298.993520
BIC              -282.357135
DIC              -349.933475
PDIC                3.683916
log(Z)             75.571254

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:37:49  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.658305065312817e-05 erg / (s cm2)

                                      low bound  \
GBM: total  5.368260798136159e-05 erg / (s cm2)

                                       hi bound
GBM: total  5.973401109187121e-05 erg / (s cm2)
16:37:49  INFO        Bin 51 / 72 complete.
16:37:49  INFO      ==== Time bin 52 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -111.31685500176602      +/-  0.10316549395637474
 Total Likelihood Evaluations:        39459
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (3.74 -0.18 +0.28) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-3.9 -0.5 +0.6) x 10^-1
GBM.spectrum.main.Band.xp      (3.46 -0.21 +0.18) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.89 -0.4 +0.19

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval51       -85.878425
n7_interval51       -92.794503
n8_interval51       -92.156457
b1_interval51       145.236096
total              -125.593289

Values of statistical measures:

        statistical measures
AIC               259.270260
BIC               275.906645
DIC               218.950134
PDIC                3.893785
log(Z)            -48.344296

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:38:15  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.217130498299059e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.0885148604656545e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.3652331388721446e-05 erg / (s cm2)
16:38:15  INFO        Bin 52 / 72 complete.
16:38:15  INFO      ==== Time bin 53 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -596.25816836223521      +/-  0.10163829836797363
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        40850
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (2.43 -0.11 +0.13) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-6.30 -0.35 +0.4) x 10^-1
GBM.spectrum.main.Band.xp      (3.40 -0.16 +0.20) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.95 -0.6 +0.19

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval52      -206.753668
n7_interval52      -221.511626
n8_interval52      -194.171529
b1_interval52        14.995431
total              -607.441393

Values of statistical measures:

        statistical measures
AIC              1222.966467
BIC              1239.602852
DIC              1187.532015
PDIC                3.691491
log(Z)           -258.951632

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:38:39  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.3718308446564805e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.3003350914640173e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.4769232299991838e-05 erg / (s cm2)
16:38:39  INFO        Bin 53 / 72 complete.
16:38:39  INFO      ==== Time bin 54 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -534.52020284462253      +/-  0.10116190068831035
 Total Likelihood Evaluations:        39588
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (2.29 -0.21 +0.16) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-6.4 -0.6 +0.5) x 10^-1
GBM.spectrum.main.Band.xp      (2.44 -0.13 +0.25) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.53 -0.5 +0.11

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval53      -171.807396
n7_interval53      -192.602330
n8_interval53      -192.730386
b1_interval53        12.377312
total              -544.762800

Values of statistical measures:

        statistical measures
AIC              1097.609282
BIC              1114.245667
DIC              1063.635666
PDIC                3.626350
log(Z)           -232.139175

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:39:06  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  9.59728699491729e-06 erg / (s cm2)

                                      low bound  \
GBM: total  8.747415232857914e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.0533998827013687e-05 erg / (s cm2)
16:39:06  INFO        Bin 54 / 72 complete.
16:39:06  INFO      ==== Time bin 55 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -374.39456319281106      +/-   9.4773995655241500E-002
 Total Likelihood Evaluations:        36210
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.20 -0.16 +0.22) x 10^-1  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha    (-9.6 -0.8 +1.0) x 10^-1
GBM.spectrum.main.Band.xp      (1.59 -0.18 +0.26) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.35 -0.6 +0.12

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval54      -129.067056
n7_interval54      -151.168575
n8_interval54      -141.479771
b1_interval54        38.464534
total              -383.250869

Values of statistical measures:

        statistical measures
AIC               774.585420
BIC               791.221805
DIC               743.727341
PDIC                2.814138
log(Z)           -162.597493

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:39:32  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.003048470798307e-06 erg / (s cm2)

                                     low bound  \
GBM: total  3.45497425596546e-06 erg / (s cm2)

                                        hi bound
GBM: total  4.6555944072179844e-06 erg / (s cm2)
16:39:32  INFO        Bin 55 / 72 complete.
16:39:32  INFO      ==== Time bin 56 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1094.9713654362963      +/-   9.3578502942807715E-002
 Total Likelihood Evaluations:        34512
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K        (4.6 -0.7 +0.5) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha          -1.17 -0.10 +0.06
GBM.spectrum.main.Band.xp     (1.51 -0.13 +0.31) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.51 -0.8 +0.15

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval55      -321.544827
n7_interval55      -313.712915
n8_interval55      -304.728793
b1_interval55      -160.731517
total             -1100.718052

Values of statistical measures:

        statistical measures
AIC              2209.519786
BIC              2226.156170
DIC              2183.793228
PDIC                2.976219
log(Z)           -475.540022

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:39:56  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  1.53159558666939e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.3736805568452216e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.7897609001583154e-06 erg / (s cm2)
16:39:56  INFO        Bin 56 / 72 complete.
16:39:56  INFO      ==== Time bin 57 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1585.5242058614560      +/-   8.7977184232983965E-002
 Total Likelihood Evaluations:        33316
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K      (2.13 -0.5 +0.30) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha          -1.29 -0.14 +0.08
GBM.spectrum.main.Band.xp      (1.60 -0.21 +1.1) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.03 -1.0 +0.05

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval56      -420.029763
n7_interval56      -445.020902
n8_interval56      -432.148235
b1_interval56      -292.212134
total             -1589.411035

Values of statistical measures:

        statistical measures
AIC              3186.905753
BIC              3203.542138
DIC              3161.254871
PDIC               -1.206246
log(Z)           -688.584414

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:40:21  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.1184708381099674e-06 erg / (s cm2)

                                      low bound  \
GBM: total  9.047915998209805e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.4051328591350994e-06 erg / (s cm2)
16:40:21  INFO        Bin 57 / 72 complete.
16:40:21  INFO      ==== Time bin 58 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -1616.0840877480557      +/-   7.9931758678703849E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        26027
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.01 -0.21 +0.13) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha           -1.32 -0.15 +0.07
GBM.spectrum.main.Band.xp         (2.1 -0.4 +1.2) x 10^2              keV
GBM.spectrum.main.Band.beta               -2.9 -0.7 +0.5

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval57      -453.986201
n7_interval57      -434.494016
n8_interval57      -424.468876
b1_interval57      -305.582623
total             -1618.531716

Values of statistical measures:

        statistical measures
AIC              3245.147114
BIC              3261.783498
DIC              3227.496034
PDIC                2.424081
log(Z)           -701.856402

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:40:43  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.860903197473907e-07 erg / (s cm2)

                                       low bound  \
GBM: total  4.1397162733330955e-07 erg / (s cm2)

                                       hi bound
GBM: total  5.958540521246462e-07 erg / (s cm2)
16:40:43  INFO        Bin 58 / 72 complete.
16:40:43  INFO      ==== Time bin 59 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3169.4830735840201      +/-   8.4029319358302657E-002
 Total Likelihood Evaluations:        28166
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K      (4.17 -0.4 +0.35) x 10^-3  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha             -1.51 +/- 0.06
GBM.spectrum.main.Band.xp        (3.4 -0.7 +2.0) x 10^2              keV
GBM.spectrum.main.Band.beta          -1.922 -1.2 -0.021

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval58      -817.619718
n7_interval58      -823.276103
n8_interval58      -821.872385
b1_interval58      -706.135347
total             -3168.903553

Values of statistical measures:

        statistical measures
AIC              6345.890788
BIC              6362.527172
DIC              6332.124368
PDIC                2.498859
log(Z)          -1376.489009

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:41:05  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  3.588569802158942e-07 erg / (s cm2)

                                       low bound  \
GBM: total  2.9657048765007294e-07 erg / (s cm2)

                                        hi bound
GBM: total  4.5679117551720385e-07 erg / (s cm2)
16:41:05  INFO        Bin 59 / 72 complete.
16:41:05  INFO      ==== Time bin 60 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2655.0094320755106      +/-   6.7736471071865353E-002
 Total Likelihood Evaluations:        18488
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K      (1.21 -0.05 +0.5) x 10^-3  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha        -1.634 -0.017 +0.26
GBM.spectrum.main.Band.xp        (3.4 -1.7 +1.6) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.35 -1.0 +0.29

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval59      -698.987303
n7_interval59      -692.581700
n8_interval59      -693.857748
b1_interval59      -567.587177
total             -2653.013928

Values of statistical measures:

        statistical measures
AIC              5314.111537
BIC              5330.747922
DIC              5304.698075
PDIC                1.053662
log(Z)          -1153.055946

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:41:24  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.010526814224715e-07 erg / (s cm2)

                                      low bound  \
GBM: total  7.619211842472397e-08 erg / (s cm2)

                                        hi bound
GBM: total  1.3353088977004242e-07 erg / (s cm2)
16:41:24  INFO        Bin 60 / 72 complete.
16:41:24  INFO      ==== Time bin 61 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************

 MultiNest Warning!
 Parameter            3  of mode            1  is converging towards the edge of the prior.

 MultiNest Warning!
 Parameter            3  of mode            1  is converging towards the edge of the prior.

 MultiNest Warning!
 Parameter            3  of mode            1  is converging towards the edge of the prior.

 MultiNest Warning!
 Parameter            3  of mode            1  is converging towards the edge of the prior.
  analysing data from chains/fit-.txt
 ln(ev)=  -3775.8594016448237      +/-   6.1399139128901305E-002
 Total Likelihood Evaluations:        15001
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K      (1.06 +0.04 +1.9) x 10^-4  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha   (-8.33 -0.33 +8) x 10^-1
GBM.spectrum.main.Band.xp      (0.12 +0.09 +3.1) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.21 -1.2 +0.09

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval60      -973.674509
n7_interval60      -968.906914
n8_interval60      -970.609642
b1_interval60      -852.618800
total             -3765.809865

Values of statistical measures:

        statistical measures
AIC              7539.703412
BIC              7556.339797
DIC              7540.738146
PDIC               -3.263443
log(Z)          -1639.834903

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:41:45  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.4958348929356241e-09 erg / (s cm2)

                                      low bound  \
GBM: total  2.496839870716096e-10 erg / (s cm2)

                                       hi bound
GBM: total  8.334624356504793e-09 erg / (s cm2)
16:41:45  INFO        Bin 61 / 72 complete.
16:41:45  INFO      ==== Time bin 62 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1720.4074553815944      +/-   5.4766776278121786E-002
 Total Likelihood Evaluations:        13611
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                result             unit
parameter
GBM.spectrum.main.Band.K       (2.0 -0.5 +0.8) x 10^-3  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-8.1 -2.8 +3.2) x 10^-1
GBM.spectrum.main.Band.xp         (4.1 +/- 1.5) x 10^2              keV
GBM.spectrum.main.Band.beta           -2.49 -1.0 +0.35

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval61      -454.404745
n7_interval61      -475.003992
n8_interval61      -457.480439
b1_interval61      -332.933523
total             -1719.822699

Values of statistical measures:

        statistical measures
AIC              3447.729079
BIC              3464.365464
DIC              3441.297385
PDIC                3.300251
log(Z)           -747.163464

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:42:00  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.6053039717212528e-07 erg / (s cm2)

                                       low bound  \
GBM: total  1.0601779335646117e-07 erg / (s cm2)

                                        hi bound
GBM: total  2.3326483822391248e-07 erg / (s cm2)
16:42:00  INFO        Bin 62 / 72 complete.
16:42:00  INFO      ==== Time bin 63 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -2689.4214098562843      +/-   8.5491645317174042E-002
 Total Likelihood Evaluations:        27921
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K       (9.06 -1.4 +0.29) x 10^-3  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha  (-7.74 -1.4 +0.29) x 10^-1
GBM.spectrum.main.Band.xp       (3.89 -0.12 +1.6) x 10^2              keV
GBM.spectrum.main.Band.beta           -2.057 -1.1 +0.027

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval62      -700.480955
n7_interval62      -709.842198
n8_interval62      -701.422396
b1_interval62      -578.332888
total             -2690.078437

Values of statistical measures:

        statistical measures
AIC              5388.240557
BIC              5404.876941
DIC              5372.429010
PDIC                2.763284
log(Z)          -1168.000878

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:42:22  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.414680902334625e-07 erg / (s cm2)

                                      low bound  \
GBM: total  7.041535263534203e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.0533469282925054e-06 erg / (s cm2)
16:42:22  INFO        Bin 63 / 72 complete.
16:42:22  INFO      ==== Time bin 64 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2378.0535230042015      +/-   8.7520697797052682E-002
 Total Likelihood Evaluations:        31143
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.20 -0.08 +0.09) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha              -1.00 +/- 0.06
GBM.spectrum.main.Band.xp         (4.4 -0.5 +0.7) x 10^2              keV
GBM.spectrum.main.Band.beta               -2.8 -0.7 +0.4

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval63      -622.982288
n7_interval63      -628.270681
n8_interval63      -631.993619
b1_interval63      -496.436353
total             -2379.682941

Values of statistical measures:

        statistical measures
AIC              4767.449564
BIC              4784.085949
DIC              4750.205952
PDIC                3.443740
log(Z)          -1032.775523

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:42:44  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  9.67885151127304e-07 erg / (s cm2)

                                      low bound  \
GBM: total  8.665543565314018e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.1067895861883762e-06 erg / (s cm2)
16:42:44  INFO        Bin 64 / 72 complete.
16:42:44  INFO      ==== Time bin 65 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3072.2084001908515      +/-  0.10241415335466234
 Total Likelihood Evaluations:        38847
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (2.35 -0.13 +0.05) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha         -1.109 -0.04 +0.018
GBM.spectrum.main.Band.xp       (3.62 -0.14 +0.6) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.34 -0.8 +0.04

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval64      -800.450856
n7_interval64      -804.159132
n8_interval64      -801.512631
b1_interval64      -666.295908
total             -3072.418527

Values of statistical measures:

        statistical measures
AIC              6152.920736
BIC              6169.557121
DIC              6133.292148
PDIC                3.239158
log(Z)          -1334.243155

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:43:10  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.712184098054801e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.5604990533640592e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.9096810697167004e-06 erg / (s cm2)
16:43:10  INFO        Bin 65 / 72 complete.
16:43:10  INFO      ==== Time bin 66 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -2159.2671131643247      +/-   9.1895965358028478E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        32537
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.99 -0.28 +0.10) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha         -1.123 -0.09 +0.035
GBM.spectrum.main.Band.xp       (2.51 -0.18 +0.9) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.12 -0.8 +0.10

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval65      -567.324084
n7_interval65      -575.091524
n8_interval65      -569.223019
b1_interval65      -449.093954
total             -2160.732581

Values of statistical measures:

        statistical measures
AIC              4329.548843
BIC              4346.185228
DIC              4310.493713
PDIC                2.721634
log(Z)           -937.757792

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:43:35  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2852733135705244e-06 erg / (s cm2)

                                      low bound  \
GBM: total  1.060442858515171e-06 erg / (s cm2)

                                       hi bound
GBM: total  1.566321938216008e-06 erg / (s cm2)
16:43:35  INFO        Bin 66 / 72 complete.
16:43:35  INFO      ==== Time bin 67 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1740.4650205679568      +/-   9.4369576726341553E-002
 Total Likelihood Evaluations:        35342
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K      (3.27 -0.4 +0.21) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha          -1.09 -0.09 +0.04
GBM.spectrum.main.Band.xp      (2.53 -0.22 +0.8) x 10^2              keV
GBM.spectrum.main.Band.beta            -2.08 -0.6 +0.08

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval66      -467.828984
n7_interval66      -470.321404
n8_interval66      -470.394734
b1_interval66      -334.865514
total             -1743.410636

Values of statistical measures:

        statistical measures
AIC              3494.904954
BIC              3511.541339
DIC              3472.897223
PDIC                2.673885
log(Z)           -755.874354

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:44:01  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.2200325841656127e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.8122147392775695e-06 erg / (s cm2)

                                        hi bound
GBM: total  2.6103539271428524e-06 erg / (s cm2)
16:44:01  INFO        Bin 67 / 72 complete.
16:44:01  INFO      ==== Time bin 68 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -2164.5700128190697      +/-   9.3358212293147530E-002
 Total Likelihood Evaluations:        33468
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                result             unit
parameter
GBM.spectrum.main.Band.K       (1.94 +/- 0.14) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha         -1.27 -0.05 +0.04
GBM.spectrum.main.Band.xp     (2.78 -0.30 +0.5) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.8 -0.7 +0.4

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval67      -564.769749
n7_interval67      -583.927260
n8_interval67      -578.386773
b1_interval67      -439.692212
total             -2166.775994

Values of statistical measures:

        statistical measures
AIC              4341.635671
BIC              4358.272055
DIC              4321.644846
PDIC                3.304489
log(Z)           -940.060812

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:44:24  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.092653643658995e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.0055014507721706e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.2364874932573299e-06 erg / (s cm2)
16:44:24  INFO        Bin 68 / 72 complete.
16:44:24  INFO      ==== Time bin 69 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -2066.7303000862034      +/-   8.5761574581786404E-002
 Total Likelihood Evaluations:        28924
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                  result             unit
parameter
GBM.spectrum.main.Band.K      (1.20 -0.12 +0.09) x 10^-2  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha           -1.35 -0.07 +0.05
GBM.spectrum.main.Band.xp         (3.3 -0.5 +1.2) x 10^2              keV
GBM.spectrum.main.Band.beta             -2.30 -1.1 +0.12

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval68      -536.586002
n7_interval68      -561.781446
n8_interval68      -546.779013
b1_interval68      -423.494044
total             -2068.640505

Values of statistical measures:

        statistical measures
AIC              4145.364692
BIC              4162.001077
DIC              4127.735371
PDIC                2.986221
log(Z)           -897.569565

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:44:46  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.487732447750802e-07 erg / (s cm2)

                                      low bound  \
GBM: total  7.451541987365606e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.0225971192419882e-06 erg / (s cm2)
16:44:46  INFO        Bin 69 / 72 complete.
16:44:46  INFO      ==== Time bin 70 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2241.9508563970026      +/-   8.2361761693862320E-002
 Total Likelihood Evaluations:        27539
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                               result             unit
parameter
GBM.spectrum.main.Band.K      (7.5 -1.1 +1.2) x 10^-3  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha           -1.42 +/- 0.09
GBM.spectrum.main.Band.xp      (2.5 -0.6 +1.6) x 10^2              keV
GBM.spectrum.main.Band.beta          -2.21 -1.2 +0.17

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval69      -588.065673
n7_interval69      -600.220459
n8_interval69      -576.074654
b1_interval69      -478.802383
total             -2243.163168

Values of statistical measures:

        statistical measures
AIC              4494.410018
BIC              4511.046403
DIC              4475.687364
PDIC               -0.016316
log(Z)           -973.666886

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:45:08  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.907616304534427e-07 erg / (s cm2)

                                       low bound  \
GBM: total  4.1084869023732107e-07 erg / (s cm2)

                                       hi bound
GBM: total  6.253131488256313e-07 erg / (s cm2)
16:45:08  INFO        Bin 70 / 72 complete.
16:45:08  INFO      ==== Time bin 71 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3434.6004490295086      +/-   8.1666751101024171E-002
 Total Likelihood Evaluations:        26729
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                              result             unit
parameter
GBM.spectrum.main.Band.K       (3.7 +/- 0.6) x 10^-3  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha          -1.41 +/- 0.10
GBM.spectrum.main.Band.xp     (2.2 -0.5 +1.4) x 10^2              keV
GBM.spectrum.main.Band.beta           -2.5 -0.9 +0.4

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval70      -890.624341
n7_interval70      -887.884187
n8_interval70      -869.103121
b1_interval70      -785.446844
total             -3433.058493

Values of statistical measures:

        statistical measures
AIC              6874.200669
BIC              6890.837054
DIC              6860.120539
PDIC                0.381616
log(Z)          -1491.628023

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:45:30  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.1932361053637512e-07 erg / (s cm2)

                                       low bound  \
GBM: total  1.8389399765220466e-07 erg / (s cm2)

                                       hi bound
GBM: total  2.776417815500093e-07 erg / (s cm2)
16:45:30  INFO        Bin 71 / 72 complete.
16:45:30  INFO      ==== Time bin 72 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -3026.9556020279902      +/-   6.9179307243322510E-002
 Total Likelihood Evaluations:        18025
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

                                                 result             unit
parameter
GBM.spectrum.main.Band.K      (1.07 -0.08 +0.4) x 10^-3  1 / (keV s cm2)
GBM.spectrum.main.Band.alpha        -1.606 -0.031 +0.25
GBM.spectrum.main.Band.xp        (3.4 -1.7 +1.5) x 10^2              keV
GBM.spectrum.main.Band.beta              -2.5 -0.9 +0.4

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval71      -766.460577
n7_interval71      -776.342985
n8_interval71      -769.540920
b1_interval71      -711.660105
total             -3024.004587

Values of statistical measures:

        statistical measures
AIC              6056.092856
BIC              6072.729241
DIC              6048.289185
PDIC                1.566190
log(Z)          -1314.590115

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:45:48  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.513754582024187e-08 erg / (s cm2)

                                     low bound  \
GBM: total  6.53431328118269e-08 erg / (s cm2)

                                       hi bound
GBM: total  1.105863262156968e-07 erg / (s cm2)
16:45:48  INFO        Bin 72 / 72 complete.

All 72 bins fitted successfully.

In [14]:
    ## Cell 11 — Save Results to CSV

In [15]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    fit_array = np.array(fit_rows)
    band_fit_param = Table(fit_array, names=PARAM_NAMES)

    # ── Attach bin edges as extra columns ────────────────────────────────
    band_fit_param['t_start'] = bb_starts
    band_fit_param['t_stop']  = bb_stops
    band_fit_param['dt']      = bb_stops - bb_starts

    csv_path = os.path.join(MODEL_PATHS['root'], 'fit_params.csv')
    band_fit_param.write(csv_path, overwrite=True)

    print(f'Results saved to: {csv_path}')
    print(f'Shape: {fit_array.shape}  ({n_bins} bins x 16 parameters)')
    band_fit_param

Results saved to: gbm_pipeline_output/band/fit_params.csv
Shape: (72, 22)  (72 bins x 16 parameters)

## Cell 13 — Time-Resolved Spectral Fitting (Band+BB Model)

In [16]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    MODEL_PATHS = get_model_paths('bandbb')

    PARAM_NAMES = []
    for p in ['K_1', 'alpha_1', 'xp_1', 'beta_1', 'K_2', 'kT_2']:
        PARAM_NAMES.extend([p, f'{p}_n_err', f'{p}_p_err', f'{p}_avg_err'])
    PARAM_NAMES.extend(['flux', 'flux_low', 'flux_hi', 'DIC', 'PDIC', 'BIC'])

    fit_rows = []

    for i in range(n_bins):
        log.info('==== Time bin %d / %d ====', i + 1, n_bins)

        det_plugins = []
        for det in detectors:
            p = time_resolved_plugins[det][i]
            if det.startswith('b'):
                p.set_active_measurements(CONFIG['bgo_range'])
            else:
                ranges = [r.strip() for r in CONFIG['nai_range'].split(',')]
                p.set_active_measurements(*ranges)
            det_plugins.append(p)

        data_list = DataList(*det_plugins)
        model = build_bandbb_model(CONFIG['ra'], CONFIG['dec'], CONFIG['priors_bandbb'])

        bayes = BayesianAnalysis(model, data_list)
        bayes.set_sampler('multinest')
        bayes.sampler.setup(n_live_points=CONFIG['n_live_points'], sampling_efficiency=CONFIG['sampling_efficiency'], auto_clean=True)
        bayes.sample()

        fig_spec = plot_spectra(
            bayes.results,
            ene_min=1.0, ene_max=1e5, num_ene=200,
            contour_colors='white', contour_style_kwargs=dict(alpha=0.2),
            use_components=True, components_to_use=['total'],
            flux_unit='keV2/(cm2 s keV)',
        )
        ax = plt.gca()
        ax.set_xlabel('Energy (keV)', fontsize=16)
        ax.set_ylabel(r'$\nu\,F_\nu\;[\mathrm{keV\,cm^{-2}\,s^{-1}}]$', fontsize=16)
        ax.set_title(f"{CONFIG['trigger_name']}  bin {i+1}/{n_bins}  [{bb_starts[i]:.3f}, {bb_stops[i]:.3f}] s", fontsize=13)
        fig_spec.savefig(os.path.join(MODEL_PATHS['spectra'], f'bandbb_spec_bin{i+1:03d}.png'), dpi=120, bbox_inches='tight')
        plt.close('all')

        fig_corner = bayes.results.corner_plot()
        fig_corner.savefig(os.path.join(MODEL_PATHS['corners'], f'bandbb_corner_bin{i+1:03d}.png'), dpi=100, bbox_inches='tight')
        plt.close('all')

        flux_df = bayes.results.get_point_source_flux(10 * u.keV, 10 * u.MeV)
        log.info('  10 keV-10 MeV flux = %s', flux_df)
        f_val = flux_df['flux'].iloc[0].value
        f_low = flux_df['low bound'].iloc[0].value
        f_hi  = flux_df['hi bound'].iloc[0].value

        df  = bayes.results.get_data_frame('equal tail')
        df  = df.drop('unit', axis=1, errors='ignore')
        param_array = df.to_numpy().flatten()

        stat_df = bayes.results.get_statistic_measure_frame()
        dic_val = stat_df.loc['DIC'].iloc[0] if 'DIC' in stat_df.index else np.nan
        pdic_val = stat_df.loc['PDIC'].iloc[0] if 'PDIC' in stat_df.index else np.nan
        bic_val = stat_df.loc['BIC'].iloc[0] if 'BIC' in stat_df.index else np.nan

        full_row = np.append(param_array, [f_val, f_low, f_hi, dic_val, pdic_val, bic_val])
        fit_rows.append(full_row)
        log.info('  Bin %d / %d complete.', i + 1, n_bins)

    print(f'\nAll {n_bins} bins fitted successfully.')

16:45:48  INFO      ==== Time bin 1 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2474.0685592637583      +/-   4.2416501387059463E-002
 Total Likelihood Evaluations:        12791
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(0.1685 +0.0019 +2.1) x 10^-4,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.03 -0.23 +0.7,
GBM.spectrum.main.composite.xp_1,(2.6 -0.9 +2.8) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.7 +/- 0.7,
GBM.spectrum.main.composite.K_2,(0.0001 +0.0006 +3.4) x 10^-6,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.25 -0.8 +0.16) x 10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval0      -614.525164
n7_interval0      -619.331541
n8_interval0      -610.559063
b1_interval0      -530.219423
total            -2374.635192

Values of statistical measures:

        statistical measures
AIC              4761.446854
BIC              4786.350483
DIC              4855.040640
PDIC              -58.551093
log(Z)          -1074.474323

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:46:09  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  3.7009663078448138e-09 erg / (s cm2)

                                       low bound  \
GBM: total  1.0178603824503057e-09 erg / (s cm2)

                                       hi bound
GBM: total  1.774316428280771e-08 erg / (s cm2)
16:46:09  INFO        Bin 1 / 72 complete.
16:46:09  INFO      ==== Time bin 2 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2641.8002308841178      +/-   8.7115766369319989E-002
 Total Likelihood Evaluations:        39252
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(9.2 -1.4 +0.7) x 10^-3,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-8.1 -1.2 +0.7) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.39 -0.28 +1.0) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.17 -1.0 +0.08,
GBM.spectrum.main.composite.K_2,(0.0 +8 +1.7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8.3 -3.3 +6,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval1      -674.241079
n7_interval1      -667.580882
n8_interval1      -668.407274
b1_interval1      -549.672324
total            -2559.901560

Values of statistical measures:

        statistical measures
AIC              5131.979591
BIC              5156.883220
DIC              5235.412308
PDIC              -11.920515
log(Z)          -1147.319263

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:46:46  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.805124721445274e-07 erg / (s cm2)

                                      low bound  \
GBM: total  5.706516722505003e-07 erg / (s cm2)

                                       hi bound
GBM: total  8.533776809748144e-07 erg / (s cm2)
16:46:46  INFO        Bin 2 / 72 complete.
16:46:46  INFO      ==== Time bin 3 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -1743.6565260583416      +/-   9.1250126856406752E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        42917
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.5 -0.5 +0.4) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-6.5 -1.2 +1.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(2.52 -0.29 +1.0) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.04 -1.0 +0.04,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +3.4) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,6.1 -1.2 +10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval2      -448.268230
n7_interval2      -452.420627
n8_interval2      -443.537255
b1_interval2      -322.495405
total            -1666.721516

Values of statistical measures:

        statistical measures
AIC              3345.619503
BIC              3370.523132
DIC              3436.590723
PDIC              -16.621535
log(Z)           -757.260408

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:47:25  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.4492897594267073e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.1635720091480632e-06 erg / (s cm2)

                                       hi bound
GBM: total  1.812916718776906e-06 erg / (s cm2)
16:47:25  INFO        Bin 3 / 72 complete.
16:47:25  INFO      ==== Time bin 4 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2323.7359961671559      +/-   9.1680211229850081E-002
 Total Likelihood Evaluations:        46126
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.47 -0.14 +0.19) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-8.7 -0.5 +1.5) x 10^-1,
GBM.spectrum.main.composite.xp_1,(2.50 -0.21 +0.32) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.9 -0.6 +0.4,
GBM.spectrum.main.composite.K_2,(0.0 +1.3 +1.5) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8.1 -2.6 +6,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval3      -586.279478
n7_interval3      -592.216713
n8_interval3      -588.357316
b1_interval3      -477.467893
total            -2244.321400

Values of statistical measures:

        statistical measures
AIC              4500.819270
BIC              4525.722899
DIC              4605.302675
PDIC               -7.861207
log(Z)          -1009.185721

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:48:04  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.108194450480669e-07 erg / (s cm2)

                                      low bound  \
GBM: total  5.563587082918844e-07 erg / (s cm2)

                                       hi bound
GBM: total  7.036835153742976e-07 erg / (s cm2)
16:48:04  INFO        Bin 4 / 72 complete.
16:48:04  INFO      ==== Time bin 5 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -1620.8136606042149      +/-   9.2626982293229257E-002
 Total Likelihood Evaluations:        41242
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(3.28 -0.8 +0.24) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-7.2 -1.8 +0.5) x 10^-1,
GBM.spectrum.main.composite.xp_1,(1.95 -0.13 +0.7) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.10 -0.7 +0.09,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +4) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.32 -0.8 +0.16) x 10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval4      -418.144625
n7_interval4      -426.351489
n8_interval4      -423.686723
b1_interval4      -275.974447
total            -1544.157285

Values of statistical measures:

        statistical measures
AIC              3100.491040
BIC              3125.394669
DIC              3195.240920
PDIC              -11.873346
log(Z)           -703.910429

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:48:41  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.4480377118784977e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.1421775379148868e-06 erg / (s cm2)

                                       hi bound
GBM: total  1.771881886050193e-06 erg / (s cm2)
16:48:41  INFO        Bin 5 / 72 complete.
16:48:41  INFO      ==== Time bin 6 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1360.9854726107008      +/-   9.3607273057708565E-002
 Total Likelihood Evaluations:        40185
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(3.90 -0.26 +0.4) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-8.27 -0.34 +0.9) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.29 -0.4 +0.31) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.6346 -0.0033 +1.0,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00010 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.14 -0.6 +0.35) x 10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval5      -367.191711
n7_interval5      -357.693272
n8_interval5      -345.811086
b1_interval5      -215.315854
total            -1286.011923

Values of statistical measures:

        statistical measures
AIC              2584.200317
BIC              2609.103946
DIC              2676.534311
PDIC              -11.403226
log(Z)           -591.068481

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:49:19  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.159091421896687e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.9892717220907065e-06 erg / (s cm2)

                                        hi bound
GBM: total  2.4234126184322246e-06 erg / (s cm2)
16:49:19  INFO        Bin 6 / 72 complete.
16:49:19  INFO      ==== Time bin 7 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -676.35729117784626      +/-   9.2086783533171970E-002
 Total Likelihood Evaluations:        38090
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(7.3 -1.0 +0.8) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-5.6 -0.9 +1.0) x 10^-1,
GBM.spectrum.main.composite.xp_1,(2.70 -0.26 +0.4) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.53 -0.8 +0.21,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00010 +4) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval6      -179.785978
n7_interval6      -193.600725
n8_interval6      -193.632007
b1_interval6       -36.156646
total             -603.175356

Values of statistical measures:

        statistical measures
AIC              1218.527182
BIC              1243.430811
DIC              1309.380335
PDIC              -10.939912
log(Z)           -293.738239

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:49:54  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  3.3049596888430163e-06 erg / (s cm2)

                                      low bound  \
GBM: total  2.908289350760131e-06 erg / (s cm2)

                                       hi bound
GBM: total  3.929584603791387e-06 erg / (s cm2)
16:49:54  INFO        Bin 7 / 72 complete.
16:49:54  INFO      ==== Time bin 8 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1580.7929068923231      +/-  0.10300855076415986
 Total Likelihood Evaluations:        64723
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(5.3 -3.2 +0.7) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-6.7 -4 +0.7) x 10^-1,
GBM.spectrum.main.composite.xp_1,(1.65 -0.11 +2.1) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.10 -0.9 +0.04,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00031 +8) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.4 +1.1) x 10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval7      -410.406750
n7_interval7      -417.379719
n8_interval7      -409.015557
b1_interval7      -267.945223
total            -1504.747250

Values of statistical measures:

        statistical measures
AIC              3021.670971
BIC              3046.574600
DIC              2973.086073
PDIC             -155.957571
log(Z)           -686.529636

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:50:38  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.8595495071636714e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.5419272026037981e-06 erg / (s cm2)

                                       hi bound
GBM: total  2.208528854971253e-06 erg / (s cm2)
16:50:38  INFO        Bin 8 / 72 complete.
16:50:38  INFO      ==== Time bin 9 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -316.11233805127631      +/-   8.5361115458587766E-002
 Total Likelihood Evaluations:        33789
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(5.23 -0.7 +0.33) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-7.4 -1.2 +0.5) x 10^-1,
GBM.spectrum.main.composite.xp_1,(4.04 -0.32 +1.1) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.50 -0.8 +0.35,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00013 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.21 -0.7 +0.28) x 10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval8       -99.376668
n7_interval8      -104.805388
n8_interval8      -101.818836
b1_interval8        63.546892
total             -242.454000

Values of statistical measures:

        statistical measures
AIC               497.084470
BIC               521.988099
DIC               593.508327
PDIC               -8.686483
log(Z)           -137.285844

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:51:12  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  4.5049129481323445e-06 erg / (s cm2)

                                     low bound  \
GBM: total  3.83408147737382e-06 erg / (s cm2)

                                       hi bound
GBM: total  5.603693367282529e-06 erg / (s cm2)
16:51:12  INFO        Bin 9 / 72 complete.
16:51:12  INFO      ==== Time bin 10 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1345.5352877690432      +/-  0.10468864770463875
 Total Likelihood Evaluations:        50882
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.08 -0.08 +0.07) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-5.4 +/- 0.5) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.01 -0.19 +0.25) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.45 -0.27 +0.16,
GBM.spectrum.main.composite.K_2,(0.0 +8 +2.8) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval9      -358.585041
n7_interval9      -375.728081
n8_interval9      -347.033775
b1_interval9      -189.488776
total            -1270.835674

Values of statistical measures:

        statistical measures
AIC              2553.847818
BIC              2578.751448
DIC              2643.498207
PDIC              -10.442327
log(Z)           -584.358551

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:51:52  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.393994432715106e-06 erg / (s cm2)

                                      low bound  \
GBM: total  5.812276427086468e-06 erg / (s cm2)

                                        hi bound
GBM: total  6.9980183097844685e-06 erg / (s cm2)
16:51:52  INFO        Bin 10 / 72 complete.
16:51:52  INFO      ==== Time bin 11 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -1155.0586317064594      +/-   9.6410484157982479E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        44429
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(5.9 -0.6 +0.7) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-8.1 -0.7 +0.8) x 10^-1,
GBM.spectrum.main.composite.xp_1,(2.45 -0.25 +0.4) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.14 -0.4 +0.06,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00010 +3.4) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 +/- 5,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval10      -296.205309
n7_interval10      -307.326893
n8_interval10      -306.903048
b1_interval10      -168.974049
total             -1079.409299

Values of statistical measures:

        statistical measures
AIC              2170.995069
BIC              2195.898698
DIC              2261.709931
PDIC              -13.438208
log(Z)           -501.635590

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:52:30  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  3.333335909523553e-06 erg / (s cm2)

                                      low bound  \
GBM: total  2.852989444041384e-06 erg / (s cm2)

                                       hi bound
GBM: total  3.838765603249961e-06 erg / (s cm2)
16:52:30  INFO        Bin 11 / 72 complete.
16:52:30  INFO      ==== Time bin 12 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -413.60780674689130      +/-   9.3017259824229231E-002
 Total Likelihood Evaluations:        36496
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(8.4 -0.5 +0.7) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-6.9 -0.4 +0.8) x 10^-1,
GBM.spectrum.main.composite.xp_1,(4.29 -0.35 +0.5) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.64 -0.9 +0.10,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.21 -0.7 +0.24) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval11      -139.962427
n7_interval11      -135.162564
n8_interval11      -127.931000
b1_interval11        61.898390
total              -341.157602

Values of statistical measures:

        statistical measures
AIC               694.491674
BIC               719.395304
DIC               784.326398
PDIC              -11.297262
log(Z)           -179.627588

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:53:04  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.968817548729794e-06 erg / (s cm2)

                                      low bound  \
GBM: total  6.370852439714515e-06 erg / (s cm2)

                                      hi bound
GBM: total  7.78381911149853e-06 erg / (s cm2)
16:53:04  INFO        Bin 12 / 72 complete.
16:53:04  INFO      ==== Time bin 13 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1073.0815993345693      +/-  0.10754630843445290
 Total Likelihood Evaluations:        45744
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.113 -0.034 +0.031) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-5.94 -0.26 +0.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(5.40 -0.21 +0.27) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.34 -0.4 +0.29,
GBM.spectrum.main.composite.K_2,(0 +9 +4) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,10 +/- 5,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval12      -294.364558
n7_interval12      -296.441324
n8_interval12      -305.267384
b1_interval12      -105.943903
total             -1002.017168

Values of statistical measures:

        statistical measures
AIC              2016.210807
BIC              2041.114437
DIC              2095.208108
PDIC              -15.441618
log(Z)           -466.033417

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:53:43  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.1481225722805396e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.0995610698227852e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.2072855567970136e-05 erg / (s cm2)
16:53:43  INFO        Bin 13 / 72 complete.
16:53:43  INFO      ==== Time bin 14 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -871.09494367760681      +/-  0.10798735584635391
 Total Likelihood Evaluations:        54112
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.345 -0.05 +0.031) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-6.24 -0.27 +0.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(5.98 -0.24 +0.4) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.52 -0.28 +0.4,
GBM.spectrum.main.composite.K_2,(0 +9 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,7.2 -2.3 +8,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval13      -264.880092
n7_interval13      -252.016755
n8_interval13      -242.279244
b1_interval13       -44.192076
total              -803.368167

Values of statistical measures:

        statistical measures
AIC              1618.912804
BIC              1643.816433
DIC              1699.257714
PDIC               -8.531455
log(Z)           -378.311727

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:54:24  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.572180947004596e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.5081017485355435e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.6446583916372328e-05 erg / (s cm2)
16:54:24  INFO        Bin 14 / 72 complete.
16:54:24  INFO      ==== Time bin 15 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -954.34940143453025      +/-  0.10173678589180578
 Total Likelihood Evaluations:        45223
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.20 +/- 0.06) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-5.4 -0.5 +0.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(4.03 -0.19 +0.32) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.69 -0.6 +0.10,
GBM.spectrum.main.composite.K_2,(0.0 +9 +2.9) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,7.0 -1.9 +8,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval14      -253.415452
n7_interval14      -281.334458
n8_interval14      -266.690235
b1_interval14       -80.593956
total              -882.034101

Values of statistical measures:

        statistical measures
AIC              1776.244673
BIC              1801.148302
DIC              1863.087780
PDIC              -10.662288
log(Z)           -414.468679

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:55:02  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  9.170691620172046e-06 erg / (s cm2)

                                      low bound  \
GBM: total  8.521562904252304e-06 erg / (s cm2)

                                      hi bound
GBM: total  9.93685129719834e-06 erg / (s cm2)
16:55:02  INFO        Bin 15 / 72 complete.
16:55:02  INFO      ==== Time bin 16 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -149.17279147093896      +/-   9.8497729350838614E-002
 Total Likelihood Evaluations:        45576
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.66 -0.17 +0.05) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-4.6 -0.9 +0.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(4.65 -0.20 +0.8) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.40 -0.4 +0.14,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.5 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval15       -64.922992
n7_interval15       -84.798955
n8_interval15       -62.957684
b1_interval15       132.783208
total               -79.896423

Values of statistical measures:

        statistical measures
AIC               171.969318
BIC               196.872947
DIC               255.797167
PDIC              -10.838616
log(Z)            -64.784920

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:55:41  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.9124466496779755e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.7387280840849035e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.096364157681879e-05 erg / (s cm2)
16:55:41  INFO        Bin 16 / 72 complete.
16:55:41  INFO      ==== Time bin 17 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -847.94216143585186      +/-  0.11008607280982902
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        58037
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.119 -0.15 +0.035) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-6.781 +0.027 +1.5) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.88 -0.17 +0.5) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.89 -0.6 +0.24,
GBM.spectrum.main.composite.K_2,(0.0000 +0.0024 +4) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(0.6 +0.4 +1.2) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval16      -235.744647
n7_interval16      -252.818488
n8_interval16      -233.454422
b1_interval16       -54.905723
total              -776.923279

Values of statistical measures:

        statistical measures
AIC              1566.023029
BIC              1590.926658
DIC              1668.263567
PDIC                0.193536
log(Z)           -368.256602

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:56:26  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  7.805952584046297e-06 erg / (s cm2)

                                      low bound  \
GBM: total  7.299477006045665e-06 erg / (s cm2)

                                       hi bound
GBM: total  8.528323324903569e-06 erg / (s cm2)
16:56:26  INFO        Bin 17 / 72 complete.
16:56:26  INFO      ==== Time bin 18 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -261.90483983416362      +/-   9.8889551602072634E-002
 Total Likelihood Evaluations:        39858
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.585 -0.19 +0.025) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-4.22 -1.1 +0.21) x 10^-1,
GBM.spectrum.main.composite.xp_1,(4.31 -0.10 +0.8) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.66 -0.8 +0.12,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.22 -0.7 +0.28) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval17       -92.402208
n7_interval17      -100.050885
n8_interval17      -114.655460
b1_interval17       114.028172
total              -193.080382

Values of statistical measures:

        statistical measures
AIC               398.337234
BIC               423.240864
DIC               480.026068
PDIC              -12.125446
log(Z)           -113.743827

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:57:03  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.399956722911777e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.2919715734859453e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.538371931567683e-05 erg / (s cm2)
16:57:03  INFO        Bin 18 / 72 complete.
16:57:03  INFO      ==== Time bin 19 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1284.8614897647863      +/-  0.11603148990115457
 Total Likelihood Evaluations:        62622
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.99 +/- 0.04) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-4.68 -0.23 +0.20) x 10^-1,
GBM.spectrum.main.composite.xp_1,(5.82 -0.15 +0.20) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.41 -0.4 +0.18,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00010 +2.9) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,6.6 -1.7 +8,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval18      -361.444111
n7_interval18      -354.098870
n8_interval18      -362.193164
b1_interval18      -140.187319
total             -1217.923465

Values of statistical measures:

        statistical measures
AIC              2448.023400
BIC              2472.927029
DIC              2521.450145
PDIC              -11.044453
log(Z)           -558.008255

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:57:48  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.370368092444178e-05 erg / (s cm2)

                                      low bound  \
GBM: total  2.309133679883592e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.443082499673323e-05 erg / (s cm2)
16:57:48  INFO        Bin 19 / 72 complete.
16:57:48  INFO      ==== Time bin 20 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -508.34504027090037      +/-  0.10216130694495175
 Total Likelihood Evaluations:        53726
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.02 -0.12 +0.11) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-5.1 +/- 0.5) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.51 +/- 0.21) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.94 -0.6 +0.20,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +9) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.2 -0.7 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval19      -154.962454
n7_interval19      -173.360030
n8_interval19      -165.818102
b1_interval19        55.671312
total              -438.469274

Values of statistical measures:

        statistical measures
AIC               889.115018
BIC               914.018648
DIC               973.338276
PDIC              -10.768308
log(Z)           -220.771446

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:58:32  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.1735526492517147e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.1040813469770529e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.2762167949447012e-05 erg / (s cm2)
16:58:32  INFO        Bin 20 / 72 complete.
16:58:32  INFO      ==== Time bin 21 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -701.03347754306401      +/-  0.11157217099841776
 Total Likelihood Evaluations:        52081
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.43 +/- 0.07) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-4.37 -0.35 +0.26) x 10^-1,
GBM.spectrum.main.composite.xp_1,(5.94 -0.28 +0.20) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.24 -0.4 +0.24,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00013 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval20      -214.379349
n7_interval20      -215.642789
n8_interval20      -219.492888
b1_interval20        14.821811
total              -634.693214

Values of statistical measures:

        statistical measures
AIC              1281.562898
BIC              1306.466528
DIC              1358.389456
PDIC               -9.293232
log(Z)           -304.454971

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:59:13  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  3.052238266770779e-05 erg / (s cm2)

                                      low bound  \
GBM: total  2.944959230642571e-05 erg / (s cm2)

                                       hi bound
GBM: total  3.177906042539608e-05 erg / (s cm2)
16:59:13  INFO        Bin 21 / 72 complete.
16:59:13  INFO      ==== Time bin 22 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=   2.4219350061856848      +/-  0.10943113070681305
 Total Likelihood Evaluations:        53748
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(3.28 +/- 0.12) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-3.21 -0.30 +0.6) x 10^-1,
GBM.spectrum.main.composite.xp_1,(6.47 -0.5 +0.24) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.75 +/- 0.20,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00010 +7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8.2 -3.4 +7,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval21       -43.471632
n7_interval21       -42.871651
n8_interval21       -36.570074
b1_interval21       188.043964
total                65.130608

Values of statistical measures:

        statistical measures
AIC              -118.084745
BIC               -93.181116
DIC               -46.830168
PDIC              -10.155542
log(Z)              1.051833

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

16:59:55  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.662625704269974e-05 erg / (s cm2)

                                       low bound  \
GBM: total  5.3744665091746806e-05 erg / (s cm2)

                                       hi bound
GBM: total  5.969291426944852e-05 erg / (s cm2)
16:59:55  INFO        Bin 22 / 72 complete.
16:59:55  INFO      ==== Time bin 23 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -777.13864432147557      +/-  0.12071720559945050
 Total Likelihood Evaluations:        62596
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(4.435 -0.12 +0.033) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-2.75 -0.4 +0.04) x 10^-1,
GBM.spectrum.main.composite.xp_1,(6.504 -0.008 +0.34) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.33 -0.4 +0.11,
GBM.spectrum.main.composite.K_2,(0.0 +9 +3.5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,7.5 -2.7 +7,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval22      -239.112879
n7_interval22      -246.758090
n8_interval22      -232.735889
b1_interval22         2.741478
total              -715.865380

Values of statistical measures:

        statistical measures
AIC              1443.907231
BIC              1468.810860
DIC              1506.411863
PDIC              -12.294446
log(Z)           -337.507025

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:00:38  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  7.192090998525398e-05 erg / (s cm2)

                                      low bound  \
GBM: total  7.017826997671971e-05 erg / (s cm2)

                                       hi bound
GBM: total  7.369312203878466e-05 erg / (s cm2)
17:00:38  INFO        Bin 23 / 72 complete.
17:00:38  INFO      ==== Time bin 24 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   255.16422072125954      +/-  0.10032318514916617
 Total Likelihood Evaluations:        43721

 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(4.05 -0.28 +0.20) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-3.61 -0.8 +0.30) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.92 -0.16 +0.34) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.06 -0.4 +0.33,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00010 +9) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,10 +/- 5,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval23        33.264205
n7_interval23        10.962025
n8_interval23        34.641777
b1_interval23       241.342777
total               320.210784

Values of statistical measures:

        statistical measures
AIC              -628.245098
BIC              -603.341469
DIC              -552.177399
PDIC              -11.865315
log(Z)            110.816413

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:01:13  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.910399355614073e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.7389870630747934e-05 erg / (s cm2)

                                       hi bound
GBM: total  3.140778033508343e-05 erg / (s cm2)
17:01:13  INFO        Bin 24 / 72 complete.
17:01:13  INFO      ==== Time bin 25 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   26.309967014805178      +/-  0.10293297175413546
 Total Likelihood Evaluations:        44881
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(4.12 -0.5 +0.20) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-2.9 -1.0 +0.5) x 10^-1,
GBM.spectrum.main.composite.xp_1,(2.415 -0.033 +0.31) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.482 -0.6 -0.034,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00012 +8) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 -0.5 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval24       -34.900305
n7_interval24       -32.544634
n8_interval24       -30.081489
b1_interval24       189.254886
total                91.728458

Values of statistical measures:

        statistical measures
AIC              -171.280446
BIC              -146.376816
DIC               -93.867924
PDIC              -10.207208
log(Z)             11.426273

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:01:52  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.4880019595867445e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.3638251111672802e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.6416001913207016e-05 erg / (s cm2)
17:01:52  INFO        Bin 25 / 72 complete.
17:01:52  INFO      ==== Time bin 26 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   88.176533035026097      +/-   9.4751565659595680E-002
 Total Likelihood Evaluations:        38360
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.08 -0.24 +0.23) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-6.9 -0.7 +0.9) x 10^-1,
GBM.spectrum.main.composite.xp_1,(2.50 -0.19 +0.35) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.462 -0.7 +0.027,
GBM.spectrum.main.composite.K_2,(0.0 +1.4 +1.1) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.13 -0.6 +0.34) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval25       -11.559571
n7_interval25       -26.048465
n8_interval25        -5.330351
b1_interval25       201.705862
total               158.767475

Values of statistical measures:

        statistical measures
AIC              -305.358479
BIC              -280.454850
DIC              -215.907590
PDIC               -9.094573
log(Z)             38.294582

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:02:32  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.964074176409485e-06 erg / (s cm2)

                                      low bound  \
GBM: total  8.118813151080227e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.0028970523536678e-05 erg / (s cm2)
17:02:32  INFO        Bin 26 / 72 complete.
17:02:32  INFO      ==== Time bin 27 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -414.24838707405746      +/-   9.5524498398941282E-002
 Total Likelihood Evaluations:        44846
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.47 -0.22 +0.07) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-7.7 -0.9 +0.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(2.18 -0.14 +0.28) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.84 -0.7 +0.22,
GBM.spectrum.main.composite.K_2,(0.0 +1.3 +1.5) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,10 +/- 5,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval26      -111.360968
n7_interval26      -146.553709
n8_interval26      -141.913413
b1_interval26        57.252302
total              -342.575787

Values of statistical measures:

        statistical measures
AIC               697.328046
BIC               722.231675
DIC               789.400893
PDIC               -8.126754
log(Z)           -179.905789

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:03:10  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.877316185180971e-06 erg / (s cm2)

                                      low bound  \
GBM: total  4.528807599905042e-06 erg / (s cm2)

                                        hi bound
GBM: total  5.4032513951810876e-06 erg / (s cm2)
17:03:10  INFO        Bin 27 / 72 complete.
17:03:10  INFO      ==== Time bin 28 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -386.42664106764607      +/-   9.8041890641800203E-002
 Total Likelihood Evaluations:        42161
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.69 -0.14 +0.07) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-5.91 -0.7 +0.35) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.73 -0.19 +0.4) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.60 -0.5 +0.20,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval27      -124.587506
n7_interval27      -134.606010
n8_interval27      -123.063055
b1_interval27        67.204064
total              -315.052507

Values of statistical measures:

        statistical measures
AIC               642.281485
BIC               667.185114
DIC               726.311671
PDIC              -14.376389
log(Z)           -167.822958

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:03:49  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2184564860822398e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.100609533549305e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.3668605659954373e-05 erg / (s cm2)
17:03:49  INFO        Bin 28 / 72 complete.
17:03:49  INFO      ==== Time bin 29 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -81.232038349655525      +/-  0.11212127346215470
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        56592
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.72 -0.12 +0.07) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-4.78 -0.4 +0.34) x 10^-1,
GBM.spectrum.main.composite.xp_1,(7.37 -0.34 +0.7) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.53 -0.26 +0.10,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.25 -0.8 +0.21) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval28       -61.673157
n7_interval28       -51.989227
n8_interval28       -62.929010
b1_interval28       156.463748
total               -20.127646

Values of statistical measures:

        statistical measures
AIC                52.431763
BIC                77.335392
DIC               120.011439
PDIC              -10.513262
log(Z)            -35.278626

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:04:33  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.594319042390185e-05 erg / (s cm2)

                                      low bound  \
GBM: total  5.314478317664314e-05 erg / (s cm2)

                                        hi bound
GBM: total  5.8663555926642486e-05 erg / (s cm2)
17:04:33  INFO        Bin 29 / 72 complete.
17:04:33  INFO      ==== Time bin 30 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   55.281756056611961      +/-  0.11147991702330719
 Total Likelihood Evaluations:        50569
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(5.07 -0.18 +0.23) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-2.42 -0.34 +0.6) x 10^-1,
GBM.spectrum.main.composite.xp_1,(6.22 -0.4 +0.26) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.85 -0.33 +0.15,
GBM.spectrum.main.composite.K_2,(0 +9 +7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8.3 -3.3 +6,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval29       -27.546253
n7_interval29       -38.954465
n8_interval29       -38.579383
b1_interval29       221.542871
total               116.462770

Values of statistical measures:

        statistical measures
AIC              -220.749069
BIC              -195.845439
DIC              -152.658341
PDIC              -10.212412
log(Z)             24.008562

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:05:14  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.236565716125006e-05 erg / (s cm2)

                                      low bound  \
GBM: total  7.867703022848682e-05 erg / (s cm2)

                                       hi bound
GBM: total  8.621526338059183e-05 erg / (s cm2)
17:05:14  INFO        Bin 30 / 72 complete.
17:05:14  INFO      ==== Time bin 31 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   195.69917293963331      +/-  0.11662030719366467
 Total Likelihood Evaluations:        57108
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(6.12 -0.19 +0.22) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-2.49 -0.25 +0.5) x 10^-1,
GBM.spectrum.main.composite.xp_1,(6.96 -0.34 +0.4) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.507 -0.21 +0.030,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -4 +6,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval30         9.086285
n7_interval30         9.695057
n8_interval30         4.922102
b1_interval30       230.673868
total               254.377312

Values of statistical measures:

        statistical measures
AIC              -496.578153
BIC              -471.674524
DIC              -434.816068
PDIC              -10.890394
log(Z)             84.991071

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:05:57  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  0.00013773326290812235 erg / (s cm2)

                                      low bound  \
GBM: total  0.0001326074902585549 erg / (s cm2)

                                        hi bound
GBM: total  0.00014315783120960593 erg / (s cm2)
17:05:57  INFO        Bin 31 / 72 complete.
17:05:57  INFO      ==== Time bin 32 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -341.32104390219831      +/-  0.11827802522706010
 Total Likelihood Evaluations:        59214
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(5.99 -0.08 +0.31) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-3.70 -0.05 +0.6) x 10^-1,
GBM.spectrum.main.composite.xp_1,(5.83 -0.4 +0.10) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.21 -0.04 +0.07,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00012 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -5 +6,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval31      -108.003174
n7_interval31      -146.281614
n8_interval31      -115.492942
b1_interval31        92.948873
total              -276.828857

Values of statistical measures:

        statistical measures
AIC               565.834185
BIC               590.737815
DIC               635.979254
PDIC              -10.914819
log(Z)           -148.233846

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:06:41  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  0.00011439589397319779 erg / (s cm2)

                                       low bound  \
GBM: total  0.00011100626698667169 erg / (s cm2)

                                        hi bound
GBM: total  0.00011798659674751893 erg / (s cm2)
17:06:41  INFO        Bin 32 / 72 complete.
17:06:41  INFO      ==== Time bin 33 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   431.18029488784771      +/-   9.9300594562215586E-002
 Total Likelihood Evaluations:        42269
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(4.23 -0.32 +0.21) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-4.3 -0.7 +0.5) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.79 -0.12 +0.4) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.959 -0.8 +0.034,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00013 +9) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8.3 -3.3 +6,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval32        54.597086
n7_interval32        68.769255
n8_interval32        63.377804
b1_interval32       309.677726
total               496.421870

Values of statistical measures:

        statistical measures
AIC              -980.667270
BIC              -955.763640
DIC              -901.026849
PDIC               -9.416078
log(Z)            187.259223

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:07:18  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.7748648874867302e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.6259512684277414e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.9706039855446817e-05 erg / (s cm2)
17:07:18  INFO        Bin 33 / 72 complete.
17:07:18  INFO      ==== Time bin 34 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -687.22764204773557      +/-  0.11338068649067494
 Total Likelihood Evaluations:        63498
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(3.00 -0.32 +0.13) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-5.81 -0.11 +1.3) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.33 -0.21 +0.29) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.61 -0.25 +0.17,
GBM.spectrum.main.composite.K_2,(0.0 +9 +1.2) x 10^-3,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.10 -0.20 +0.6) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval33      -200.396286
n7_interval33      -220.388204
n8_interval33      -213.243700
b1_interval33        16.588596
total              -617.439593

Values of statistical measures:

        statistical measures
AIC              1247.055658
BIC              1271.959287
DIC              1346.764488
PDIC                0.102192
log(Z)           -298.459173

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:08:04  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.873717559438292e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.754529795290782e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.998881464883079e-05 erg / (s cm2)
17:08:04  INFO        Bin 34 / 72 complete.
17:08:04  INFO      ==== Time bin 35 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -727.16452546128266      +/-  0.11074122034863816
 Total Likelihood Evaluations:        60131
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.92 -0.7 -0.16) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-7.4 -1.2 +0.9) x 10^-1,
GBM.spectrum.main.composite.xp_1,(2.05 +0.26 +1.2) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.15 -1.0 -0.12,
GBM.spectrum.main.composite.K_2,(0.00 +0.29 +1.8) x 10^-3,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9.8 +0.7 +6,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval34      -210.998734
n7_interval34      -223.991165
n8_interval34      -210.335138
b1_interval34       -12.145750
total              -657.470786

Values of statistical measures:

        statistical measures
AIC              1327.118043
BIC              1352.021673
DIC              1428.585248
PDIC               -1.382736
log(Z)           -315.803541

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:08:49  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  7.91010631480776e-06 erg / (s cm2)

                                      low bound  \
GBM: total  7.102078385440228e-06 erg / (s cm2)

                                      hi bound
GBM: total  8.87260821291038e-06 erg / (s cm2)
17:08:49  INFO        Bin 35 / 72 complete.
17:08:49  INFO      ==== Time bin 36 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -648.56063332494989      +/-  0.10061223314898741
 Total Likelihood Evaluations:        56670
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.25 -0.31 +0.08) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-8.5 -0.6 +0.9) x 10^-1,
GBM.spectrum.main.composite.xp_1,(2.34 -0.13 +0.8) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.39 -0.9 +0.05,
GBM.spectrum.main.composite.K_2,(0.00000 +0.00028 +7) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8.3 -0.5 +8,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval35      -194.817785
n7_interval35      -200.424949
n8_interval35      -181.631307
b1_interval35        -0.145957
total              -577.019998

Values of statistical measures:

        statistical measures
AIC              1166.216466
BIC              1191.120095
DIC              1269.056718
PDIC               -1.640074
log(Z)           -281.666304

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:09:30  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.471393434106166e-06 erg / (s cm2)

                                      low bound  \
GBM: total  4.951124979070078e-06 erg / (s cm2)

                                       hi bound
GBM: total  6.210796822226966e-06 erg / (s cm2)
17:09:30  INFO        Bin 36 / 72 complete.
17:09:30  INFO      ==== Time bin 37 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -442.48264065786952      +/-  0.10492072096254400
 Total Likelihood Evaluations:        56841
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.77 -0.16 +0.04) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-6.91 -0.24 +1.9) x 10^-1,
GBM.spectrum.main.composite.xp_1,(4.80 -0.31 +0.5) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.59 -0.6 +0.11,
GBM.spectrum.main.composite.K_2,(0.0 +1.9 +1.3) x 10^-3,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9.3 -1.3 +6,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval36      -145.171906
n7_interval36      -142.455442
n8_interval36      -154.047836
b1_interval36        68.771099
total              -372.904085

Values of statistical measures:

        statistical measures
AIC               757.984640
BIC               782.888270
DIC               857.222766
PDIC               -1.675170
log(Z)           -192.167769

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:10:15  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.7158700883283493e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.586928996823125e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.8690769751410848e-05 erg / (s cm2)
17:10:15  INFO        Bin 37 / 72 complete.
17:10:15  INFO      ==== Time bin 38 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -522.08536622080624      +/-  0.10719707484487355
 Total Likelihood Evaluations:        50154
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.50 -0.08 +0.10) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-5.78 -0.28 +0.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(5.57 -0.4 +0.28) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.79 -0.23 +0.24,
GBM.spectrum.main.composite.K_2,(0 +9 +4) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval37      -163.246741
n7_interval37      -177.677705
n8_interval37      -173.986632
b1_interval37        60.349618
total              -454.561460

Values of statistical measures:

        statistical measures
AIC               921.299390
BIC               946.203019
DIC               997.754603
PDIC              -12.075259
log(Z)           -226.738794

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:10:56  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  3.028627865132052e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.8684780337024203e-05 erg / (s cm2)

                                       hi bound
GBM: total  3.200439095455256e-05 erg / (s cm2)
17:10:56  INFO        Bin 38 / 72 complete.
17:10:56  INFO      ==== Time bin 39 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -783.25991882485823      +/-  0.11536552428021844
 Total Likelihood Evaluations:        58046
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(3.08 -0.05 +0.09) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-5.36 -0.16 +0.31) x 10^-1,
GBM.spectrum.main.composite.xp_1,(6.67 +/- 0.26) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.18 -0.32 +0.23,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,10 +/- 5,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval38      -233.552365
n7_interval38      -251.586241
n8_interval38      -225.646807
b1_interval38        -8.010377
total              -718.795789

Values of statistical measures:

        statistical measures
AIC              1449.768049
BIC              1474.671679
DIC              1517.630417
PDIC              -14.190260
log(Z)           -340.165461

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:11:39  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.540853151987981e-05 erg / (s cm2)

                                   low bound  \
GBM: total  4.390131654849e-05 erg / (s cm2)

                                        hi bound
GBM: total  4.6953990923366686e-05 erg / (s cm2)
17:11:39  INFO        Bin 39 / 72 complete.
17:11:39  INFO      ==== Time bin 40 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -249.97184051504965      +/-  0.11471661565178715
 Total Likelihood Evaluations:        56484
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(3.77 -0.10 +0.09) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-4.65 -0.26 +0.31) x 10^-1,
GBM.spectrum.main.composite.xp_1,(7.11 -0.30 +0.29) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.60 -0.15 +0.5,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8.4 -3.5 +6,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval39      -104.469260
n7_interval39      -116.904064
n8_interval39      -107.515509
b1_interval39       138.469072
total              -190.419760

Values of statistical measures:

        statistical measures
AIC               393.015991
BIC               417.919621
DIC               455.745552
PDIC              -11.489903
log(Z)           -108.561391

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:12:20  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.134367991343107e-05 erg / (s cm2)

                                       low bound  \
GBM: total  5.9224650022627576e-05 erg / (s cm2)

                                       hi bound
GBM: total  6.364211233540346e-05 erg / (s cm2)
17:12:20  INFO        Bin 40 / 72 complete.
17:12:20  INFO      ==== Time bin 41 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -615.88151866396981      +/-  0.12067003910698082
 Total Likelihood Evaluations:        60564
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(5.47 -0.12 +0.10) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-3.32 -0.25 +0.23) x 10^-1,
GBM.spectrum.main.composite.xp_1,(6.49 -0.22 +0.17) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.86 -0.10 +0.13,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +9) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 -0.6 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval40      -192.784424
n7_interval40      -203.472012
n8_interval40      -201.235539
b1_interval40        45.191655
total              -552.300320

Values of statistical measures:

        statistical measures
AIC              1116.777110
BIC              1141.680740
DIC              1185.705350
PDIC              -10.356075
log(Z)           -267.473945

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:13:05  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  9.237065182542081e-05 erg / (s cm2)

                                      low bound  \
GBM: total  8.995294945080031e-05 erg / (s cm2)

                                       hi bound
GBM: total  9.484316916251462e-05 erg / (s cm2)
17:13:05  INFO        Bin 41 / 72 complete.
17:13:05  INFO      ==== Time bin 42 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=   129.38867829545069      +/-  0.10666306272609873
 Total Likelihood Evaluations:        48033
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(5.13 -0.22 +0.16) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-4.10 -0.4 +0.30) x 10^-1,
GBM.spectrum.main.composite.xp_1,(5.05 -0.19 +0.26) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.43 -0.35 +0.32,
GBM.spectrum.main.composite.K_2,(0.0 +1.1 +1.0) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 +/- 0.5) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval41        -9.059289
n7_interval41       -25.271612
n8_interval41       -11.225919
b1_interval41       238.606072
total               193.049253

Values of statistical measures:

        statistical measures
AIC              -373.922035
BIC              -349.018405
DIC              -299.755499
PDIC              -10.254523
log(Z)             56.192789

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:13:45  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.053803812065723e-05 erg / (s cm2)

                                      low bound  \
GBM: total  4.860345255543487e-05 erg / (s cm2)

                                       hi bound
GBM: total  5.283124949963808e-05 erg / (s cm2)
17:13:45  INFO        Bin 42 / 72 complete.
17:13:45  INFO      ==== Time bin 43 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -37.597246006281338      +/-  0.10425779911774119
 Total Likelihood Evaluations:        51542
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(4.71 -0.32 +0.16) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-4.4 -0.5 +0.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.53 -0.13 +0.22) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.19 -0.4 +0.29,
GBM.spectrum.main.composite.K_2,(0.0 +1.3 +1.6) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.25 -0.8 +0.25) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval42       -47.188236
n7_interval42       -77.487932
n8_interval42       -54.056624
b1_interval42       206.502795
total                27.770003

Values of statistical measures:

        statistical measures
AIC               -43.363536
BIC               -18.459907
DIC                34.958150
PDIC               -9.454721
log(Z)            -16.328276

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:14:27  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.7143839386178075e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.5945431584289167e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.8638523613207866e-05 erg / (s cm2)
17:14:27  INFO        Bin 43 / 72 complete.
17:14:27  INFO      ==== Time bin 44 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1471.7907624719635      +/-  0.11749459428869888
 Total Likelihood Evaluations:        83656
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.50 -0.14 +0.05) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-6.80 -0.25 +0.19) x 10^-1,
GBM.spectrum.main.composite.xp_1,(4.12 -0.11 +0.28) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.58 -0.16 +0.09,
GBM.spectrum.main.composite.K_2,(0.0 +2.6 +1.6) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.2 -0.6 +0.7) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval43      -399.660633
n7_interval43      -415.301163
n8_interval43      -399.077627
b1_interval43      -184.480137
total             -1398.519561

Values of statistical measures:

        statistical measures
AIC              2809.215592
BIC              2834.119221
DIC              2901.440009
PDIC               -5.513418
log(Z)           -639.190607

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:15:20  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.0866512257668036e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.0141884100846815e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.160033101714708e-05 erg / (s cm2)
17:15:20  INFO        Bin 44 / 72 complete.
17:15:20  INFO      ==== Time bin 45 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -208.95458681420183      +/-  0.10483914371505501
 Total Likelihood Evaluations:        46150
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(3.32 -0.12 +0.11) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-5.62 -0.22 +0.5) x 10^-1,
GBM.spectrum.main.composite.xp_1,(4.97 -0.24 +0.25) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.35 -0.33 +0.4,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00010 +9) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval44       -99.264978
n7_interval44       -97.994282
n8_interval44       -88.527210
b1_interval44       143.352222
total              -142.434248

Values of statistical measures:

        statistical measures
AIC               297.044967
BIC               321.948596
DIC               373.791733
PDIC              -12.334854
log(Z)            -90.747824

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:15:57  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  3.111504057546853e-05 erg / (s cm2)

                                      low bound  \
GBM: total  2.977585464415791e-05 erg / (s cm2)

                                       hi bound
GBM: total  3.275231466959475e-05 erg / (s cm2)
17:15:57  INFO        Bin 45 / 72 complete.
17:15:57  INFO      ==== Time bin 46 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -569.63964184091776      +/-  0.10479347349542720
 Total Likelihood Evaluations:        48839
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.74 +/- 0.11) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-6.44 -0.31 +0.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.56 -0.11 +0.24) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.26 -0.5 +0.22,
GBM.spectrum.main.composite.K_2,(0 +9 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval45      -185.063974
n7_interval45      -192.944837
n8_interval45      -176.693717
b1_interval45        54.511678
total              -500.190851

Values of statistical measures:

        statistical measures
AIC              1012.558172
BIC              1037.461802
DIC              1094.504745
PDIC              -10.764553
log(Z)           -247.391353

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:16:36  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.607218177052956e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.548775574752598e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.681578364077282e-05 erg / (s cm2)
17:16:36  INFO        Bin 46 / 72 complete.
17:16:36  INFO      ==== Time bin 47 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -594.61863487774269      +/-  0.10338174363306910
 Total Likelihood Evaluations:        47804
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.35 -0.21 +0.09) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-5.71 -0.7 +0.30) x 10^-1,
GBM.spectrum.main.composite.xp_1,(2.81 -0.10 +0.25) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.75 -0.24 +0.25,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00012 +7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.13 -0.7 +0.31) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval46      -180.317388
n7_interval46      -189.125203
n8_interval46      -179.417485
b1_interval46        25.196062
total              -523.664014

Values of statistical measures:

        statistical measures
AIC              1059.504498
BIC              1084.408128
DIC              1144.839665
PDIC              -10.549951
log(Z)           -258.239592

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:17:16  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.1369344042602891e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.0527462486981516e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.2269392016139626e-05 erg / (s cm2)
17:17:16  INFO        Bin 47 / 72 complete.
17:17:16  INFO      ==== Time bin 48 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   417.69781052157208      +/-   8.6747138474891128E-002
 Total Likelihood Evaluations:        37031
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.69 -0.4 +0.06) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-7.00 -2.0 +0.22) x 10^-1,
GBM.spectrum.main.composite.xp_1,(2.12 -0.06 +0.6) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.42 -0.7 +0.11,
GBM.spectrum.main.composite.K_2,(0.0 +1.2 +1.3) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 -0.5 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval47        83.019998
n7_interval47        68.180160
n8_interval47        78.070980
b1_interval47       258.358758
total               487.629895

Values of statistical measures:

        statistical measures
AIC              -963.083320
BIC              -938.179690
DIC              -874.388822
PDIC              -10.872590
log(Z)            181.403854

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:17:51  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  6.31314214492848e-06 erg / (s cm2)

                                     low bound  \
GBM: total  5.52202872265643e-06 erg / (s cm2)

                                      hi bound
GBM: total  7.44014156259871e-06 erg / (s cm2)
17:17:51  INFO        Bin 48 / 72 complete.
17:17:51  INFO      ==== Time bin 49 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -490.74147538154796      +/-  0.10110056242958602
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        46449
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.06 -0.15 +0.11) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-6.6 -0.6 +0.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.03 -0.17 +0.23) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.01 -0.4 +0.34,
GBM.spectrum.main.composite.K_2,(0.0 +1.4 +1.6) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.5 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval48      -160.511208
n7_interval48      -157.299561
n8_interval48      -158.522141
b1_interval48        56.515931
total              -419.816979

Values of statistical measures:

        statistical measures
AIC               851.810429
BIC               876.714058
DIC               941.283432
PDIC               -7.734856
log(Z)           -213.126315

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:18:31  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.0249970401034484e-05 erg / (s cm2)

                                    low bound  \
GBM: total  9.6172355789027e-06 erg / (s cm2)

                                       hi bound
GBM: total  1.104214081990658e-05 erg / (s cm2)
17:18:31  INFO        Bin 49 / 72 complete.
17:18:31  INFO      ==== Time bin 50 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -47.017449322664916      +/-  0.10119852900221163
 Total Likelihood Evaluations:        43272
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.53 -0.19 +0.04) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-5.4 -0.5 +0.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(5.10 -0.12 +0.6) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.719 -0.7 +0.030,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00012 +9) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.14 -0.6 +0.31) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval49       -49.868728
n7_interval49       -61.868275
n8_interval49       -51.164606
b1_interval49       183.611470
total                20.709860

Values of statistical measures:

        statistical measures
AIC               -29.243250
BIC                -4.339621
DIC                52.546113
PDIC              -10.567290
log(Z)            -20.419419

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:19:09  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.6841487570853218e-05 erg / (s cm2)

                                      low bound  \
GBM: total  2.523904567975474e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.874799656556688e-05 erg / (s cm2)
17:19:09  INFO        Bin 50 / 72 complete.
17:19:09  INFO      ==== Time bin 51 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   173.57552996781001      +/-  0.10821621276967003
 Total Likelihood Evaluations:        50149
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(3.39 -0.18 +0.08) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-4.41 -0.6 +0.30) x 10^-1,
GBM.spectrum.main.composite.xp_1,(6.71 -0.16 +0.7) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.715 -0.6 -0.035,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +10) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8.2 -3.3 +6,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval50         6.061225
n7_interval50       -14.974718
n8_interval50        -3.195973
b1_interval50       247.649475
total               235.540009

Values of statistical measures:

        statistical measures
AIC              -458.903548
BIC              -433.999919
DIC              -388.334270
PDIC              -11.076832
log(Z)             75.382895

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:19:49  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  5.6680405777104185e-05 erg / (s cm2)

                                      low bound  \
GBM: total  5.382227616766597e-05 erg / (s cm2)

                                       hi bound
GBM: total  5.973230285713813e-05 erg / (s cm2)
17:19:49  INFO        Bin 51 / 72 complete.
17:19:49  INFO      ==== Time bin 52 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -111.42964268965142      +/-  0.10372832637842627
 Total Likelihood Evaluations:        45464
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(3.79 -0.23 +0.22) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-3.7 -0.6 +0.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.40 -0.13 +0.26) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.95 -0.34 +0.24,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00012 +9) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -4 +6,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval51       -65.287503
n7_interval51       -73.130629
n8_interval51       -71.285038
b1_interval51       165.185026
total               -44.518144

Values of statistical measures:

        statistical measures
AIC               101.212759
BIC               126.116388
DIC               180.794659
PDIC              -10.158369
log(Z)            -48.393279

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:20:28  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.2139370237560712e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.0914900954995254e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.356484076499152e-05 erg / (s cm2)
17:20:28  INFO        Bin 52 / 72 complete.
17:20:28  INFO      ==== Time bin 53 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -596.47308942506538      +/-  0.10303586438053675
 Total Likelihood Evaluations:        47335
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.44 -0.12 +0.11) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-6.3 +/- 0.4) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.41 -0.16 +0.20) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.1 +/- 0.4,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00010 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.12 -0.6 +0.35) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval52      -186.891092
n7_interval52      -201.701610
n8_interval52      -173.865100
b1_interval52        35.459884
total              -526.997918

Values of statistical measures:

        statistical measures
AIC              1066.172307
BIC              1091.075936
DIC              1148.805512
PDIC              -10.640657
log(Z)           -259.044971

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:21:05  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.3776346389158637e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.302511626037484e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.478279548795945e-05 erg / (s cm2)
17:21:05  INFO        Bin 53 / 72 complete.
17:21:05  INFO      ==== Time bin 54 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -534.55963664833700      +/-  0.10172347481468449
 Total Likelihood Evaluations:        47792
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.25 -0.16 +0.20) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-6.6 -0.4 +0.7) x 10^-1,
GBM.spectrum.main.composite.xp_1,(2.49 -0.18 +0.19) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.47 -0.5 +0.05,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00010 +8) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval53      -152.130944
n7_interval53      -172.205787
n8_interval53      -172.794122
b1_interval53        33.565703
total              -463.565151

Values of statistical measures:

        statistical measures
AIC               939.306772
BIC               964.210401
DIC              1025.844906
PDIC               -9.777309
log(Z)           -232.156300

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:21:44  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  9.619293304853865e-06 erg / (s cm2)

                                      low bound  \
GBM: total  8.773345548704273e-06 erg / (s cm2)

                                       hi bound
GBM: total  1.054509157632291e-05 erg / (s cm2)
17:21:44  INFO        Bin 54 / 72 complete.
17:21:44  INFO      ==== Time bin 55 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -374.40556612642479      +/-   9.5397547228784144E-002
 Total Likelihood Evaluations:        47686
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.29 -0.26 +0.14) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-9.2 -1.3 +0.6) x 10^-1,
GBM.spectrum.main.composite.xp_1,(1.53 -0.10 +0.4) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.33 -0.6 +0.09,
GBM.spectrum.main.composite.K_2,(0.0 +1.5 +2.6) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.24 -0.7 +0.21) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval54      -108.538602
n7_interval54      -132.005809
n8_interval54      -120.445774
b1_interval54        58.601145
total              -302.389040

Values of statistical measures:

        statistical measures
AIC               616.954552
BIC               641.858181
DIC               706.622159
PDIC              -11.360039
log(Z)           -162.602271

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:22:24  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  3.969695551965922e-06 erg / (s cm2)

                                      low bound  \
GBM: total  3.451146117789293e-06 erg / (s cm2)

                                       hi bound
GBM: total  4.608868535088147e-06 erg / (s cm2)
17:22:24  INFO        Bin 55 / 72 complete.
17:22:24  INFO      ==== Time bin 56 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1095.0982529391231      +/-   9.4275233719752910E-002
 Total Likelihood Evaluations:        40554
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(4.5 -0.7 +0.5) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.17 -0.10 +0.06,
GBM.spectrum.main.composite.xp_1,(1.54 -0.16 +0.29) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.7 -0.6 +0.4,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00010 +4) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval55      -301.673986
n7_interval55      -293.649653
n8_interval55      -284.345173
b1_interval55      -140.319674
total             -1019.988486

Values of statistical measures:

        statistical measures
AIC              2052.153443
BIC              2077.057072
DIC              2143.302733
PDIC              -12.654474
log(Z)           -475.595128

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:22:59  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.5250260273649872e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.3744688994798993e-06 erg / (s cm2)

                                       hi bound
GBM: total  1.762631396749033e-06 erg / (s cm2)
17:22:59  INFO        Bin 56 / 72 complete.
17:22:59  INFO      ==== Time bin 57 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1585.1750786557127      +/-   9.1569426968269765E-002
 Total Likelihood Evaluations:        53092
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.39 -1.1 -0.16) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.232 -0.27 -0.023,
GBM.spectrum.main.composite.xp_1,(1.36 +0.21 +2.9) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-1.96 -1.2 -0.05,
GBM.spectrum.main.composite.K_2,(0.0 +4 +1.0) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8.4 -1.7 +9,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval56      -399.599370
n7_interval56      -425.014746
n8_interval56      -411.688980
b1_interval56      -271.929681
total             -1508.232777

Values of statistical measures:

        statistical measures
AIC              3028.642025
BIC              3053.545654
DIC              3101.412064
PDIC              -38.590494
log(Z)           -688.432790

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:23:40  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.1124028752369923e-06 erg / (s cm2)

                                      low bound  \
GBM: total  9.337755605372792e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.3871917232449598e-06 erg / (s cm2)
17:23:40  INFO        Bin 57 / 72 complete.
17:23:40  INFO      ==== Time bin 58 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1616.0241300157677      +/-   8.2934265170868840E-002
 Total Likelihood Evaluations:        44445
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                      result              unit
parameter
GBM.spectrum.main.composite.K_1      (9.0 -1.0 +3.1) x 10^-3   1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1        -1.39 -0.06 +0.28
GBM.spectrum.main.composite.xp_1      (2.2 -0.4 +1.0) x 10^2               keV
GBM.spectrum.main.composite.beta_1            -3.0 -0.6 +0.5
GBM.spectrum.main.composite.K_2      (0.0 +1.7 +1.3) x 10^-3  1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2                 8.0 -2.7 +6               keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval57      -433.808957
n7_interval57      -413.794663
n8_interval57      -404.276920
b1_interval57      -285.164116
total             -1537.044655

Values of statistical measures:

        statistical measures
AIC              3086.265780
BIC              3111.169410
DIC              3166.780835
PDIC              -35.414153
log(Z)           -701.830362

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:24:19  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  4.82081418507451e-07 erg / (s cm2)

                                      low bound  \
GBM: total  4.158793358422088e-07 erg / (s cm2)

                                      hi bound
GBM: total  5.80274770183621e-07 erg / (s cm2)
17:24:19  INFO        Bin 58 / 72 complete.
17:24:19  INFO      ==== Time bin 59 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3169.8972650502028      +/-   8.6314523782068567E-002
 Total Likelihood Evaluations:        32744
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(3.94 -0.18 +0.5) x 10^-3,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.545 -0.027 +0.09,
GBM.spectrum.main.composite.xp_1,(3.6 -0.8 +1.8) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-1.81 -1.3 -0.13,
GBM.spectrum.main.composite.K_2,(0.0001 +0.0006 +7) x 10^-6,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8.0 -3.3 +6,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval58      -797.809214
n7_interval58      -803.267958
n8_interval58      -801.480718
b1_interval58      -686.227567
total             -3088.785456

Values of statistical measures:

        statistical measures
AIC              6189.747383
BIC              6214.651013
DIC              6282.991225
PDIC              -20.008872
log(Z)          -1376.668890

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:24:52  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  3.571821603741682e-07 erg / (s cm2)

                                      low bound  \
GBM: total  3.010157547652624e-07 erg / (s cm2)

                                        hi bound
GBM: total  4.5476274262147244e-07 erg / (s cm2)
17:24:52  INFO        Bin 59 / 72 complete.
17:24:52  INFO      ==== Time bin 60 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -2655.4281006415385      +/-   7.1259841785768371E-002
 Total Likelihood Evaluations:        26210
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.150 -0.007 +0.6) x 10^-3,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.68 +0.04 +0.4,
GBM.spectrum.main.composite.xp_1,(4.1 -2.3 +0.9) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.6 -0.8 +0.5,
GBM.spectrum.main.composite.K_2,(0 +9 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.09 -0.7 +0.31) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval59      -678.878306
n7_interval59      -671.930721
n8_interval59      -673.703453
b1_interval59      -547.354002
total             -2571.866482

Values of statistical measures:

        statistical measures
AIC              5155.909435
BIC              5180.813065
DIC              5184.720012
PDIC              -93.989924
log(Z)          -1153.237771

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:25:25  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.0185536673334357e-07 erg / (s cm2)

                                     low bound  \
GBM: total  7.71579811911406e-08 erg / (s cm2)

                                       hi bound
GBM: total  1.331187368656914e-07 erg / (s cm2)
17:25:25  INFO        Bin 60 / 72 complete.
17:25:25  INFO      ==== Time bin 61 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -3773.6177002671952      +/-   4.9655636272278800E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        11020
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.10 +0.18 +3.5) x 10^-5,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.09 -0.16 +0.7,
GBM.spectrum.main.composite.xp_1,(2.7 -1.6 +2.1) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-3.19 -0.22 +1.1,
GBM.spectrum.main.composite.K_2,(0.001 +0.004 +7) x 10^-7,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.22 -0.7 +0.22) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval60      -950.185306
n7_interval60      -945.448531
n8_interval60      -947.133328
b1_interval60      -829.065928
total             -3671.833094

Values of statistical measures:

        statistical measures
AIC              7355.842658
BIC              7380.746287
DIC              7457.590039
PDIC              -49.788100
log(Z)          -1638.861344

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

17:25:43  WARNING   Too few points to create valid contours

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:25:43  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2315067837339995e-09 erg / (s cm2)

                                      low bound  \
GBM: total  4.367330717377925e-10 erg / (s cm2)

                                        hi bound
GBM: total  2.9205380353955408e-09 erg / (s cm2)
17:25:43  INFO        Bin 61 / 72 complete.
17:25:43  INFO      ==== Time bin 62 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -1720.8617213876869      +/-   5.8802717278204790E-002
 Total Likelihood Evaluations:        16319
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                      result              unit
parameter
GBM.spectrum.main.composite.K_1      (1.9 -0.4 +0.9) x 10^-3   1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1         -1.01 -0.07 +0.5
GBM.spectrum.main.composite.xp_1      (4.9 -2.2 +0.6) x 10^2               keV
GBM.spectrum.main.composite.beta_1          -3.10 -0.32 +1.0
GBM.spectrum.main.composite.K_2        (0.0 +9 +1.5) x 10^-5  1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2      (1.11 -0.6 +0.32) x 10               keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval61      -434.183232
n7_interval61      -454.713085
n8_interval61      -437.649584
b1_interval61      -312.801727
total             -1639.347628

Values of statistical measures:

        statistical measures
AIC              3290.871726
BIC              3315.775355
DIC              3396.549847
PDIC              -15.314021
log(Z)           -747.360750

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:26:06  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.601676563571884e-07 erg / (s cm2)

                                      low bound  \
GBM: total  1.097444258285726e-07 erg / (s cm2)

                                        hi bound
GBM: total  2.3337839840233962e-07 erg / (s cm2)
17:26:06  INFO        Bin 62 / 72 complete.
17:26:06  INFO      ==== Time bin 63 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2689.7432480556872      +/-   8.7184134189492224E-002
 Total Likelihood Evaluations:        34385
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(8.9 -1.2 +0.5) x 10^-3,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,(-7.9 -1.2 +0.5) x 10^-1,
GBM.spectrum.main.composite.xp_1,(3.94 -0.22 +1.5) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-1.96 -1.2 -0.07,
GBM.spectrum.main.composite.K_2,(0.0 +7 +1.1) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -4 +5,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval62      -679.867100
n7_interval62      -689.418697
n8_interval62      -680.833591
b1_interval62      -558.258493
total             -2608.377881

Values of statistical measures:

        statistical measures
AIC              5228.932233
BIC              5253.835862
DIC              5327.491760
PDIC              -15.920320
log(Z)          -1168.140650

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:26:39  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.410006271434859e-07 erg / (s cm2)

                                      low bound  \
GBM: total  7.049402064065526e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.0473742392670442e-06 erg / (s cm2)
17:26:39  INFO        Bin 63 / 72 complete.
17:26:39  INFO      ==== Time bin 64 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2378.5596209323689      +/-   9.0104376852075646E-002
 Total Likelihood Evaluations:        33973
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.21 -0.09 +0.08) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.00 +/- 0.06,
GBM.spectrum.main.composite.xp_1,(4.3 -0.5 +0.8) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.63 -0.9 +0.19,
GBM.spectrum.main.composite.K_2,(0.0 +7 +1.3) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 -0.6 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval63      -602.585031
n7_interval63      -607.874892
n8_interval63      -611.525593
b1_interval63      -476.102891
total             -2298.088408

Values of statistical measures:

        statistical measures
AIC              4608.353286
BIC              4633.256915
DIC              4699.244503
PDIC              -21.364391
log(Z)          -1032.995318

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:27:11  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  9.67681294744527e-07 erg / (s cm2)

                                      low bound  \
GBM: total  8.699902793291607e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.1120018356581038e-06 erg / (s cm2)
17:27:11  INFO        Bin 64 / 72 complete.
17:27:11  INFO      ==== Time bin 65 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -3072.2990804777128      +/-  0.10293615024543083
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        49379
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(2.30 +/- 0.09) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.118 -0.028 +0.027,
GBM.spectrum.main.composite.xp_1,(3.84 -0.33 +0.35) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.58 -0.6 +0.25,
GBM.spectrum.main.composite.K_2,(0.0 +8 +1.6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 +/- 0.5) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval64      -780.494852
n7_interval64      -784.175030
n8_interval64      -780.854639
b1_interval64      -645.116943
total             -2990.641464

Values of statistical measures:

        statistical measures
AIC              5993.459398
BIC              6018.363028
DIC              6092.681290
PDIC              -11.429449
log(Z)          -1334.282537

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:27:50  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.705288994836339e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.5590747417860046e-06 erg / (s cm2)

                                       hi bound
GBM: total  1.896467450356385e-06 erg / (s cm2)
17:27:50  INFO        Bin 65 / 72 complete.
17:27:50  INFO      ==== Time bin 66 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2159.4113577384028      +/-   9.2897313582255461E-002
 Total Likelihood Evaluations:        42294
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.90 -0.20 +0.19) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.15 -0.06 +0.07,
GBM.spectrum.main.composite.xp_1,(2.64 -0.31 +0.8) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.10 -0.8 +0.08,
GBM.spectrum.main.composite.K_2,(0.0 +7 +1.3) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.25 -0.8 +0.22) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval65      -546.994680
n7_interval65      -554.705863
n8_interval65      -549.478403
b1_interval65      -428.968418
total             -2080.147364

Values of statistical measures:

        statistical measures
AIC              4172.471198
BIC              4197.374827
DIC              4261.939826
PDIC              -19.747655
log(Z)           -937.820437

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:28:28  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2997907621331815e-06 erg / (s cm2)

                                      low bound  \
GBM: total  1.070283714086179e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.5747122649393637e-06 erg / (s cm2)
17:28:28  INFO        Bin 66 / 72 complete.
17:28:28  INFO      ==== Time bin 67 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1740.6884950280876      +/-   9.5627582564417543E-002
 Total Likelihood Evaluations:        45281
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(3.20 -0.35 +0.31) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.10 -0.07 +0.06,
GBM.spectrum.main.composite.xp_1,(2.7 -0.4 +0.6) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.19 -0.5 +0.19,
GBM.spectrum.main.composite.K_2,(0.0 +8 +2.4) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.16 -0.7 +0.29) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval66      -447.545320
n7_interval66      -449.969468
n8_interval66      -450.119328
b1_interval66      -314.544662
total             -1662.178778

Values of statistical measures:

        statistical measures
AIC              3336.534026
BIC              3361.437655
DIC              3412.594908
PDIC              -32.191694
log(Z)           -755.971408

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:29:07  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.2192688713411293e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.8160185674696969e-06 erg / (s cm2)

                                        hi bound
GBM: total  2.6041944856534654e-06 erg / (s cm2)
17:29:07  INFO        Bin 67 / 72 complete.
17:29:07  INFO      ==== Time bin 68 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2164.4808035494229      +/-   9.4131485999426223E-002
 Total Likelihood Evaluations:        48206
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.93 -0.15 +0.12) x 10^-2,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.28 -0.04 +0.06,
GBM.spectrum.main.composite.xp_1,(2.75 -0.22 +0.6) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.9 -0.6 +0.4,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00014 +9) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8.1 -2.7 +6,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval67      -544.779408
n7_interval67      -562.973509
n8_interval67      -558.285739
b1_interval67      -419.242737
total             -2085.281392

Values of statistical measures:

        statistical measures
AIC              4182.739255
BIC              4207.642885
DIC              4287.437733
PDIC               -6.546592
log(Z)           -940.022069

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:29:46  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.090867746167958e-06 erg / (s cm2)

                                      low bound  \
GBM: total  1.009339626131727e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.2204846730332092e-06 erg / (s cm2)
17:29:46  INFO        Bin 68 / 72 complete.
17:29:46  INFO      ==== Time bin 69 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2067.0298588166502      +/-   8.7263328312773766E-002
 Total Likelihood Evaluations:        39919
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                      result              unit
parameter
GBM.spectrum.main.composite.K_1      (1.18 +/- 0.10) x 10^-2   1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1        -1.37 -0.05 +0.07
GBM.spectrum.main.composite.xp_1      (3.5 -0.7 +0.9) x 10^2               keV
GBM.spectrum.main.composite.beta_1          -2.46 -0.9 +0.27
GBM.spectrum.main.composite.K_2        (0.0 +8 +1.1) x 10^-5  1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2        (1.1 -0.6 +0.4) x 10               keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval68      -516.036026
n7_interval68      -541.176792
n8_interval68      -526.744696
b1_interval68      -403.050443
total             -1987.007957

Values of statistical measures:

        statistical measures
AIC              3986.192385
BIC              4011.096014
DIC              4040.285323
PDIC              -58.640207
log(Z)           -897.699662

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:30:23  INFO        10 keV-10 MeV flux =                                          flux  \
GBM: total  8.4771417144651e-07 erg / (s cm2)

                                      low bound  \
GBM: total  7.417075257290514e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.0186190294766783e-06 erg / (s cm2)
17:30:23  INFO        Bin 69 / 72 complete.
17:30:23  INFO      ==== Time bin 70 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
 ln(ev)=  -2242.0834445692994      +/-   8.3981904436871688E-002
 Total Likelihood Evaluations:        33639
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(7.4 -1.0 +1.3) x 10^-3,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.44 -0.06 +0.11,
GBM.spectrum.main.composite.xp_1,(2.6 -0.7 +1.4) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.35 -1.0 +0.33,
GBM.spectrum.main.composite.K_2,(0.00001 +0.00012 +2.7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval69      -567.974188
n7_interval69      -579.188838
n8_interval69      -556.004577
b1_interval69      -458.415093
total             -2161.582696

Values of statistical measures:

        statistical measures
AIC              4335.341862
BIC              4360.245491
DIC              4435.222370
PDIC              -15.179363
log(Z)           -973.724468

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:30:54  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.876892835912611e-07 erg / (s cm2)

                                       low bound  \
GBM: total  4.1030304258587033e-07 erg / (s cm2)

                                       hi bound
GBM: total  6.328559494763416e-07 erg / (s cm2)
17:30:54  INFO        Bin 70 / 72 complete.
17:30:54  INFO      ==== Time bin 71 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3434.7910251277344      +/-   8.3130139277187695E-002
 Total Likelihood Evaluations:        34417
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                      result              unit
parameter
GBM.spectrum.main.composite.K_1      (3.5 -0.5 +0.8) x 10^-3   1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1        -1.44 -0.07 +0.13
GBM.spectrum.main.composite.xp_1      (2.5 -0.8 +1.1) x 10^2               keV
GBM.spectrum.main.composite.beta_1          -3.09 -0.29 +1.0
GBM.spectrum.main.composite.K_2        (0.0 +7 +1.5) x 10^-5  1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2        (1.1 -0.6 +0.4) x 10               keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval70      -870.454832
n7_interval70      -867.558496
n8_interval70      -849.004802
b1_interval70      -764.737798
total             -3351.755928

Values of statistical measures:

        statistical measures
AIC              6715.688326
BIC              6740.591955
DIC              6808.583501
PDIC              -24.999125
log(Z)          -1491.710789

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:31:26  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.1650372458773564e-07 erg / (s cm2)

                                       low bound  \
GBM: total  1.8341195359608452e-07 erg / (s cm2)

                                        hi bound
GBM: total  2.7551327559054367e-07 erg / (s cm2)
17:31:26  INFO        Bin 71 / 72 complete.
17:31:26  INFO      ==== Time bin 72 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    6
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3027.3612322180138      +/-   7.2403082943570299E-002
 Total Likelihood Evaluations:        24876
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(1.15 -0.17 +0.32) x 10^-3,1 / (keV s cm2)
GBM.spectrum.main.composite.alpha_1,-1.57 -0.06 +0.27,
GBM.spectrum.main.composite.xp_1,(3.8 -2.0 +1.1) x 10^2,keV
GBM.spectrum.main.composite.beta_1,-2.36 -1.0 +0.28,
GBM.spectrum.main.composite.K_2,(0 +9 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -4 +5,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval71      -746.647193
n7_interval71      -756.130871
n8_interval71      -748.864566
b1_interval71      -690.921638
total             -2942.564268

Values of statistical measures:

        statistical measures
AIC              5897.305007
BIC              5922.208636
DIC              5989.553386
PDIC              -31.759317
log(Z)          -1314.766278

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

17:31:55  WARNING   Too few points to create valid contours

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:31:55  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.492560474346493e-08 erg / (s cm2)

                                      low bound  \
GBM: total  6.604782842077961e-08 erg / (s cm2)

                                        hi bound
GBM: total  1.1011259254887247e-07 erg / (s cm2)
17:31:55  INFO        Bin 72 / 72 complete.

All 72 bins fitted successfully.

In [17]:
    ## Cell 14 — Save Results to CSV (Band+BB)

In [18]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    fit_array = np.array(fit_rows)
    bandbb_fit_param = Table(fit_array, names=PARAM_NAMES)
    bandbb_fit_param['t_start'] = bb_starts
    bandbb_fit_param['t_stop']  = bb_stops
    bandbb_fit_param['dt']      = bb_stops - bb_starts

    csv_path = os.path.join(MODEL_PATHS['root'], 'fit_params.csv')
    bandbb_fit_param.write(csv_path, overwrite=True)
    print(f'Results saved to: {csv_path}')
    print(f'Shape: {fit_array.shape}  ({n_bins} bins x {len(PARAM_NAMES)} parameters)')
    bandbb_fit_param

Results saved to: gbm_pipeline_output/bandbb/fit_params.csv
Shape: (72, 30)  (72 bins x 30 parameters)

## Cell 15 — Time-Resolved Spectral Fitting (Cutoff+BB Model)

In [19]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    MODEL_PATHS = get_model_paths('cutoffbb')

    PARAM_NAMES = []
    for p in ['K_1', 'index_1', 'xc_1', 'K_2', 'kT_2']:
        PARAM_NAMES.extend([p, f'{p}_n_err', f'{p}_p_err', f'{p}_avg_err'])
    PARAM_NAMES.extend(['flux', 'flux_low', 'flux_hi', 'DIC', 'PDIC', 'BIC'])

    fit_rows = []

    for i in range(n_bins):
        log.info('==== Time bin %d / %d ====', i + 1, n_bins)

        det_plugins = []
        for det in detectors:
            p = time_resolved_plugins[det][i]
            if det.startswith('b'):
                p.set_active_measurements(CONFIG['bgo_range'])
            else:
                ranges = [r.strip() for r in CONFIG['nai_range'].split(',')]
                p.set_active_measurements(*ranges)
            det_plugins.append(p)

        data_list = DataList(*det_plugins)
        model = build_cutoffbb_model(CONFIG['ra'], CONFIG['dec'], CONFIG['priors_cutoffbb'])

        bayes = BayesianAnalysis(model, data_list)
        bayes.set_sampler('multinest')
        bayes.sampler.setup(n_live_points=CONFIG['n_live_points'], sampling_efficiency=CONFIG['sampling_efficiency'], auto_clean=True)
        bayes.sample()

        fig_spec = plot_spectra(
            bayes.results,
            ene_min=1.0, ene_max=1e5, num_ene=200,
            contour_colors='white', contour_style_kwargs=dict(alpha=0.2),
            use_components=True, components_to_use=['total'],
            flux_unit='keV2/(cm2 s keV)',
        )
        ax = plt.gca()
        ax.set_xlabel('Energy (keV)', fontsize=16)
        ax.set_ylabel(r'$\nu\,F_\nu\;[\mathrm{keV\,cm^{-2}\,s^{-1}}]$', fontsize=16)
        ax.set_title(f"{CONFIG['trigger_name']}  bin {i+1}/{n_bins}  [{bb_starts[i]:.3f}, {bb_stops[i]:.3f}] s", fontsize=13)
        fig_spec.savefig(os.path.join(MODEL_PATHS['spectra'], f'cutoffbb_spec_bin{i+1:03d}.png'), dpi=120, bbox_inches='tight')
        plt.close('all')

        fig_corner = bayes.results.corner_plot()
        fig_corner.savefig(os.path.join(MODEL_PATHS['corners'], f'cutoffbb_corner_bin{i+1:03d}.png'), dpi=100, bbox_inches='tight')
        plt.close('all')

        flux_df = bayes.results.get_point_source_flux(10 * u.keV, 10 * u.MeV)
        log.info('  10 keV-10 MeV flux = %s', flux_df)
        f_val = flux_df['flux'].iloc[0].value
        f_low = flux_df['low bound'].iloc[0].value
        f_hi  = flux_df['hi bound'].iloc[0].value

        df  = bayes.results.get_data_frame('equal tail')
        df  = df.drop('unit', axis=1, errors='ignore')
        param_array = df.to_numpy().flatten()

        stat_df = bayes.results.get_statistic_measure_frame()
        dic_val = stat_df.loc['DIC'].iloc[0] if 'DIC' in stat_df.index else np.nan
        pdic_val = stat_df.loc['PDIC'].iloc[0] if 'PDIC' in stat_df.index else np.nan
        bic_val = stat_df.loc['BIC'].iloc[0] if 'BIC' in stat_df.index else np.nan

        full_row = np.append(param_array, [f_val, f_low, f_hi, dic_val, pdic_val, bic_val])
        fit_rows.append(full_row)
        log.info('  Bin %d / %d complete.', i + 1, n_bins)

    print(f'\nAll {n_bins} bins fitted successfully.')

17:31:55  INFO      ==== Time bin 1 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -2473.1489131394505      +/-   2.9951617143330767E-002
 Total Likelihood Evaluations:        11678
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(0.001 +0.004 +5) x 10^-3,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,-1.22 -0.27 +0.7,
GBM.spectrum.main.composite.xc_1,(4.5 -3.0 +0.8) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.001 +0.004 +7) x 10^-6,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -5 +7,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval0      -613.994954
n7_interval0      -618.854515
n8_interval0      -610.021690
b1_interval0      -529.730812
total            -2372.601971

Values of statistical measures:

        statistical measures
AIC              4755.329728
BIC              4776.104025
DIC              4881.650772
PDIC              -35.374853
log(Z)          -1074.074926

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

17:32:13  WARNING   Too few points to create valid contours

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:32:13  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.904814110939565e-10 erg / (s cm2)

                                       low bound  \
GBM: total  1.2847383236381941e-11 erg / (s cm2)

                                       hi bound
GBM: total  5.178831437736482e-09 erg / (s cm2)
17:32:13  INFO        Bin 1 / 72 complete.
17:32:13  INFO      ==== Time bin 2 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -2642.6820787702259      +/-   8.8724045871289056E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        31914
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(4.7 -1.2 +1.5) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-8.8 -0.7 +0.8) x 10^-1,
GBM.spectrum.main.composite.xc_1,(3.8 +/- 0.8) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0005 +1.7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8 -5 +8,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval1      -679.976660
n7_interval1      -674.052094
n8_interval1      -674.734532
b1_interval1      -556.198364
total            -2584.961651

Values of statistical measures:

        statistical measures
AIC              5180.049088
BIC              5200.823385
DIC              5236.769892
PDIC              -20.857094
log(Z)          -1147.702244

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:32:43  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.367069976205045e-07 erg / (s cm2)

                                      low bound  \
GBM: total  4.912788590433853e-07 erg / (s cm2)

                                       hi bound
GBM: total  5.916434167340433e-07 erg / (s cm2)
17:32:43  INFO        Bin 2 / 72 complete.
17:32:43  INFO      ==== Time bin 3 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1744.4416932360893      +/-   9.5975955902672300E-002
 Total Likelihood Evaluations:        44621
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(6.5 -2.2 +2.1) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-7.5 -1.1 +0.6) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.66 -0.09 +1.4) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.000 +0.004 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(0.89 -0.25 +1.4) x 10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval2      -453.537863
n7_interval2      -457.920527
n8_interval2      -449.491780
b1_interval2      -327.179630
total            -1688.129800

Values of statistical measures:

        statistical measures
AIC              3386.385387
BIC              3407.159684
DIC              3451.129361
PDIC              -13.511032
log(Z)           -757.601401

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:33:20  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.0897750320011458e-06 erg / (s cm2)

                                      low bound  \
GBM: total  9.992187398736287e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.2016029514640685e-06 erg / (s cm2)
17:33:20  INFO        Bin 3 / 72 complete.
17:33:20  INFO      ==== Time bin 4 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2324.1179320276710      +/-   9.2811489075610890E-002
 Total Likelihood Evaluations:        40906
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(7.5 -2.4 +2.0) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-8.6 -0.7 +1.0) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.24 -0.34 +0.5) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +6 +1.0) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.27 -0.8 +0.28) x 10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval3      -591.986680
n7_interval3      -598.287121
n8_interval3      -594.215378
b1_interval3      -483.400689
total            -2267.889868

Values of statistical measures:

        statistical measures
AIC              4545.905522
BIC              4566.679819
DIC              4598.361242
PDIC              -22.939843
log(Z)          -1009.351593

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:33:55  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.415642757410362e-07 erg / (s cm2)

                                      low bound  \
GBM: total  5.079752742478708e-07 erg / (s cm2)

                                       hi bound
GBM: total  5.793686916884387e-07 erg / (s cm2)
17:33:55  INFO        Bin 4 / 72 complete.
17:33:55  INFO      ==== Time bin 5 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1622.5922622791311      +/-   9.2050706452738273E-002
 Total Likelihood Evaluations:        38575
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.36 -0.13 +0.7,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-8.59 -1.3 +0.21) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.25 -0.08 +1.0) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0010 +7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,10 -5 +9,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval4      -425.240825
n7_interval4      -431.693886
n8_interval4      -429.748650
b1_interval4      -281.930913
total            -1568.614273

Values of statistical measures:

        statistical measures
AIC              3147.354332
BIC              3168.128629
DIC              3211.106115
PDIC              -10.255047
log(Z)           -704.682866

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:34:30  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.0061043377410174e-06 erg / (s cm2)

                                      low bound  \
GBM: total  9.333973268059504e-07 erg / (s cm2)

                                       hi bound
GBM: total  1.095858900751281e-06 erg / (s cm2)
17:34:30  INFO        Bin 5 / 72 complete.
17:34:30  INFO      ==== Time bin 6 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1360.3495702520154      +/-   9.3748129093835897E-002
 Total Likelihood Evaluations:        40621
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.7 +/- 0.4,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-8.2 +/- 0.6) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.9 +/- 0.4) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0008 +7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(0.70 -0.25 +1.1) x 10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval5      -372.366059
n7_interval5      -363.354869
n8_interval5      -351.664706
b1_interval5      -219.559184
total            -1306.944818

Values of statistical measures:

        statistical measures
AIC              2624.015423
BIC              2644.789720
DIC              2687.333541
PDIC               -8.340422
log(Z)           -590.792312

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:35:05  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.9607359569171517e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.8551605112404852e-06 erg / (s cm2)

                                        hi bound
GBM: total  2.0758741325434873e-06 erg / (s cm2)
17:35:05  INFO        Bin 6 / 72 complete.
17:35:05  INFO      ==== Time bin 7 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -677.49815023755627      +/-   9.4153394556033443E-002
 Total Likelihood Evaluations:        37361
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(9.9 -1.4 +5) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-5.8 -1.2 +0.4) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.09 -0.16 +0.5) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8 -4 +9,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval6      -184.544041
n7_interval6      -198.408768
n8_interval6      -199.364920
b1_interval6       -40.679142
total             -622.996871

Values of statistical measures:

        statistical measures
AIC              1256.119528
BIC              1276.893825
DIC              1317.120780
PDIC              -11.947985
log(Z)           -294.233708

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:35:39  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.7199421157470873e-06 erg / (s cm2)

                                      low bound  \
GBM: total  2.554320520160611e-06 erg / (s cm2)

                                        hi bound
GBM: total  2.9039642736217526e-06 erg / (s cm2)
17:35:39  INFO        Bin 7 / 72 complete.
17:35:39  INFO      ==== Time bin 8 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -1580.9233851626957      +/-  0.11203830193807635
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        60064
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,2.18 -0.06 +1.4,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-8.9 -2.4 -0.8) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.2 +0.9 +3.1) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0 +4 +9) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(0.7 +1.3 +1.8) x 10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval7      -418.059524
n7_interval7      -425.237926
n8_interval7      -417.020668
b1_interval7      -272.748357
total            -1533.066475

Values of statistical measures:

        statistical measures
AIC              3076.258736
BIC              3097.033033
DIC              3138.936646
PDIC               -2.321443
log(Z)           -686.586302

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:36:19  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.4462314778507086e-06 erg / (s cm2)

                                      low bound  \
GBM: total  1.340299286395476e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.5707400084793526e-06 erg / (s cm2)
17:36:19  INFO        Bin 8 / 72 complete.
17:36:19  INFO      ==== Time bin 9 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -316.64798224159870      +/-   8.6693214086449435E-002
 Total Likelihood Evaluations:        32959
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.8 -0.4 +0.7,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-7.8 -0.9 +0.6) x 10^-1,
GBM.spectrum.main.composite.xc_1,(3.57 -0.32 +1.2) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +9 +1.0) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8 -4 +9,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval8      -105.181149
n7_interval8      -110.635544
n8_interval8      -107.313173
b1_interval8        57.604891
total             -265.524976

Values of statistical measures:

        statistical measures
AIC               541.175738
BIC               561.950035
DIC               601.691673
PDIC               -9.987249
log(Z)           -137.518471

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:36:50  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  3.6573634905224582e-06 erg / (s cm2)

                                       low bound  \
GBM: total  3.3341053220359456e-06 erg / (s cm2)

                                        hi bound
GBM: total  4.0239501796705474e-06 erg / (s cm2)
17:36:50  INFO        Bin 9 / 72 complete.
17:36:50  INFO      ==== Time bin 10 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1349.7189551942583      +/-  0.11233372817485006
 Total Likelihood Evaluations:        62438
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.64 -0.21 +0.30,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-6.15 -0.8 +0.20) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.486 -0.022 +0.8) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.000 +0.006 +7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.07 -0.35 +1.7) x 10,keV

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval9      -364.635289
n7_interval9      -381.076282
n8_interval9      -353.407495
b1_interval9      -196.250535
total            -1295.369602

Values of statistical measures:

        statistical measures
AIC              2600.864989
BIC              2621.639286
DIC              2669.022038
PDIC               -3.757579
log(Z)           -586.175494

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:37:34  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.011768644452187e-06 erg / (s cm2)

                                      low bound  \
GBM: total  4.813274748285494e-06 erg / (s cm2)

                                       hi bound
GBM: total  5.253474390288267e-06 erg / (s cm2)
17:37:34  INFO        Bin 10 / 72 complete.
17:37:34  INFO      ==== Time bin 11 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -1158.0784311116618      +/-   9.4804951728214917E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        42829
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,3.3 +/- 0.6,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-9.1 +/- 0.6) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.86 -0.31 +0.6) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.2 +/- 0.7) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval10      -301.878239
n7_interval10      -313.705002
n8_interval10      -313.900919
b1_interval10      -177.222959
total             -1106.707118

Values of statistical measures:

        statistical measures
AIC              2223.540023
BIC              2244.314320
DIC              2281.977524
PDIC               -9.774742
log(Z)           -502.947072

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:38:10  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.3845303303139798e-06 erg / (s cm2)

                                      low bound  \
GBM: total  2.248923372218166e-06 erg / (s cm2)

                                      hi bound
GBM: total  2.54416666233487e-06 erg / (s cm2)
17:38:10  INFO        Bin 11 / 72 complete.
17:38:10  INFO      ==== Time bin 12 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -413.93643597898131      +/-   9.2833844928669418E-002
 Total Likelihood Evaluations:        34531
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.95 -0.31 +0.6,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-6.9 -0.7 +0.5) x 10^-1,
GBM.spectrum.main.composite.xc_1,(3.47 -0.31 +0.6) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0006 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.35 -0.9 +0.31) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval11      -145.382966
n7_interval11      -140.774069
n8_interval11      -132.468113
b1_interval11        56.715167
total              -361.909980

Values of statistical measures:

        statistical measures
AIC               733.945747
BIC               754.720044
DIC               793.062201
PDIC              -10.040923
log(Z)           -179.770310

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:38:40  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  6.17466388179974e-06 erg / (s cm2)

                                       low bound  \
GBM: total  5.7950928830988245e-06 erg / (s cm2)

                                      hi bound
GBM: total  6.60887407486531e-06 erg / (s cm2)
17:38:40  INFO        Bin 12 / 72 complete.
17:38:40  INFO      ==== Time bin 13 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -1072.9019728708511      +/-  0.10289818061666225
 Total Likelihood Evaluations:        44300
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.68 -0.18 +0.24,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-5.89 -0.4 +0.26) x 10^-1,
GBM.spectrum.main.composite.xc_1,(3.80 -0.12 +0.4) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0005 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8 -4 +9,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval12      -297.994565
n7_interval12      -300.581230
n8_interval12      -309.034895
b1_interval12      -111.060810
total             -1018.671500

Values of statistical measures:

        statistical measures
AIC              2047.468787
BIC              2068.243084
DIC              2108.354466
PDIC               -8.493992
log(Z)           -465.955406

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:39:13  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.0661639358687128e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.0330716856629583e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.1007508251718071e-05 erg / (s cm2)
17:39:13  INFO        Bin 13 / 72 complete.
17:39:13  INFO      ==== Time bin 14 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -869.38576613802468      +/-  0.10309471253350569
 Total Likelihood Evaluations:        44596
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,2.39 -0.28 +0.33,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-6.26 -0.35 +0.27) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.42 -0.16 +0.4) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +8) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -4 +9,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval13      -268.525201
n7_interval13      -255.623478
n8_interval13      -245.902542
b1_interval13       -47.217238
total              -817.268459

Values of statistical measures:

        statistical measures
AIC              1644.662704
BIC              1665.437001
DIC              1704.864866
PDIC               -6.746026
log(Z)           -377.569441

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:39:49  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.490826091576209e-05 erg / (s cm2)

                                     low bound  \
GBM: total  1.43922405828331e-05 erg / (s cm2)

                                      hi bound
GBM: total  1.54255233529154e-05 erg / (s cm2)
17:39:49  INFO        Bin 14 / 72 complete.
17:39:49  INFO      ==== Time bin 15 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -955.64089876192406      +/-  0.10238988142579841
 Total Likelihood Evaluations:        42818
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.55 -0.11 +0.4,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-5.61 -0.6 +0.19) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.97 -0.10 +0.33) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +4) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.7 +0.6) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval14      -258.508909
n7_interval14      -286.192037
n8_interval14      -271.579349
b1_interval14       -84.933850
total              -901.214145

Values of statistical measures:

        statistical measures
AIC              1812.554076
BIC              1833.328373
DIC              1873.695252
PDIC               -8.703773
log(Z)           -415.029569

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:40:23  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  7.993562097387664e-06 erg / (s cm2)

                                      low bound  \
GBM: total  7.730684741088587e-06 erg / (s cm2)

                                       hi bound
GBM: total  8.282388966783329e-06 erg / (s cm2)
17:40:23  INFO        Bin 15 / 72 complete.
17:40:23  INFO      ==== Time bin 16 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -152.97392943587886      +/-   9.7473146730488333E-002
 Total Likelihood Evaluations:        46801
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,2.0 +/- 0.4,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-5.6 +/- 0.5) x 10^-1,
GBM.spectrum.main.composite.xc_1,(3.95 -0.28 +0.6) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.00001 +0.00010 +1.1) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(0.9 -0.5 +1.0) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval15       -69.788055
n7_interval15       -89.173183
n8_interval15       -68.107581
b1_interval15       125.690849
total              -101.377971

Values of statistical measures:

        statistical measures
AIC               212.881728
BIC               233.656025
DIC               273.281485
PDIC               -8.239268
log(Z)            -66.435733

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:41:01  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.5395045780916456e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.4529158819405282e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.6298779624070324e-05 erg / (s cm2)
17:41:01  INFO        Bin 16 / 72 complete.
17:41:01  INFO      ==== Time bin 17 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -848.01744710442767      +/-  0.11185730686411910
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        54521
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,2.41 -1.2 -0.05,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-6.63 -0.21 +1.2) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.89 -0.06 +0.6) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +0.7 +4) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.11 +0.35 +1.0) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval16      -240.986373
n7_interval16      -257.236790
n8_interval16      -238.009674
b1_interval16       -60.830104
total              -797.062941

Values of statistical measures:

        statistical measures
AIC              1604.251668
BIC              1625.025965
DIC              1668.079330
PDIC               -5.820012
log(Z)           -368.289298

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:41:42  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.995444376571412e-06 erg / (s cm2)

                                      low bound  \
GBM: total  6.710956434622381e-06 erg / (s cm2)

                                       hi bound
GBM: total  7.304396757873999e-06 erg / (s cm2)
17:41:42  INFO        Bin 17 / 72 complete.
17:41:42  INFO      ==== Time bin 18 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -261.63428860787650      +/-   9.7466950322436949E-002
 Total Likelihood Evaluations:        45195
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.43 -0.18 +0.4,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-4.96 -0.7 +0.27) x 10^-1,
GBM.spectrum.main.composite.xc_1,(3.27 -0.10 +0.5) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -5 +9,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval17       -96.751919
n7_interval17      -104.552048
n8_interval17      -118.070520
b1_interval17       110.908549
total              -208.465938

Values of statistical measures:

        statistical measures
AIC               427.057663
BIC               447.831960
DIC               488.658384
PDIC               -8.430404
log(Z)           -113.626328

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:42:19  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2461343275759943e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.1865759307272388e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.3106065797523786e-05 erg / (s cm2)
17:42:19  INFO        Bin 18 / 72 complete.
17:42:19  INFO      ==== Time bin 19 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1283.1199832701070      +/-  0.11245730262961076
 Total Likelihood Evaluations:        76784
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.85 -0.27 +0.10,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-4.88 -0.14 +0.31) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.00 -0.17 +0.14) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0012 +7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +1.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval18      -365.316437
n7_interval18      -356.664445
n8_interval18      -366.022888
b1_interval18      -141.139208
total             -1229.142979

Values of statistical measures:

        statistical measures
AIC              2468.411743
BIC              2489.186041
DIC              2530.580316
PDIC               -6.115632
log(Z)           -557.251928

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:43:06  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.2530165323965536e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.2072543608548995e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.3010582888300484e-05 erg / (s cm2)
17:43:06  INFO        Bin 19 / 72 complete.
17:43:06  INFO      ==== Time bin 20 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -508.59318465210276      +/-  0.10582717045560862
 Total Likelihood Evaluations:        53074
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,2.32 -0.5 +0.30,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-5.4 -0.4 +0.5) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.46 -0.09 +0.29) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.00001 +0.00017 +1.7) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +1.1) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval19      -158.906312
n7_interval19      -177.234885
n8_interval19      -170.202249
b1_interval19        50.438417
total              -455.905030

Values of statistical measures:

        statistical measures
AIC               921.935846
BIC               942.710143
DIC               985.953093
PDIC               -5.595946
log(Z)           -220.879214

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:43:45  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.0621152993239892e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.0286671006268506e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.0993019235296259e-05 erg / (s cm2)
17:43:45  INFO        Bin 20 / 72 complete.
17:43:45  INFO      ==== Time bin 21 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -701.88181031746171      +/-  0.10716283950668135
 Total Likelihood Evaluations:        44488
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,2.04 -0.24 +0.21,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-4.67 -0.26 +0.28) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.02 -0.18 +0.21) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0006 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 -0.6 +0.7) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval20      -218.422952
n7_interval20      -218.593608
n8_interval20      -222.342640
b1_interval20        11.094151
total              -648.265050

Values of statistical measures:

        statistical measures
AIC              1306.655885
BIC              1327.430182
DIC              1366.252941
PDIC               -7.889698
log(Z)           -304.823397

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:44:21  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.8476618487751926e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.7727359901512398e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.9247361743449177e-05 erg / (s cm2)
17:44:21  INFO        Bin 21 / 72 complete.
17:44:21  INFO      ==== Time bin 22 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -4.3227434445147779      +/-  0.10353392535729632
 Total Likelihood Evaluations:        46597
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.62 -0.16 +0.4,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-3.58 -0.5 +0.23) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.30 -0.17 +0.4) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0009 +7) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.45 -1.0 +0.27) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval21       -46.573526
n7_interval21       -45.585641
n8_interval21       -38.531113
b1_interval21       177.810536
total                47.120256

Values of statistical measures:

        statistical measures
AIC               -84.114726
BIC               -63.340429
DIC               -26.588395
PDIC               -8.038009
log(Z)             -1.877344

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:44:59  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  4.9282693310760914e-05 erg / (s cm2)

                                      low bound  \
GBM: total  4.749090706420539e-05 erg / (s cm2)

                                       hi bound
GBM: total  5.108734728260429e-05 erg / (s cm2)
17:44:59  INFO        Bin 22 / 72 complete.
17:44:59  INFO      ==== Time bin 23 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -779.94729975774419      +/-  0.11319372995794562
 Total Likelihood Evaluations:        50323
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.85 -0.13 +0.18,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-3.18 -0.21 +0.17) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.15 -0.12 +0.14) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.7 +0.6) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval22      -241.150642
n7_interval22      -247.325864
n8_interval22      -235.420472
b1_interval22        -2.469694
total              -726.366673

Values of statistical measures:

        statistical measures
AIC              1462.859132
BIC              1483.633429
DIC              1520.040998
PDIC               -8.198510
log(Z)           -338.726808

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:45:35  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  6.80765138496737e-05 erg / (s cm2)

                                     low bound  \
GBM: total  6.68214385368836e-05 erg / (s cm2)

                                       hi bound
GBM: total  6.937171887270313e-05 erg / (s cm2)
17:45:35  INFO        Bin 23 / 72 complete.
17:45:35  INFO      ==== Time bin 24 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=   254.20213135679364      +/-  0.10081069205544713
 Total Likelihood Evaluations:        40447
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,2.7 -0.4 +0.6,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-4.3 +/- 0.5) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.74 -0.22 +0.18) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +7 +1.1) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,10 -6 +7,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval23        29.410593
n7_interval23         7.123555
n8_interval23        30.544690
b1_interval23       238.171242
total               305.250079

Values of statistical measures:

        statistical measures
AIC              -600.374372
BIC              -579.600075
DIC              -543.037046
PDIC               -8.921034
log(Z)            110.398583

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:46:08  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.609732312770186e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.5076639909152405e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.7133798919754967e-05 erg / (s cm2)
17:46:08  INFO        Bin 24 / 72 complete.
17:46:08  INFO      ==== Time bin 25 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   23.185763265642009      +/-  0.10419210984891064
 Total Likelihood Evaluations:        44451
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,2.1 -0.4 +0.5,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-3.9 -0.6 +0.5) x 10^-1,
GBM.spectrum.main.composite.xc_1,(1.74 -0.09 +0.18) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +9 +1.1) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8 -4 +10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval24       -42.359946
n7_interval24       -37.897274
n8_interval24       -32.926274
b1_interval24       187.892321
total                74.708827

Values of statistical measures:

        statistical measures
AIC              -139.291869
BIC              -118.517571
DIC               -81.734253
PDIC               -8.643338
log(Z)             10.069449

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:46:45  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2363997392936672e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.1937365924348606e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.2820480507968602e-05 erg / (s cm2)
17:46:45  INFO        Bin 25 / 72 complete.
17:46:45  INFO      ==== Time bin 26 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   86.187484018670645      +/-   9.6010725040021450E-002
 Total Likelihood Evaluations:        37441
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,5.4 -0.6 +2.2,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-7.24 -1.1 +0.28) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.17 -0.07 +0.6) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +2.0) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.4 -0.9 +0.5) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval25       -17.053240
n7_interval25       -32.829756
n8_interval25       -10.547894
b1_interval25       194.600076
total               134.169187

Values of statistical measures:

        statistical measures
AIC              -258.212587
BIC              -237.438290
DIC              -201.082756
PDIC               -7.111892
log(Z)             37.430749

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:47:21  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  7.68324354271331e-06 erg / (s cm2)

                                      low bound  \
GBM: total  7.282125310248191e-06 erg / (s cm2)

                                      hi bound
GBM: total  8.14016761789654e-06 erg / (s cm2)
17:47:21  INFO        Bin 26 / 72 complete.
17:47:21  INFO      ==== Time bin 27 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -414.37491086230949      +/-   9.6403348141795464E-002
 Total Likelihood Evaluations:        42582
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,6.4 -1.6 +1.0,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-8.4 -0.5 +0.7) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.01 -0.18 +0.32) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.00001 +0.00012 +2.3) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 -0.5 +0.7) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval26      -117.384501
n7_interval26      -151.488389
n8_interval26      -149.320997
b1_interval26        51.361327
total              -366.832560

Values of statistical measures:

        statistical measures
AIC               743.790906
BIC               764.565203
DIC               800.113028
PDIC               -6.709906
log(Z)           -179.960737

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:47:57  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.394621976415406e-06 erg / (s cm2)

                                      low bound  \
GBM: total  4.203140915763763e-06 erg / (s cm2)

                                       hi bound
GBM: total  4.612487490835567e-06 erg / (s cm2)
17:47:57  INFO        Bin 27 / 72 complete.
17:47:57  INFO      ==== Time bin 28 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -388.69480398921161      +/-   9.8543956733275817E-002
 Total Likelihood Evaluations:        37573
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,3.1 -0.5 +0.6,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-6.5 +/- 0.5) x 10^-1,
GBM.spectrum.main.composite.xc_1,(3.03 -0.26 +0.32) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.40 -1.0 +0.27) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval27      -129.888828
n7_interval27      -139.741827
n8_interval27      -127.312482
b1_interval27        59.750958
total              -337.192179

Values of statistical measures:

        statistical measures
AIC               684.510143
BIC               705.284440
DIC               741.398319
PDIC              -10.054759
log(Z)           -168.808009

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:48:29  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.0080775426301457e-05 erg / (s cm2)

                                    low bound  \
GBM: total  9.6599069892237e-06 erg / (s cm2)

                                       hi bound
GBM: total  1.055108176625763e-05 erg / (s cm2)
17:48:29  INFO        Bin 28 / 72 complete.
17:48:29  INFO      ==== Time bin 29 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -87.278270647481818      +/-  0.10458185706726006
 Total Likelihood Evaluations:        50233
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,3.08 -0.29 +0.6,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-5.42 -0.4 +0.20) x 10^-1,
GBM.spectrum.main.composite.xc_1,(6.04 -0.25 +0.6) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.3 -0.9 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval28       -64.573735
n7_interval28       -55.932247
n8_interval28       -66.784597
b1_interval28       147.047279
total               -40.243300

Values of statistical measures:

        statistical measures
AIC                90.612386
BIC               111.386683
DIC               141.786681
PDIC               -7.502322
log(Z)            -37.904471

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:49:07  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.993777847574728e-05 erg / (s cm2)

                                      low bound  \
GBM: total  4.791791576244954e-05 erg / (s cm2)

                                        hi bound
GBM: total  5.2160035126362216e-05 erg / (s cm2)
17:49:07  INFO        Bin 29 / 72 complete.
17:49:07  INFO      ==== Time bin 30 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   51.355523123554114      +/-  0.10580973100527193
 Total Likelihood Evaluations:        44022
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.79 -0.07 +0.5,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-2.88 -0.6 +0.11) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.01 -0.11 +0.35) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -5 +8,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval29       -29.857001
n7_interval29       -42.804784
n8_interval29       -39.678628
b1_interval29       215.125691
total               102.785278

Values of statistical measures:

        statistical measures
AIC              -195.444769
BIC              -174.670472
DIC              -138.463168
PDIC               -7.683434
log(Z)             22.303420

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:49:43  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  7.503464936005035e-05 erg / (s cm2)

                                      low bound  \
GBM: total  7.266376105821472e-05 erg / (s cm2)

                                       hi bound
GBM: total  7.743018674995344e-05 erg / (s cm2)
17:49:43  INFO        Bin 30 / 72 complete.
17:49:43  INFO      ==== Time bin 31 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=   171.44246907317697      +/-  0.10722441976005810
 Total Likelihood Evaluations:        60869
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,2.48 -0.26 +0.5,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-3.23 -0.4 +0.26) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.98 -0.26 +0.29) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0006 +8) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,10 -6 +8,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval30         7.023723
n7_interval30         5.235849
n8_interval30         0.443285
b1_interval30       208.632239
total               221.335096

Values of statistical measures:

        statistical measures
AIC              -432.544406
BIC              -411.770109
DIC              -378.222469
PDIC               -8.055506
log(Z)             74.456518

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:50:27  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  0.00011935131834875258 erg / (s cm2)

                                      low bound  \
GBM: total  0.0001155779018097151 erg / (s cm2)

                                        hi bound
GBM: total  0.00012332146301074926 erg / (s cm2)
17:50:27  INFO        Bin 31 / 72 complete.
17:50:27  INFO      ==== Time bin 32 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -438.99760655956248      +/-  0.15849210464959959
 Total Likelihood Evaluations:        81571

 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,3.8 -0.4 +0.5,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-4.83 -0.14 +0.29) x 10^-1,
GBM.spectrum.main.composite.xc_1,(5.947 -0.4 +0.026) x 10^2,keV
GBM.spectrum.main.composite.K_2,(1.53 -0.26 +0.6) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(3.9734 -0.5 +0.0025) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval31      -130.338752
n7_interval31      -168.870211
n8_interval31      -140.567947
b1_interval31       -18.918138
total              -458.695048

Values of statistical measures:

        statistical measures
AIC               927.515882
BIC               948.290179
DIC               851.917119
PDIC                2.400417
log(Z)           -190.654238

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:51:24  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  9.098170306138086e-05 erg / (s cm2)

                                      low bound  \
GBM: total  8.884492992915506e-05 erg / (s cm2)

                                       hi bound
GBM: total  9.326620546859534e-05 erg / (s cm2)
17:51:24  INFO        Bin 32 / 72 complete.
17:51:24  INFO      ==== Time bin 33 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=   431.35319593276864      +/-   9.9513682408552129E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        45770
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,3.2 -0.5 +0.9,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-4.5 -0.6 +0.5) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.61 -0.17 +0.27) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +9 +1.9) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.3 -0.9 +0.5) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval32        50.823891
n7_interval32        64.103163
n8_interval32        59.619538
b1_interval32       306.309812
total               480.856404

Values of statistical measures:

        statistical measures
AIC              -951.587022
BIC              -930.812725
DIC              -894.666219
PDIC               -8.040991
log(Z)            187.334313

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:52:00  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.5636007103997288e-05 erg / (s cm2)

                                      low bound  \
GBM: total  2.454286489633746e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.6738939379023333e-05 erg / (s cm2)
17:52:00  INFO        Bin 33 / 72 complete.
17:52:00  INFO      ==== Time bin 34 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -692.41710138456165      +/-  0.11930891199864230
 Total Likelihood Evaluations:        54992
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,5.2 -2.1 -0.4,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-6.41 -0.10 +0.9) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.76 -0.11 +0.35) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +1.7 +7) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(0.6 +0.9 +1.6) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval33      -207.214484
n7_interval33      -227.169167
n8_interval33      -221.182652
b1_interval33         8.281981
total              -647.284322

Values of statistical measures:

        statistical measures
AIC              1304.694431
BIC              1325.468728
DIC              1360.809708
PDIC               -2.381151
log(Z)           -300.712926

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:52:41  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.5549650931260122e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.5121866054643653e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.600892458420834e-05 erg / (s cm2)
17:52:41  INFO        Bin 34 / 72 complete.
17:52:41  INFO      ==== Time bin 35 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -728.46856365544568      +/-  0.11372918950655021
 Total Likelihood Evaluations:        55260
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,8.61 -4 -0.30,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-8.9 -0.4 +0.9) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.662 +0.017 +0.9) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.00 +0.34 +1.1) x 10^-3,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(0.3 +1.1 +1.6) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval34      -218.969423
n7_interval34      -234.424081
n8_interval34      -221.110162
b1_interval34       -13.704187
total              -688.207852

Values of statistical measures:

        statistical measures
AIC              1386.541491
BIC              1407.315788
DIC              1429.929631
PDIC               -9.129012
log(Z)           -316.369877

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:53:20  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.640587008376743e-06 erg / (s cm2)

                                      low bound  \
GBM: total  6.362140278374291e-06 erg / (s cm2)

                                       hi bound
GBM: total  6.930827414786098e-06 erg / (s cm2)
17:53:20  INFO        Bin 35 / 72 complete.
17:53:20  INFO      ==== Time bin 36 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -649.27354056716194      +/-  0.10757423177128521
 Total Likelihood Evaluations:        48795
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,6.5 -1.8 +1.5,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-8.76 -1.1 +0.30) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.38 +0.19 +1.3) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +1.5 +6) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.20 +0.12 +0.7) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval35      -201.756411
n7_interval35      -208.712954
n8_interval35      -187.655952
b1_interval35        -5.029254
total              -603.154572

Values of statistical measures:

        statistical measures
AIC              1216.434930
BIC              1237.209227
DIC              1278.964044
PDIC               -2.436089
log(Z)           -281.975916

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:53:58  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.826870366638697e-06 erg / (s cm2)

                                       low bound  \
GBM: total  4.5645745430064095e-06 erg / (s cm2)

                                       hi bound
GBM: total  5.107557690673876e-06 erg / (s cm2)
17:53:58  INFO        Bin 36 / 72 complete.
17:53:58  INFO      ==== Time bin 37 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -443.81102091586172      +/-  0.10303328482318870
 Total Likelihood Evaluations:        47464
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,4.6 -1.9 +0.5,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-7.16 -0.31 +1.0) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.07 -0.34 +0.4) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0000 +0.0008 +8) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.3 -0.6 +0.5) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval36      -150.183806
n7_interval36      -147.542527
n8_interval36      -159.874408
b1_interval36        62.655503
total              -394.945238

Values of statistical measures:

        statistical measures
AIC               800.016263
BIC               820.790560
DIC               858.058052
PDIC               -9.202774
log(Z)           -192.744677

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:54:36  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.5039391921234425e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.4411676606007248e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.5720247454359533e-05 erg / (s cm2)
17:54:36  INFO        Bin 37 / 72 complete.
17:54:36  INFO      ==== Time bin 38 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -526.43853247685172      +/-  0.10824615782023198
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        62066
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,4.1 -0.6 +0.4,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-6.18 -0.28 +0.33) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.39 -0.20 +0.5) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +1.0) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 -0.5 +1.7) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval37      -167.930545
n7_interval37      -182.268231
n8_interval37      -178.010179
b1_interval37        51.921649
total              -476.287306

Values of statistical measures:

        statistical measures
AIC               962.700398
BIC               983.474695
DIC              1019.846976
PDIC               -7.639553
log(Z)           -228.629350

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:55:22  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.664782951829496e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.5735590812790835e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.7702078629527433e-05 erg / (s cm2)
17:55:22  INFO        Bin 38 / 72 complete.
17:55:22  INFO      ==== Time bin 39 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -785.15440091226594      +/-  0.10951779543718700
 Total Likelihood Evaluations:        44267
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,4.13 -0.5 +0.13,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-5.69 -0.08 +0.33) x 10^-1,
GBM.spectrum.main.composite.xc_1,(5.05 -0.34 +0.08) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0008 +5) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8 -4 +9,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval38      -238.183717
n7_interval38      -254.375104
n8_interval38      -230.563128
b1_interval38       -12.450983
total              -735.572933

Values of statistical measures:

        statistical measures
AIC              1481.271652
BIC              1502.045949
DIC              1533.096550
PDIC               -8.208075
log(Z)           -340.988224

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:55:56  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.266368502969141e-05 erg / (s cm2)

                                      low bound  \
GBM: total  4.158762788740034e-05 erg / (s cm2)

                                        hi bound
GBM: total  4.3735656895195676e-05 erg / (s cm2)
17:55:56  INFO        Bin 39 / 72 complete.
17:55:56  INFO      ==== Time bin 40 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -249.11741909337184      +/-  0.10642490171988482
 Total Likelihood Evaluations:        48348
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,3.26 -0.25 +0.5,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-4.74 -0.32 +0.20) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.87 -0.23 +0.26) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.2 -0.8 +0.5) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval39      -107.037837
n7_interval39      -119.109158
n8_interval39      -109.169685
b1_interval39       136.489585
total              -198.827094

Values of statistical measures:

        statistical measures
AIC               407.779974
BIC               428.554271
DIC               463.000754
PDIC               -7.694828
log(Z)           -108.190320

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:56:34  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.815196451104388e-05 erg / (s cm2)

                                      low bound  \
GBM: total  5.646732533443249e-05 erg / (s cm2)

                                      hi bound
GBM: total  5.99069524762837e-05 erg / (s cm2)
17:56:34  INFO        Bin 40 / 72 complete.
17:56:34  INFO      ==== Time bin 41 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -638.78337389543958      +/-  0.11205675080974405
 Total Likelihood Evaluations:        44758
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,3.14 -0.29 +0.24,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-3.91 -0.19 +0.22) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.42 -0.12 +0.19) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.3 -0.9 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval40      -196.114997
n7_interval40      -204.725425
n8_interval40      -204.773711
b1_interval40        17.861036
total              -587.753096

Values of statistical measures:

        statistical measures
AIC              1185.631979
BIC              1206.406276
DIC              1239.935335
PDIC               -7.499227
log(Z)           -277.420094

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:57:09  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.231538011199532e-05 erg / (s cm2)

                                      low bound  \
GBM: total  8.068573199814904e-05 erg / (s cm2)

                                       hi bound
GBM: total  8.396998070877686e-05 erg / (s cm2)
17:57:09  INFO        Bin 41 / 72 complete.
17:57:09  INFO      ==== Time bin 42 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=   129.93161203873004      +/-  0.10334163763910345
 Total Likelihood Evaluations:        43927
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,3.6 -0.4 +0.7,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-4.26 -0.4 +0.29) x 10^-1,
GBM.spectrum.main.composite.xc_1,(3.28 -0.11 +0.30) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +7 +1.6) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -4 +9,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval41       -12.020594
n7_interval41       -28.126838
n8_interval41       -14.632360
b1_interval41       235.368052
total               180.588261

Values of statistical measures:

        statistical measures
AIC              -351.050735
BIC              -330.276438
DIC              -293.023043
PDIC               -7.432005
log(Z)             56.428582

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:57:46  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  4.748859693951152e-05 erg / (s cm2)

                                       low bound  \
GBM: total  4.5994080572931946e-05 erg / (s cm2)

                                       hi bound
GBM: total  4.896464005814301e-05 erg / (s cm2)
17:57:46  INFO        Bin 42 / 72 complete.
17:57:46  INFO      ==== Time bin 43 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -38.551403665352417      +/-  0.10572813722643565
 Total Likelihood Evaluations:        50520
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,4.0 -0.8 +0.6,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-4.8 +/- 0.4) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.46 -0.11 +0.22) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.00001 +0.00021 +3.3) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(0.9 -0.4 +1.1) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval42       -51.464257
n7_interval42       -80.388843
n8_interval42       -58.556289
b1_interval42       202.269599
total                11.860210

Values of statistical measures:

        statistical measures
AIC               -13.594633
BIC                 7.179664
DIC                46.872013
PDIC               -5.940945
log(Z)            -16.742662

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:58:25  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.5045274067308475e-05 erg / (s cm2)

                                      low bound  \
GBM: total  2.428856335038428e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.583763945317903e-05 erg / (s cm2)
17:58:25  INFO        Bin 43 / 72 complete.
17:58:25  INFO      ==== Time bin 44 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -1476.1610812860204      +/-  0.13795264672719817
 Total Likelihood Evaluations:        85041
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,7.0 -0.7 +0.5,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-7.78 -0.17 +0.34) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.46 -0.4 +0.19) x 10^2,keV
GBM.spectrum.main.composite.K_2,(8.3 -1.7 +4) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(3.07 -0.4 +0.17) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval43      -416.921484
n7_interval43      -438.316942
n8_interval43      -414.764746
b1_interval43      -209.867348
total             -1479.870520

Values of statistical measures:

        statistical measures
AIC              2969.866827
BIC              2990.641124
DIC              2929.823970
PDIC                3.525111
log(Z)           -641.088612

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:59:13  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.8199040528661393e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.7809064742237794e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.8608608058736783e-05 erg / (s cm2)
17:59:13  INFO        Bin 44 / 72 complete.
17:59:13  INFO      ==== Time bin 45 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -208.91380420328272      +/-  0.10259055366765224
 Total Likelihood Evaluations:        40201
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,4.18 -0.32 +0.8,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-5.54 -0.4 +0.19) x 10^-1,
GBM.spectrum.main.composite.xc_1,(3.55 -0.16 +0.29) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +10) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,7.6 -3.5 +9,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval44      -103.766051
n7_interval44      -101.748847
n8_interval44       -93.042774
b1_interval44       139.700683
total              -158.856990

Values of statistical measures:

        statistical measures
AIC               327.839765
BIC               348.614063
DIC               383.063121
PDIC               -8.749792
log(Z)            -90.730112

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

17:59:46  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.883712490775883e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.7946496050287157e-05 erg / (s cm2)

                                       hi bound
GBM: total  2.979656902851979e-05 erg / (s cm2)
17:59:46  INFO        Bin 45 / 72 complete.
17:59:46  INFO      ==== Time bin 46 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -568.82070174492401      +/-  0.10413439584964930
 Total Likelihood Evaluations:        42141
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,5.7 -0.7 +0.6,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-6.64 -0.27 +0.34) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.82 -0.17 +0.16) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +10) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,7.1 -2.9 +10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval45      -188.763359
n7_interval45      -197.261357
n8_interval45      -183.315900
b1_interval45        50.851028
total              -518.489588

Values of statistical measures:

        statistical measures
AIC              1047.104962
BIC              1067.879259
DIC              1104.027319
PDIC               -7.245821
log(Z)           -247.035692

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:00:21  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.509850291788492e-05 erg / (s cm2)

                                       low bound  \
GBM: total  1.4689256240974976e-05 erg / (s cm2)

                                        hi bound
GBM: total  1.5542112968014464e-05 erg / (s cm2)
18:00:21  INFO        Bin 46 / 72 complete.
18:00:21  INFO      ==== Time bin 47 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -598.42069186712558      +/-  0.10186289553103317
 Total Likelihood Evaluations:        43305
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,4.1 -0.4 +0.8,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-6.46 -0.5 +0.33) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.39 -0.17 +0.18) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0007 +6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.2 -0.8 +0.5) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval46      -185.572206
n7_interval46      -194.612227
n8_interval46      -184.990439
b1_interval46        17.773979
total              -547.400893

Values of statistical measures:

        statistical measures
AIC              1104.927572
BIC              1125.701869
DIC              1161.581062
PDIC               -8.620376
log(Z)           -259.890804

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:00:53  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  9.493102670729752e-06 erg / (s cm2)

                                      low bound  \
GBM: total  9.182656109664176e-06 erg / (s cm2)

                                       hi bound
GBM: total  9.808105717685833e-06 erg / (s cm2)
18:00:53  INFO        Bin 47 / 72 complete.
18:00:53  INFO      ==== Time bin 48 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   415.84981530194614      +/-   8.9351384064494485E-002
 Total Likelihood Evaluations:        30349
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,7.0 -1.9 +1.7,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-8.6 -0.7 +1.0) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.3 -0.4 +0.5) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +9 +1.7) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 +/- 0.6) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval47        78.361216
n7_interval47        61.468440
n8_interval47        72.083386
b1_interval47       251.216933
total               463.129974

Values of statistical measures:

        statistical measures
AIC              -916.134162
BIC              -895.359865
DIC              -860.878480
PDIC               -9.187272
log(Z)            180.601280

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:01:21  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.158703984990293e-06 erg / (s cm2)

                                      low bound  \
GBM: total  4.767014215620693e-06 erg / (s cm2)

                                       hi bound
GBM: total  5.634209862614391e-06 erg / (s cm2)
18:01:21  INFO        Bin 48 / 72 complete.
18:01:21  INFO      ==== Time bin 49 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -491.99866832222256      +/-  0.10123263765282163
 Total Likelihood Evaluations:        45280
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,5.0 -0.8 +0.7,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-7.0 +/- 0.4) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.48 -0.13 +0.29) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.00001 +0.00010 +2.2) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -4 +10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval48      -165.189284
n7_interval48      -162.314468
n8_interval48      -165.260553
b1_interval48        50.865964
total              -441.898341

Values of statistical measures:

        statistical measures
AIC               893.922469
BIC               914.696766
DIC               953.957230
PDIC               -6.109585
log(Z)           -213.672307

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:01:58  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  9.158187679255767e-06 erg / (s cm2)

                                      low bound  \
GBM: total  8.849381498197956e-06 erg / (s cm2)

                                       hi bound
GBM: total  9.502039219876458e-06 erg / (s cm2)
18:01:58  INFO        Bin 49 / 72 complete.
18:01:58  INFO      ==== Time bin 50 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -47.819641156454978      +/-   9.9324823791312633E-002
 Total Likelihood Evaluations:        36773
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,3.3 -0.4 +0.8,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-5.66 -0.6 +0.25) x 10^-1,
GBM.spectrum.main.composite.xc_1,(3.85 -0.14 +0.5) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0006 +8) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 +/- 0.6) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval49       -54.276757
n7_interval49       -66.306393
n8_interval49       -55.073553
b1_interval49       178.448545
total                 2.791842

Values of statistical measures:

        statistical measures
AIC                 4.542103
BIC                25.316400
DIC                61.907427
PDIC               -8.416304
log(Z)            -20.767806

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:02:29  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  2.423212815302341e-05 erg / (s cm2)

                                       low bound  \
GBM: total  2.3219645593057298e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.5361498237329845e-05 erg / (s cm2)
18:02:29  INFO        Bin 50 / 72 complete.
18:02:29  INFO      ==== Time bin 51 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=   172.68762386685617      +/-  0.10139022159093558
 Total Likelihood Evaluations:        39264
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,3.0 -0.4 +0.6,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-4.88 -0.4 +0.31) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.96 -0.25 +0.5) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0006 +9) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,7.2 -2.8 +9,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval50          2.42758
n7_interval50        -17.13037
n8_interval50         -6.13068
b1_interval50        242.48363
total                221.65016

Values of statistical measures:

        statistical measures
AIC              -433.174534
BIC              -412.400237
DIC              -378.943499
PDIC               -8.442757
log(Z)             74.997282

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:03:01  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.230434955071914e-05 erg / (s cm2)

                                       low bound  \
GBM: total  5.0129222716290716e-05 erg / (s cm2)

                                        hi bound
GBM: total  5.4651410291668644e-05 erg / (s cm2)
18:03:01  INFO        Bin 51 / 72 complete.
18:03:01  INFO      ==== Time bin 52 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -115.01158835107435      +/-  0.10423586088749884
 Total Likelihood Evaluations:        50083
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,2.52 -0.34 +0.5,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-4.25 -0.5 +0.34) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.36 -0.12 +0.21) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +8 +1.1) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,7.5 -3.4 +10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval51       -70.242494
n7_interval51       -75.905065
n8_interval51       -75.708744
b1_interval51       158.691498
total               -63.164805

Values of statistical measures:

        statistical measures
AIC               136.455395
BIC               157.229692
DIC               195.268009
PDIC               -7.793554
log(Z)            -49.948898

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:03:40  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.9574049008956835e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.898180466491333e-05 erg / (s cm2)

                                        hi bound
GBM: total  2.0263206803304332e-05 erg / (s cm2)
18:03:40  INFO        Bin 52 / 72 complete.
18:03:40  INFO      ==== Time bin 53 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -597.50589413991452      +/-  0.10300881914050244
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        43683
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,4.5 -0.5 +0.7,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-6.42 -0.4 +0.30) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.63 -0.15 +0.20) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0008 +10) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 -0.6 +0.7) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval52      -192.334285
n7_interval52      -206.786441
n8_interval52      -178.460345
b1_interval52        30.479307
total              -547.101764

Values of statistical measures:

        statistical measures
AIC              1104.329314
BIC              1125.103611
DIC              1160.749787
PDIC               -7.952193
log(Z)           -259.493513

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:04:16  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2433778774634838e-05 erg / (s cm2)

                                      low bound  \
GBM: total  1.207091960432386e-05 erg / (s cm2)

                                       hi bound
GBM: total  1.281064081199104e-05 erg / (s cm2)
18:04:16  INFO        Bin 53 / 72 complete.
18:04:16  INFO      ==== Time bin 54 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -537.28744091872898      +/-  0.10241914667546451
 Total Likelihood Evaluations:        50740
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,5.6 -0.9 +0.7,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-7.2 -0.4 +0.5) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.21 -0.16 +0.23) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.00001 +0.00011 +1.5) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 -0.6 +0.9) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval53      -157.299490
n7_interval53      -177.283785
n8_interval53      -178.992994
b1_interval53        26.127981
total              -487.448288

Values of statistical measures:

        statistical measures
AIC               985.022363
BIC              1005.796660
DIC              1044.142175
PDIC               -6.209886
log(Z)           -233.340971

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:04:54  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  7.912045019851011e-06 erg / (s cm2)

                                      low bound  \
GBM: total  7.655275143079219e-06 erg / (s cm2)

                                       hi bound
GBM: total  8.192345011711629e-06 erg / (s cm2)
18:04:54  INFO        Bin 54 / 72 complete.
18:04:54  INFO      ==== Time bin 55 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -377.86856524896695      +/-  0.10202240463560205
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        43106
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,10.00 -2.8 -0.32,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-9.759 -0.023 +0.8) x 10^-1,
GBM.spectrum.main.composite.xc_1,(1.80 -0.26 +0.20) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +2.9 +2.2) x 10^-3,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8.8 -2.9 +5,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval54      -114.587506
n7_interval54      -139.415709
n8_interval54      -127.378228
b1_interval54        50.359068
total              -331.022375

Values of statistical measures:

        statistical measures
AIC               672.170536
BIC               692.944833
DIC               729.820000
PDIC               -6.885245
log(Z)           -164.106233

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:05:30  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  3.0455292160684885e-06 erg / (s cm2)

                                       low bound  \
GBM: total  2.9032935243456263e-06 erg / (s cm2)

                                        hi bound
GBM: total  3.2171731114467115e-06 erg / (s cm2)
18:05:31  INFO        Bin 55 / 72 complete.
18:05:31  INFO      ==== Time bin 56 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -1096.8473583707357      +/-   9.8621571929098262E-002
 Total Likelihood Evaluations:        40800
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,9.81 -1.9 -0.07,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,-1.163 -0.009 +0.06,
GBM.spectrum.main.composite.xc_1,(1.81 -0.18 +0.25) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +6 +1.5) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8 -4 +8,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval55      -309.396169
n7_interval55      -301.173285
n8_interval55      -291.906932
b1_interval55      -147.940398
total             -1050.416784

Values of statistical measures:

        statistical measures
AIC              2110.959354
BIC              2131.733652
DIC              2157.397987
PDIC              -12.978703
log(Z)           -476.354755

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:06:03  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.2732724640989627e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.2121492125773768e-06 erg / (s cm2)

                                       hi bound
GBM: total  1.336645218375249e-06 erg / (s cm2)
18:06:03  INFO        Bin 56 / 72 complete.
18:06:03  INFO      ==== Time bin 57 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1586.7189733393736      +/-   9.2592684481661441E-002
 Total Likelihood Evaluations:        48318
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,9.43 -1.8 +0.21,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,-1.356 -0.022 +0.06,
GBM.spectrum.main.composite.xc_1,(3.4 -0.7 +1.0) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0012 +10) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.1 +/- 0.6) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval56      -407.533469
n7_interval56      -433.188386
n8_interval56      -420.089907
b1_interval56      -280.452770
total             -1541.264532

Values of statistical measures:

        statistical measures
AIC              3092.654850
BIC              3113.429147
DIC              3147.680672
PDIC               -6.151761
log(Z)           -689.103294

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:06:40  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.175910354036076e-07 erg / (s cm2)

                                      low bound  \
GBM: total  7.567677602908245e-07 erg / (s cm2)

                                       hi bound
GBM: total  8.864164235035819e-07 erg / (s cm2)
18:06:40  INFO        Bin 57 / 72 complete.
18:06:40  INFO      ==== Time bin 58 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -1615.8008740369130      +/-   8.3513943996451623E-002
 Total Likelihood Evaluations:        38573
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                     result              unit
parameter
GBM.spectrum.main.composite.K_1               4.1 -1.3 +2.0   1 / (keV s cm2)
GBM.spectrum.main.composite.index_1       -1.29 -0.13 +0.10
GBM.spectrum.main.composite.xc_1     (2.7 -0.4 +1.8) x 10^2               keV
GBM.spectrum.main.composite.K_2           (0 +8 +6) x 10^-4  1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2                    8 -4 +7               keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval57      -441.520876
n7_interval57      -422.209513
n8_interval57      -411.689894
b1_interval57      -292.839346
total             -1568.259629

Values of statistical measures:

        statistical measures
AIC              3146.645045
BIC              3167.419342
DIC              3158.184860
PDIC              -55.121267
log(Z)           -701.733403

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:07:15  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  4.16607708494902e-07 erg / (s cm2)

                                      low bound  \
GBM: total  3.732747453825171e-07 erg / (s cm2)

                                       hi bound
GBM: total  4.660542294389256e-07 erg / (s cm2)
18:07:15  INFO        Bin 58 / 72 complete.
18:07:15  INFO      ==== Time bin 59 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -3171.9783034546253      +/-   9.0815185346807728E-002
 Total Likelihood Evaluations:        37164
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,3.4 -0.4 +1.0,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,-1.43 -0.07 +0.04,
GBM.spectrum.main.composite.xc_1,(5.0 -0.9 +1.7) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0004 +4) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.2 -0.8 +0.4) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval58      -805.710753
n7_interval58      -813.159756
n8_interval58      -810.377391
b1_interval58      -695.926637
total             -3125.174537

Values of statistical measures:

        statistical measures
AIC              6260.474860
BIC              6281.249157
DIC              6260.364793
PDIC              -61.691841
log(Z)          -1377.572674

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:07:49  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  2.5371703243048417e-07 erg / (s cm2)

                                       low bound  \
GBM: total  2.3210868814816365e-07 erg / (s cm2)

                                       hi bound
GBM: total  2.767809942024934e-07 erg / (s cm2)
18:07:49  INFO        Bin 59 / 72 complete.
18:07:49  INFO      ==== Time bin 60 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2655.6586533349509      +/-   7.1004006255372329E-002
 Total Likelihood Evaluations:        30260
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                     result              unit
parameter
GBM.spectrum.main.composite.K_1                 1.5 +/- 1.1   1 / (keV s cm2)
GBM.spectrum.main.composite.index_1       -1.50 -0.15 +0.33
GBM.spectrum.main.composite.xc_1     (3.5 -1.1 +2.0) x 10^2               keV
GBM.spectrum.main.composite.K_2       (0.0 +7 +1.5) x 10^-3  1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2     (1.13 -0.8 +0.33) x 10               keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval59      -687.188841
n7_interval59      -681.763962
n8_interval59      -682.326091
b1_interval59      -556.457917
total             -2607.736812

Values of statistical measures:

        statistical measures
AIC              5225.599410
BIC              5246.373707
DIC              5031.498649
PDIC             -263.721458
log(Z)          -1153.337899

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:08:20  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.819561753200167e-08 erg / (s cm2)

                                     low bound  \
GBM: total  5.19390004933848e-08 erg / (s cm2)

                                       hi bound
GBM: total  8.682538667768219e-08 erg / (s cm2)
18:08:20  INFO        Bin 60 / 72 complete.
18:08:20  INFO      ==== Time bin 61 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -3771.7473896439014      +/-   3.4325984851457728E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:         6818
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(0.011 +0.024 +9) x 10^-4,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,-1.32 -0.22 +0.7,
GBM.spectrum.main.composite.xc_1,(2.9 -1.5 +2.1) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0013 +0.0026 +3.2) x 10^-6,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 +/- 6,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval60      -949.942529
n7_interval60      -945.211731
n8_interval60      -946.877032
b1_interval60      -828.972748
total             -3671.004041

Values of statistical measures:

        statistical measures
AIC              7352.133868
BIC              7372.908165
DIC              7464.228937
PDIC              -45.674156
log(Z)          -1638.049078

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

18:08:33  WARNING   Too few points to create valid contours

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:08:33  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.410377059149829e-11 erg / (s cm2)

                                       low bound  \
GBM: total  3.9263474847869355e-12 erg / (s cm2)

                                        hi bound
GBM: total  4.6288803253243537e-10 erg / (s cm2)
18:08:33  INFO        Bin 61 / 72 complete.
18:08:33  INFO      ==== Time bin 62 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1721.2154777043288      +/-   6.1795683301898392E-002
 Total Likelihood Evaluations:        16723
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(0.2173 -0.0035 +1.9) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-4.9 -5 -0.4) x 10^-1,
GBM.spectrum.main.composite.xc_1,(2.79 -0.29 +2.6) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0005 +2.1) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.46 -1.1 +0.18) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval61      -438.704464
n7_interval61      -459.548098
n8_interval61      -442.047815
b1_interval61      -317.667838
total             -1657.968216

Values of statistical measures:

        statistical measures
AIC              3326.062218
BIC              3346.836515
DIC              3392.942606
PDIC              -27.331184
log(Z)           -747.514384

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:08:54  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.3583672987343758e-07 erg / (s cm2)

                                      low bound  \
GBM: total  9.347260708186086e-08 erg / (s cm2)

                                        hi bound
GBM: total  1.9146112371953931e-07 erg / (s cm2)
18:08:54  INFO        Bin 62 / 72 complete.
18:08:54  INFO      ==== Time bin 63 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -2690.6554852384656      +/-   8.9949241960493462E-002
 Total Likelihood Evaluations:        33053
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,(4.1 -0.8 +1.5) x 10^-1,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-8.5 -0.8 +0.5) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.4 -0.5 +1.2) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0004 +1.3) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.33 -0.9 +0.32) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval62      -686.494764
n7_interval62      -695.619316
n8_interval62      -687.175198
b1_interval62      -563.969899
total             -2633.259177

Values of statistical measures:

        statistical measures
AIC              5276.644141
BIC              5297.418438
DIC              5334.313837
PDIC              -19.240141
log(Z)          -1168.536830

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:09:24  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.655207236685462e-07 erg / (s cm2)

                                      low bound  \
GBM: total  6.087046062262048e-07 erg / (s cm2)

                                       hi bound
GBM: total  7.335336430244192e-07 erg / (s cm2)
18:09:24  INFO        Bin 63 / 72 complete.
18:09:24  INFO      ==== Time bin 64 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2378.6089270108832      +/-   9.1099674798178543E-002
 Total Likelihood Evaluations:        33513
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,1.18 -0.16 +0.34,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,(-9.9 -0.7 +0.4) x 10^-1,
GBM.spectrum.main.composite.xc_1,(4.3 -0.4 +1.2) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0005 +2.0) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,7 -4 +9,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval63      -609.290569
n7_interval63      -614.489087
n8_interval63      -618.114187
b1_interval63      -482.649011
total             -2324.542855

Values of statistical measures:

        statistical measures
AIC              4659.211495
BIC              4679.985792
DIC              4710.269262
PDIC              -21.097569
log(Z)          -1033.016732

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:09:53  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  8.541594522441638e-07 erg / (s cm2)

                                      low bound  \
GBM: total  7.914524215991364e-07 erg / (s cm2)

                                       hi bound
GBM: total  9.269120290610849e-07 erg / (s cm2)
18:09:53  INFO        Bin 64 / 72 complete.
18:09:53  INFO      ==== Time bin 65 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3073.4385352981049      +/-  0.10399245927402133
 Total Likelihood Evaluations:        48167
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,4.09 -0.25 +0.4,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,-1.128 -0.032 +0.015,
GBM.spectrum.main.composite.xc_1,(4.53 -0.13 +0.7) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0005 +2.1) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -4 +8,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval64      -788.044662
n7_interval64      -791.454837
n8_interval64      -788.620169
b1_interval64      -654.278036
total             -3022.397704

Values of statistical measures:

        statistical measures
AIC              6054.921193
BIC              6075.695490
DIC              6108.773488
PDIC               -9.884835
log(Z)          -1334.777396

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:10:29  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  1.470663558848992e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.4216050890925358e-06 erg / (s cm2)

                                       hi bound
GBM: total  1.522840628721899e-06 erg / (s cm2)
18:10:29  INFO        Bin 65 / 72 complete.
18:10:29  INFO      ==== Time bin 66 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -2160.9222954961592      +/-   9.3240902697588363E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        38896
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,4.0 -0.4 +1.0,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,-1.171 -0.06 +0.031,
GBM.spectrum.main.composite.xc_1,(3.8 -0.4 +1.0) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0005 +2.0) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(1.0 -0.6 +0.7) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval65      -554.448200
n7_interval65      -563.217393
n8_interval65      -556.491039
b1_interval65      -436.893982
total             -2111.050615

Values of statistical measures:

        statistical measures
AIC              4232.227017
BIC              4253.001314
DIC              4282.516025
PDIC              -14.985289
log(Z)           -938.476629

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:11:04  INFO        10 keV-10 MeV flux =                                         flux  \
GBM: total  9.580593694747e-07 erg / (s cm2)

                                      low bound  \
GBM: total  8.984515787596196e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.0303230801055784e-06 erg / (s cm2)
18:11:04  INFO        Bin 66 / 72 complete.
18:11:04  INFO      ==== Time bin 67 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1742.6020772588167      +/-   9.4754379944013867E-002
 Total Likelihood Evaluations:        39425
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,5.7 -0.5 +1.1,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,-1.140 -0.06 +0.026,
GBM.spectrum.main.composite.xc_1,(3.64 -0.25 +0.9) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0005 +2.6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -5 +8,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval66      -455.001532
n7_interval66      -457.505318
n8_interval66      -457.857771
b1_interval66      -323.283618
total             -1693.648238

Values of statistical measures:

        statistical measures
AIC              3397.422263
BIC              3418.196560
DIC              3449.019144
PDIC              -12.163499
log(Z)           -756.802466

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:11:38  INFO        10 keV-10 MeV flux =                                             flux  \
GBM: total  1.5678003554646208e-06 erg / (s cm2)

                                       low bound  \
GBM: total  1.4853886997010356e-06 erg / (s cm2)

                                        hi bound
GBM: total  1.6657573221991345e-06 erg / (s cm2)
18:11:38  INFO        Bin 67 / 72 complete.
18:11:38  INFO      ==== Time bin 68 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2164.2916441232510      +/-   9.4571030644507531E-002
 Total Likelihood Evaluations:        41816
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,6.6 -0.8 +1.2,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,-1.261 -0.05 +0.030,
GBM.spectrum.main.composite.xc_1,(3.67 -0.26 +1.1) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0 +6 +1.1) x 10^-4,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8 -4 +7,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval67      -552.486937
n7_interval67      -571.819860
n8_interval67      -565.399950
b1_interval67      -426.951136
total             -2116.657883

Values of statistical measures:

        statistical measures
AIC              4243.441552
BIC              4264.215849
DIC              4296.928768
PDIC               -9.260155
log(Z)           -939.939918

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:12:13  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  9.879556665556663e-07 erg / (s cm2)

                                      low bound  \
GBM: total  9.331352500848624e-07 erg / (s cm2)

                                        hi bound
GBM: total  1.0512817929656057e-06 erg / (s cm2)
18:12:13  INFO        Bin 68 / 72 complete.
18:12:13  INFO      ==== Time bin 69 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2067.9725957854794      +/-   9.2014148347022165E-002
 Total Likelihood Evaluations:        34458
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,5.5 -0.6 +1.3,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,-1.324 -0.06 +0.035,
GBM.spectrum.main.composite.xc_1,(4.6 -0.7 +1.4) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0005 +2.1) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,9 -5 +7,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval68      -524.614488
n7_interval68      -549.687953
n8_interval68      -535.038888
b1_interval68      -412.053657
total             -2021.394986

Values of statistical measures:

        statistical measures
AIC              4052.915759
BIC              4073.690056
DIC              4088.171103
PDIC              -25.741404
log(Z)           -898.109087

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:12:44  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  6.971082179995851e-07 erg / (s cm2)

                                      low bound  \
GBM: total  6.470569958384254e-07 erg / (s cm2)

                                       hi bound
GBM: total  7.551419577471209e-07 erg / (s cm2)
18:12:44  INFO        Bin 69 / 72 complete.
18:12:44  INFO      ==== Time bin 70 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
 ln(ev)=  -2242.6526846122761      +/-   8.6515121515628055E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        33851
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,5.1 -1.2 +1.0,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,-1.41 -0.05 +0.08,
GBM.spectrum.main.composite.xc_1,(4.1 -0.9 +1.5) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0005 +3.2) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,8 -4 +7,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval69      -575.970896
n7_interval69      -588.923794
n8_interval69      -564.160172
b1_interval69      -467.304625
total             -2196.359488

Values of statistical measures:

        statistical measures
AIC              4402.844762
BIC              4423.619059
DIC              4452.910264
PDIC              -12.004008
log(Z)           -973.971686

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:13:14  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  3.795226334701712e-07 erg / (s cm2)

                                      low bound  \
GBM: total  3.459221560284333e-07 erg / (s cm2)

                                       hi bound
GBM: total  4.183321479887692e-07 erg / (s cm2)
18:13:14  INFO        Bin 70 / 72 complete.
18:13:14  INFO      ==== Time bin 71 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3435.1821335498439      +/-   8.5638791345754584E-002
 Total Likelihood Evaluations:        33389
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
GBM.spectrum.main.composite.K_1,2.2 -0.4 +0.7,1 / (keV s cm2)
GBM.spectrum.main.composite.index_1,-1.39 -0.08 +0.06,
GBM.spectrum.main.composite.xc_1,(3.7 -0.8 +1.6) x 10^2,keV
GBM.spectrum.main.composite.K_2,(0.0001 +0.0005 +1.6) x 10^-5,1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2,(0.64 -0.26 +1.0) x 10,keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval70      -878.685580
n7_interval70      -876.625665
n8_interval70      -856.947739
b1_interval70      -773.484876
total             -3385.743861

Values of statistical measures:

        statistical measures
AIC              6781.613508
BIC              6802.387805
DIC              6819.663530
PDIC              -28.419689
log(Z)          -1491.880645

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:13:44  INFO        10 keV-10 MeV flux =                                           flux  \
GBM: total  1.74459565955799e-07 erg / (s cm2)

                                       low bound  \
GBM: total  1.5794863337132887e-07 erg / (s cm2)

                                       hi bound
GBM: total  1.914136073473849e-07 erg / (s cm2)
18:13:44  INFO        Bin 71 / 72 complete.
18:13:44  INFO      ==== Time bin 72 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    5
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3027.7600311804445      +/-   7.2614646098078259E-002
 Total Likelihood Evaluations:        27588
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

                                                     result              unit
parameter
GBM.spectrum.main.composite.K_1          (10 -5 +8) x 10^-1   1 / (keV s cm2)
GBM.spectrum.main.composite.index_1          -1.42 +/- 0.17
GBM.spectrum.main.composite.xc_1     (3.8 -1.3 +1.8) x 10^2               keV
GBM.spectrum.main.composite.K_2       (0.0 +7 +2.2) x 10^-4  1 / (s cm2 keV3)
GBM.spectrum.main.composite.kT_2       (1.0 -0.6 +0.5) x 10               keV

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval71      -754.118421
n7_interval71      -765.162688
n8_interval71      -757.927979
b1_interval71      -699.825652
total             -2977.034739

Values of statistical measures:

        statistical measures
AIC              5964.195264
BIC              5984.969561
DIC              5949.154088
PDIC              -88.364912
log(Z)          -1314.939474

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:14:13  INFO        10 keV-10 MeV flux =                                            flux  \
GBM: total  5.968249943791181e-08 erg / (s cm2)

                                      low bound  \
GBM: total  4.875798462436612e-08 erg / (s cm2)

                                       hi bound
GBM: total  7.311509512429047e-08 erg / (s cm2)
18:14:13  INFO        Bin 72 / 72 complete.

All 72 bins fitted successfully.

In [20]:
    ## Cell 16 — Save Results to CSV (Cutoff+BB)

In [21]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    fit_array = np.array(fit_rows)
    cutoffbb_fit_param = Table(fit_array, names=PARAM_NAMES)
    cutoffbb_fit_param['t_start'] = bb_starts
    cutoffbb_fit_param['t_stop']  = bb_stops
    cutoffbb_fit_param['dt']      = bb_stops - bb_starts

    csv_path = os.path.join(MODEL_PATHS['root'], 'fit_params.csv')
    cutoffbb_fit_param.write(csv_path, overwrite=True)
    print(f'Results saved to: {csv_path}')
    print(f'Shape: {fit_array.shape}  ({n_bins} bins x {len(PARAM_NAMES)} parameters)')
    cutoffbb_fit_param

Results saved to: gbm_pipeline_output/cutoffbb/fit_params.csv
Shape: (72, 26)  (72 bins x 26 parameters)

## Cell 17 — Time-Resolved Spectral Fitting (Synchrotron Model)

In [22]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    MODEL_PATHS = get_model_paths('synchrotron')

    PARAM_NAMES = []
    for p in ['K', 'B', 'index', 'gamma_cool']:
        PARAM_NAMES.extend([p, f'{p}_n_err', f'{p}_p_err', f'{p}_avg_err'])
    PARAM_NAMES.extend(['flux', 'flux_low', 'flux_hi', 'DIC', 'PDIC', 'BIC'])

    fit_rows = []

    for i in range(n_bins):
        log.info('==== Time bin %d / %d ====', i + 1, n_bins)

        det_plugins = []
        for det in detectors:
            p = time_resolved_plugins[det][i]
            if det.startswith('b'):
                p.set_active_measurements(CONFIG['bgo_range'])
            else:
                ranges = [r.strip() for r in CONFIG['nai_range'].split(',')]
                p.set_active_measurements(*ranges)
            det_plugins.append(p)

        data_list = DataList(*det_plugins)
        model = build_synchrotron_model(CONFIG['ra'], CONFIG['dec'], CONFIG['priors_synchrotron'])

        bayes = BayesianAnalysis(model, data_list)
        bayes.set_sampler('multinest')
        bayes.sampler.setup(n_live_points=CONFIG['n_live_points'], sampling_efficiency=CONFIG['sampling_efficiency'], auto_clean=True)
        bayes.sample()

        fig_spec = plot_spectra(
            bayes.results,
            ene_min=1.0, ene_max=1e5, num_ene=200,
            contour_colors='white', contour_style_kwargs=dict(alpha=0.2),
            use_components=True, components_to_use=['total'],
            flux_unit='keV2/(cm2 s keV)',
        )
        ax = plt.gca()
        ax.set_xlabel('Energy (keV)', fontsize=16)
        ax.set_ylabel(r'$\nu\,F_\nu\;[\mathrm{keV\,cm^{-2}\,s^{-1}}]$', fontsize=16)
        ax.set_title(f"{CONFIG['trigger_name']}  bin {i+1}/{n_bins}  [{bb_starts[i]:.3f}, {bb_stops[i]:.3f}] s", fontsize=13)
        fig_spec.savefig(os.path.join(MODEL_PATHS['spectra'], f'synchrotron_spec_bin{i+1:03d}.png'), dpi=120, bbox_inches='tight')
        plt.close('all')

        fig_corner = bayes.results.corner_plot()
        fig_corner.savefig(os.path.join(MODEL_PATHS['corners'], f'synchrotron_corner_bin{i+1:03d}.png'), dpi=100, bbox_inches='tight')
        plt.close('all')

        flux_df = bayes.results.get_point_source_flux(10 * u.keV, 10 * u.MeV)
        log.info('  10 keV-10 MeV flux = %s', flux_df)
        f_val = flux_df['flux'].iloc[0].value
        f_low = flux_df['low bound'].iloc[0].value
        f_hi  = flux_df['hi bound'].iloc[0].value

        df  = bayes.results.get_data_frame('equal tail')
        df  = df.drop('unit', axis=1, errors='ignore')
        param_array = df.to_numpy().flatten()

        stat_df = bayes.results.get_statistic_measure_frame()
        dic_val = stat_df.loc['DIC'].iloc[0] if 'DIC' in stat_df.index else np.nan
        pdic_val = stat_df.loc['PDIC'].iloc[0] if 'PDIC' in stat_df.index else np.nan
        bic_val = stat_df.loc['BIC'].iloc[0] if 'BIC' in stat_df.index else np.nan

        full_row = np.append(param_array, [f_val, f_low, f_hi, dic_val, pdic_val, bic_val])
        fit_rows.append(full_row)
        log.info('  Bin %d / %d complete.', i + 1, n_bins)

    print(f'\nAll {n_bins} bins fitted successfully.')

18:14:13  INFO      ==== Time bin 1 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2473.3684228445723      +/-   3.2845164076930305E-002
 Total Likelihood Evaluations:         8069
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.011 +0.012 +1.3) x 10^-5,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(0.173 -0.021 +3.5) x 10,G
Synchrotron...index,3.0 -0.6 +0.9,
Synchrotron...gamma_cool,(0.014 +0.026 +4) x 10^7,

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval0      -635.991532
n7_interval0      -640.850983
n8_interval0      -632.018288
b1_interval0      -551.727290
total            -2460.588092

Values of statistical measures:

        statistical measures
AIC              4929.259867
BIC              4945.896252
DIC              4940.009754
PDIC              -14.001497
log(Z)          -1074.170258

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:17:20  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  8.191357422566679e-10 erg / (s cm2)

                                              low bound  \
Synchrotron: total  3.717412914587904e-11 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.0786198092180687e-08 erg / (s cm2)
18:17:20  INFO        Bin 1 / 72 complete.
18:17:20  INFO      ==== Time bin 2 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2641.5469301270841      +/-   8.7024763805067379E-002
 Total Likelihood Evaluations:        33317
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.10 +0.09 +1.1) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.3 -7 -3.0) x 10,G
Synchrotron...index,3.4 +/- 0.6,
Synchrotron...gamma_cool,(0.045 +0.033 +1.4) x 10^7,

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval1      -699.540319
n7_interval1      -692.262661
n8_interval1      -693.541193
b1_interval1      -575.165997
total            -2660.510170

Values of statistical measures:

        statistical measures
AIC              5329.104022
BIC              5345.740407
DIC              5268.356837
PDIC              -19.040493
log(Z)          -1147.209255

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:21:28  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  7.408828144389998e-07 erg / (s cm2)

                                              low bound  \
Synchrotron: total  6.376418218398808e-07 erg / (s cm2)

                                               hi bound
Synchrotron: total  8.844515719223284e-07 erg / (s cm2)
18:21:28  INFO        Bin 2 / 72 complete.
18:21:28  INFO      ==== Time bin 3 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1743.2287919795974      +/-   8.8920390887781406E-002
 Total Likelihood Evaluations:        39451
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.33 +0.22 +2.2) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(7.2 -4 -1.7) x 10,G
Synchrotron...index,3.8 -0.6 +0.5,
Synchrotron...gamma_cool,(0.07 +0.04 +2.1) x 10^7,

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval2      -473.662121
n7_interval2      -477.828520
n8_interval2      -470.005828
b1_interval2      -346.951496
total            -1768.447964

Values of statistical measures:

        statistical measures
AIC              3544.979611
BIC              3561.615995
DIC              3467.086792
PDIC              -25.847884
log(Z)           -757.074645

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:25:33  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.4304717900313305e-06 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.2789877738912641e-06 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.6525167576525173e-06 erg / (s cm2)
18:25:33  INFO        Bin 3 / 72 complete.
18:25:33  INFO      ==== Time bin 4 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -2324.1751637676884      +/-   8.9728791348696477E-002
 Total Likelihood Evaluations:        41026
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.36 +0.11 +2.1) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(4.8 -2.8 -0.7) x 10,G
Synchrotron...index,3.62 -0.27 +0.9,
Synchrotron...gamma_cool,(0.062 +0.025 +2.0) x 10^7,

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval3      -611.592498
n7_interval3      -617.523350
n8_interval3      -614.180388
b1_interval3      -503.708685
total            -2347.004922

Values of statistical measures:

        statistical measures
AIC              4702.093526
BIC              4718.729911
DIC              4605.903778
PDIC              -47.705692
log(Z)          -1009.376449

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:30:19  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  6.958596093822115e-07 erg / (s cm2)

                                            low bound  \
Synchrotron: total  6.2815384269492e-07 erg / (s cm2)

                                               hi bound
Synchrotron: total  7.871100282122946e-07 erg / (s cm2)
18:30:19  INFO        Bin 4 / 72 complete.
18:30:19  INFO      ==== Time bin 5 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1619.4352569015543      +/-   8.9517855103548510E-002
 Total Likelihood Evaluations:        36778
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.66 +0.28 +5) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(4.6 -3.0 -0.8) x 10,G
Synchrotron...index,3.21 -0.34 +0.7,
Synchrotron...gamma_cool,(0.058 +0.023 +1.9) x 10^7,

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval4      -443.942697
n7_interval4      -450.303475
n8_interval4      -448.338199
b1_interval4      -300.922930
total            -1643.507301

Values of statistical measures:

        statistical measures
AIC              3295.098284
BIC              3311.734669
DIC              3215.089107
PDIC              -29.755040
log(Z)           -703.311796

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:34:55  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.3889199673005301e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  1.218354321486294e-06 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.6248613071273049e-06 erg / (s cm2)
18:34:55  INFO        Bin 5 / 72 complete.
18:34:55  INFO      ==== Time bin 6 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1360.5571165431338      +/-   9.4592440812570816E-002
 Total Likelihood Evaluations:        41466
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.90 +0.24 +4) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(5.8 -2.9 -0.6) x 10,G
Synchrotron...index,4.0 -0.5 +0.6,
Synchrotron...gamma_cool,(0.083 +0.021 +1.4) x 10^7,

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval5      -392.331991
n7_interval5      -383.744341
n8_interval5      -370.839404
b1_interval5      -242.188737
total            -1389.104474

Values of statistical measures:

        statistical measures
AIC              2786.292629
BIC              2802.929014
DIC              2692.804850
PDIC              -34.099192
log(Z)           -590.882448

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:39:20  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  2.4008926642723916e-06 erg / (s cm2)

                                               low bound  \
Synchrotron: total  2.2185963923500366e-06 erg / (s cm2)

                                                hi bound
Synchrotron: total  2.6447712913814903e-06 erg / (s cm2)
18:39:20  INFO        Bin 6 / 72 complete.
18:39:20  INFO      ==== Time bin 7 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -679.69863607943410      +/-   9.3608578670607637E-002
 Total Likelihood Evaluations:        45051
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.7 +0.7 +4) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(5.4 -2.1 -0.7) x 10,G
Synchrotron...index,4.1 -0.4 +0.6,
Synchrotron...gamma_cool,(0.13 +0.08 +2.6) x 10^7,

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval6      -207.685734
n7_interval6      -222.432417
n8_interval6      -220.862477
b1_interval6       -62.145235
total             -713.125862

Values of statistical measures:

        statistical measures
AIC              1434.335407
BIC              1450.971792
DIC              1355.651196
PDIC              -12.494117
log(Z)           -295.189367

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:43:15  INFO        10 keV-10 MeV flux =                                                   flux  \
Synchrotron: total  3.70918791203175e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  3.414743327261755e-06 erg / (s cm2)

                                               hi bound
Synchrotron: total  4.120382440602978e-06 erg / (s cm2)
18:43:15  INFO        Bin 7 / 72 complete.
18:43:15  INFO      ==== Time bin 8 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1580.4603099108199      +/-   9.3564440487598460E-002
 Total Likelihood Evaluations:        40627
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.6 +0.7 +7) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(3.4 -1.7 -0.6) x 10,G
Synchrotron...index,3.55 -0.32 +0.6,
Synchrotron...gamma_cool,(0.09 +0.04 +2.4) x 10^7,

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval7      -437.610140
n7_interval7      -443.297290
n8_interval7      -436.063849
b1_interval7      -291.505901
total            -1608.477180

Values of statistical measures:

        statistical measures
AIC              3225.038041
BIC              3241.674426
DIC              3143.728017
PDIC              -23.681371
log(Z)           -686.385191

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:47:13  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  1.682803045066565e-06 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.5112011476004247e-06 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.9016538614451624e-06 erg / (s cm2)
18:47:13  INFO        Bin 8 / 72 complete.
18:47:13  INFO      ==== Time bin 9 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -315.77409815129437      +/-   8.5729468224558722E-002
 Total Likelihood Evaluations:        32348
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.7 +0.5 +5) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.1 -6 -2.3) x 10,G
Synchrotron...index,3.14 -0.33 +0.9,
Synchrotron...gamma_cool,(0.06 +0.04 +1.9) x 10^7,

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval8      -125.183549
n7_interval8      -128.492342
n8_interval8      -126.858318
b1_interval8        37.301760
total             -343.232449

Values of statistical measures:

        statistical measures
AIC               694.548580
BIC               711.184964
DIC               626.538957
PDIC              -13.989280
log(Z)           -137.138948

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:50:46  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  5.112948901151794e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  4.451893818609445e-06 erg / (s cm2)

                                                hi bound
Synchrotron: total  6.0332298993150906e-06 erg / (s cm2)
18:50:46  INFO        Bin 9 / 72 complete.
18:50:46  INFO      ==== Time bin 10 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1356.3818876909440      +/-  0.10605779562827866
 Total Likelihood Evaluations:        69546
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(3.5 +0.8 +4) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(5.4 -1.3 -0.5) x 10,G
Synchrotron...index,4.885 -0.5 +0.016,
Synchrotron...gamma_cool,(0.30 +0.09 +7) x 10^7,

Values of -log(posterior) at the minimum:

              -log(posterior)
n6_interval9      -393.776675
n7_interval9      -404.006979
n8_interval9      -382.616249
b1_interval9      -217.196200
total            -1397.596104

Values of statistical measures:

        statistical measures
AIC              2803.275890
BIC              2819.912275
DIC              2696.868120
PDIC              -23.092723
log(Z)           -589.069169

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

18:55:38  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  6.2988798842300756e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  6.085867584975652e-06 erg / (s cm2)

                                               hi bound
Synchrotron: total  6.599803098478425e-06 erg / (s cm2)
18:55:38  INFO        Bin 10 / 72 complete.
18:55:38  INFO      ==== Time bin 11 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -1154.2962428380963      +/-   9.2913807801995180E-002
 Total Likelihood Evaluations:        38601
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.3 +0.5 +8) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(5.2 -3.2 -0.9) x 10,G
Synchrotron...index,3.66 -0.6 +0.33,
Synchrotron...gamma_cool,(0.067 +0.020 +2.2) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval10      -322.024846
n7_interval10      -332.950817
n8_interval10      -332.359231
b1_interval10      -194.710063
total             -1182.044957

Values of statistical measures:

        statistical measures
AIC              2372.173596
BIC              2388.809980
DIC              2228.198679
PDIC              -86.781418
log(Z)           -501.304489

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:00:01  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  3.1455162007510176e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  2.814846695977857e-06 erg / (s cm2)

                                                hi bound
Synchrotron: total  3.5654562300771154e-06 erg / (s cm2)
19:00:01  INFO        Bin 11 / 72 complete.
19:00:01  INFO      ==== Time bin 12 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -414.85018618049384      +/-   9.5013156059437734E-002
 Total Likelihood Evaluations:        48631
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.5 +0.6 +5) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(8.4 -4 -1.2) x 10,G
Synchrotron...index,4.15 -0.32 +0.6,
Synchrotron...gamma_cool,(0.12 +0.05 +2.2) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval11      -167.340992
n7_interval11      -161.272804
n8_interval11      -155.702300
b1_interval11        35.029041
total              -449.287055

Values of statistical measures:

        statistical measures
AIC               906.657792
BIC               923.294177
DIC               750.411250
PDIC              -88.042824
log(Z)           -180.167147

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:04:15  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  7.908315474575489e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  7.397057906711166e-06 erg / (s cm2)

                                              hi bound
Synchrotron: total  8.57609697871627e-06 erg / (s cm2)
19:04:15  INFO        Bin 12 / 72 complete.
19:04:15  INFO      ==== Time bin 13 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1091.0188391052488      +/-  0.11018178912797885
 Total Likelihood Evaluations:        73291
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(2.8 +0.6 +2.9) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.1 -2.0 -0.6) x 10,G
Synchrotron...index,5.00 -0.4 -0.04,
Synchrotron...gamma_cool,(0.30 +0.10 +5) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval12      -327.156415
n7_interval12      -322.529617
n8_interval12      -337.555391
b1_interval12      -146.130302
total             -1133.371725

Values of statistical measures:

        statistical measures
AIC              2274.827132
BIC              2291.463517
DIC              2175.766372
PDIC              -12.565957
log(Z)           -473.823461

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:09:24  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.3804156430368762e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.3369202963847484e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.4287338694326348e-05 erg / (s cm2)
19:09:24  INFO        Bin 13 / 72 complete.
19:09:24  INFO      ==== Time bin 14 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -882.89270116205432      +/-  0.11091882979120550
 Total Likelihood Evaluations:        75071
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(3.40 +0.31 +3.1) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.61 -1.9 -0.34) x 10,G
Synchrotron...index,4.985 -0.32 -0.023,
Synchrotron...gamma_cool,(0.31 +0.04 +2.8) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval13      -294.529009
n7_interval13      -279.068195
n8_interval13      -274.012258
b1_interval13       -77.948664
total              -925.558127

Values of statistical measures:

        statistical measures
AIC              1859.199936
BIC              1875.836320
DIC              1724.768927
PDIC              -46.892106
log(Z)           -383.435428

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:14:43  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.8533602888682716e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.7951599426964508e-05 erg / (s cm2)

                                              hi bound
Synchrotron: total  1.91988363464807e-05 erg / (s cm2)
19:14:43  INFO        Bin 14 / 72 complete.
19:14:43  INFO      ==== Time bin 15 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -969.00035430730145      +/-  0.10637684515571678
 Total Likelihood Evaluations:        67924
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(3.67 +0.35 +3.4) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(7.0 -1.6 -0.4) x 10,G
Synchrotron...index,5.00 -0.5 -0.07,
Synchrotron...gamma_cool,(0.343 +0.033 +5) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval14      -286.267307
n7_interval14      -309.108601
n8_interval14      -302.364375
b1_interval14      -114.612792
total             -1012.353075

Values of statistical measures:

        statistical measures
AIC              2032.789832
BIC              2049.426217
DIC              1663.073383
PDIC             -282.506373
log(Z)           -420.831507

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:19:33  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.0452136065063585e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.0083921264101557e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.0891220495588616e-05 erg / (s cm2)
19:19:33  INFO        Bin 15 / 72 complete.
19:19:33  INFO      ==== Time bin 16 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -157.68350838871177      +/-   9.8906999999391829E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        52980
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(3.0 +1.1 +5) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(10.0 -2.8 -0.9) x 10,G
Synchrotron...index,4.30 -0.33 +0.5,
Synchrotron...gamma_cool,(0.22 +0.12 +3.1) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval15       -94.581613
n7_interval15      -112.828843
n8_interval15       -94.857954
b1_interval15       104.388574
total              -197.879836

Values of statistical measures:

        statistical measures
AIC               403.843355
BIC               420.479739
DIC               323.271446
PDIC               -2.073683
log(Z)            -68.481078

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:23:32  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  2.1007370596557518e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.9847050890695898e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  2.236774631342153e-05 erg / (s cm2)
19:23:32  INFO        Bin 16 / 72 complete.
19:23:32  INFO      ==== Time bin 17 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -851.80565410639224      +/-  0.10199980279046081
 Total Likelihood Evaluations:        54319
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(3.4 +0.7 +6) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(6.0 -1.7 -0.4) x 10,G
Synchrotron...index,4.34 -0.25 +0.5,
Synchrotron...gamma_cool,(0.20 +0.05 +5) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval16      -263.480888
n7_interval16      -280.696245
n8_interval16      -262.634338
b1_interval16       -82.847278
total              -889.658749

Values of statistical measures:

        statistical measures
AIC              1787.401180
BIC              1804.037565
DIC              1641.765148
PDIC              -69.788780
log(Z)           -369.934495

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:27:52  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  8.657189492797982e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  8.232121803647965e-06 erg / (s cm2)

                                              hi bound
Synchrotron: total  9.20207833089231e-06 erg / (s cm2)
19:27:52  INFO        Bin 17 / 72 complete.
19:27:52  INFO      ==== Time bin 18 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -276.33846443252617      +/-  0.10264925267453398
 Total Likelihood Evaluations:        59064
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(2.7 +1.0 +4) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.8 -3.0 -1.2) x 10,G
Synchrotron...index,4.87 -0.5 +0.04,
Synchrotron...gamma_cool,(0.21 +0.12 +2.7) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval17      -123.494761
n7_interval17      -131.166876
n8_interval17      -146.238324
b1_interval17        82.645677
total              -318.254285

Values of statistical measures:

        statistical measures
AIC               644.592251
BIC               661.228636
DIC               518.151825
PDIC              -43.403994
log(Z)           -120.012270

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:32:17  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.6758168332614894e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  1.594145815299731e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  1.766593204174436e-05 erg / (s cm2)
19:32:17  INFO        Bin 18 / 72 complete.
19:32:17  INFO      ==== Time bin 19 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1399.2299840818828      +/-  0.12243295713596118
 Total Likelihood Evaluations:        99202
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(6.28 -0.23 +2.1) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.97 -1.2 -0.20) x 10,G
Synchrotron...index,4.994 -0.08 -0.004,
Synchrotron...gamma_cool,(0.61 +0.10 +6) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval18      -421.007474
n7_interval18      -403.846906
n8_interval18      -414.498277
b1_interval18      -205.067303
total             -1444.419960

Values of statistical measures:

        statistical measures
AIC              2896.923602
BIC              2913.559987
DIC              1741.742118
PDIC            -1059.934731
log(Z)           -607.677861

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:38:30  INFO        10 keV-10 MeV flux =                                                   flux  \
Synchrotron: total  2.99626865721494e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  2.9392874037116486e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  3.0566011928881445e-05 erg / (s cm2)
19:38:30  INFO        Bin 19 / 72 complete.
19:38:30  INFO      ==== Time bin 20 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -527.71751048750241      +/-  0.10716889096581649
 Total Likelihood Evaluations:        64671
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(6.2 +1.2 +7) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(6.1 -1.5 -0.5) x 10,G
Synchrotron...index,4.99 -0.5 -0.05,
Synchrotron...gamma_cool,(0.31 +0.09 +7) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval19      -186.381374
n7_interval19      -206.872391
n8_interval19      -202.015394
b1_interval19        22.881383
total              -572.387775

Values of statistical measures:

        statistical measures
AIC              1152.859233
BIC              1169.495618
DIC              1057.206223
PDIC               -6.676926
log(Z)           -229.184803

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:43:09  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.3844421920674144e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.3345350307209081e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.4427849689561355e-05 erg / (s cm2)
19:43:09  INFO        Bin 20 / 72 complete.
19:43:09  INFO      ==== Time bin 21 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -776.33613856669967      +/-  0.11778867073725670
 Total Likelihood Evaluations:        93698
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(8.0 -0.5 +2.1) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.99 -0.9 -0.16) x 10,G
Synchrotron...index,4.995 -0.15 -0.010,
Synchrotron...gamma_cool,(0.83 +0.15 +6) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval20      -268.980383
n7_interval20      -263.722847
n8_interval20      -262.796630
b1_interval20       -29.368557
total              -824.868416

Values of statistical measures:

        statistical measures
AIC              1657.820514
BIC              1674.456898
DIC              1553.296923
PDIC               -5.807352
log(Z)           -337.158501

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:48:59  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  3.813238125334178e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  3.7182755912647544e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  3.9145784897692514e-05 erg / (s cm2)
19:48:59  INFO        Bin 21 / 72 complete.
19:48:59  INFO      ==== Time bin 22 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -75.444284527829794      +/-  0.11359462669413552
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        69021
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(7.8 +1.5 +7) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.999 -0.25 -0.023) x 10,G
Synchrotron...index,4.37 -0.30 +0.10,
Synchrotron...gamma_cool,(6.5 -2.9 +2.3) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval21       -88.251234
n7_interval21      -102.491656
n8_interval21       -77.630553
b1_interval21       139.244798
total              -129.128645

Values of statistical measures:

        statistical measures
AIC               266.340972
BIC               282.977357
DIC              -349.549905
PDIC             -509.169266
log(Z)            -32.765036

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:53:23  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  6.662786663641526e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  6.363104461479455e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  6.979935206569629e-05 erg / (s cm2)
19:53:23  INFO        Bin 22 / 72 complete.
19:53:23  INFO      ==== Time bin 23 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1157.1487132288864      +/-  0.12996140578618245

 Total Likelihood Evaluations:        77638
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.36 -0.10 +0.6) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.999 -0.06 -0.004) x 10,G
Synchrotron...index,4.61 -0.14 +0.10,
Synchrotron...gamma_cool,(8.9 -2.0 +0.4) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval22      -346.252780
n7_interval22      -369.682758
n8_interval22      -361.383990
b1_interval22      -134.121966
total             -1211.441494

Values of statistical measures:

        statistical measures
AIC              2430.966670
BIC              2447.603055
DIC              2315.393820
PDIC               -1.768528
log(Z)           -502.543301

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

19:58:07  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  8.694790471711403e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  8.488957295262461e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  8.918512412429927e-05 erg / (s cm2)
19:58:07  INFO        Bin 23 / 72 complete.
19:58:07  INFO      ==== Time bin 24 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=   223.34040272374693      +/-  0.10677149067209867
 Total Likelihood Evaluations:        57231
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(10.0 +1.2 +9) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(7.9 -1.7 -0.4) x 10,G
Synchrotron...index,5.00 -0.5 -0.06,
Synchrotron...gamma_cool,(0.34 +0.06 +6) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval23        -2.860394
n7_interval23       -24.296083
n8_interval23        -2.053332
b1_interval23       204.630252
total               175.420443

Values of statistical measures:

        statistical measures
AIC              -342.757204
BIC              -326.120820
DIC              -614.359836
PDIC             -177.429485
log(Z)             96.995504

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:02:22  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  3.564305985254666e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  3.408447420604405e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  3.7260857311598264e-05 erg / (s cm2)
20:02:22  INFO        Bin 24 / 72 complete.
20:02:22  INFO      ==== Time bin 25 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -4.7192691336217409      +/-  0.10539646875403315
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        58408
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.16 +0.20 +1.1) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(4.90 -1.1 -0.25) x 10,G
Synchrotron...index,4.9172 -0.5 +0.0014,
Synchrotron...gamma_cool,(0.38 +0.07 +7) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval24       -71.758013
n7_interval24       -70.434759
n8_interval24       -64.400738
b1_interval24       155.023423
total               -51.570088

Values of statistical measures:

        statistical measures
AIC               111.223858
BIC               127.860242
DIC                12.856203
PDIC               -6.549555
log(Z)             -2.049553

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:06:36  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  1.686846453042995e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  1.616311958428472e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  1.768762113058837e-05 erg / (s cm2)
20:06:36  INFO        Bin 25 / 72 complete.
20:06:36  INFO      ==== Time bin 26 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=   87.871859771309502      +/-   9.5350169095687484E-002
 Total Likelihood Evaluations:        43250
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.59 +0.18 +1.7) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(4.5 -1.8 -0.5) x 10,G
Synchrotron...index,4.12 -0.31 +0.6,
Synchrotron...gamma_cool,(0.12 +0.05 +3.0) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval25       -39.149055
n7_interval25       -53.272022
n8_interval25       -32.779732
b1_interval25       175.888714
total                50.687906

Values of statistical measures:

        statistical measures
AIC               -93.292129
BIC               -76.655745
DIC              -277.002486
PDIC             -111.408435
log(Z)             38.162264

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:10:35  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  9.486024296820935e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  8.901626963404214e-06 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.0297890498150393e-05 erg / (s cm2)
20:10:35  INFO        Bin 26 / 72 complete.
20:10:35  INFO      ==== Time bin 27 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -414.21518605258132      +/-   9.6933533067288066E-002
 Total Likelihood Evaluations:        47939
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.53 +0.11 +1.6) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(3.58 -1.5 -0.27) x 10,G
Synchrotron...index,4.09 -0.25 +0.6,
Synchrotron...gamma_cool,(0.105 +0.029 +1.5) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval26      -139.193349
n7_interval26      -171.715983
n8_interval26      -168.409896
b1_interval26        30.454436
total              -448.864791

Values of statistical measures:

        statistical measures
AIC               905.813265
BIC               922.449649
DIC               807.186619
PDIC              -29.316758
log(Z)           -179.891370

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:15:13  INFO        10 keV-10 MeV flux =                                                   flux  \
Synchrotron: total  5.25492846750476e-06 erg / (s cm2)

                                               low bound  \
Synchrotron: total  4.9511025034520185e-06 erg / (s cm2)

                                              hi bound
Synchrotron: total  5.65305316041346e-06 erg / (s cm2)
20:15:13  INFO        Bin 27 / 72 complete.
20:15:13  INFO      ==== Time bin 28 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -392.17815469134342      +/-  0.10044283951675606
 Total Likelihood Evaluations:        53672
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(4.8 +1.2 +7) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(6.2 -1.7 -0.4) x 10,G
Synchrotron...index,4.31 -0.24 +0.5,
Synchrotron...gamma_cool,(0.23 +0.10 +5) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval27      -154.953471
n7_interval27      -165.761250
n8_interval27      -150.104709
b1_interval27        38.292962
total              -432.526468

Values of statistical measures:

        statistical measures
AIC               873.136619
BIC               889.773003
DIC               788.859037
PDIC               -5.169318
log(Z)           -170.320809

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:19:22  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.3092100055103841e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.2409433986081561e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.3960234268278757e-05 erg / (s cm2)
20:19:22  INFO        Bin 28 / 72 complete.
20:19:22  INFO      ==== Time bin 29 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -110.72508230765696      +/-  0.11109580846878922

 Total Likelihood Evaluations:        72638
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(8.12 +0.27 +5) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.997 -0.31 -0.032) x 10,G
Synchrotron...index,4.05 -0.17 +0.21,
Synchrotron...gamma_cool,(5.9 -2.9 +2.8) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval28       -96.405199
n7_interval28       -88.904967
n8_interval28      -102.892818
b1_interval28       125.004690
total              -163.198294

Values of statistical measures:

        statistical measures
AIC               334.480270
BIC               351.116655
DIC               -79.230004
PDIC             -309.624623
log(Z)            -48.087292

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:23:56  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  6.241122616930718e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  5.964198920215526e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  6.536674014150413e-05 erg / (s cm2)
20:23:56  INFO        Bin 29 / 72 complete.
20:23:56  INFO      ==== Time bin 30 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -81.832542614171786      +/-  0.11803460359656218
 Total Likelihood Evaluations:        74308
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.26 +0.13 +0.9) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(10.000 -0.17 -0.017) x 10,G
Synchrotron...index,4.49 -0.22 +0.18,
Synchrotron...gamma_cool,(10.0 -6 -1.0) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval29       -95.386813
n7_interval29      -115.004669
n8_interval29       -87.431725
b1_interval29       159.509527
total              -138.313680

Values of statistical measures:

        statistical measures
AIC               284.711041
BIC               301.347426
DIC               -86.795414
PDIC             -258.684413
log(Z)            -35.539422

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:28:34  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  9.742629167812128e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  9.350552227713627e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  0.00010158178558562485 erg / (s cm2)
20:28:34  INFO        Bin 30 / 72 complete.
20:28:34  INFO      ==== Time bin 31 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=   37.135340399768374      +/-  0.11768878203479979
 Total Likelihood Evaluations:        68701
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.90 -0.05 +1.0) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.999 -0.14 -0.013) x 10,G
Synchrotron...index,3.67 -0.14 +0.10,
Synchrotron...gamma_cool,(9.23 -5 -0.13) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval30       -49.853434
n7_interval30       -66.497447
n8_interval30       -66.368711
b1_interval30       165.535794
total               -17.183797

Values of statistical measures:

        statistical measures
AIC                42.451275
BIC                59.087660
DIC              -275.018538
PDIC             -208.009450
log(Z)             16.127673

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:32:56  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  0.00016203468467836053 erg / (s cm2)

                                               low bound  \
Synchrotron: total  0.00015595713366335938 erg / (s cm2)

                                                hi bound
Synchrotron: total  0.00016842439081952705 erg / (s cm2)
20:32:56  INFO        Bin 31 / 72 complete.
20:32:56  INFO      ==== Time bin 32 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -453.11197827440554      +/-  0.11449799804581787
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        69866
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.49 +0.14 +1.0) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(10.00 -0.4 -0.05) x 10,G
Synchrotron...index,3.99 -0.18 +0.07,
Synchrotron...gamma_cool,(6.2 -2.4 +2.6) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval31      -165.692093
n7_interval31      -204.131261
n8_interval31      -172.428479
b1_interval31        35.043675
total              -507.208158

Values of statistical measures:

        statistical measures
AIC              1022.499998
BIC              1039.136382
DIC              -109.886953
PDIC            -1024.697318
log(Z)           -196.784032

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:37:22  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  0.0001251662881948848 erg / (s cm2)

                                               low bound  \
Synchrotron: total  0.00012148037488303658 erg / (s cm2)

                                               hi bound
Synchrotron: total  0.0001288783827178439 erg / (s cm2)
20:37:22  INFO        Bin 32 / 72 complete.
20:37:22  INFO      ==== Time bin 33 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=   410.12380983463368      +/-  0.10386798577674830
 Total Likelihood Evaluations:        60637
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.00 +0.14 +1.2) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(7.4 -1.9 -0.4) x 10,G
Synchrotron...index,4.98 -0.5 -0.05,
Synchrotron...gamma_cool,(0.288 +0.034 +3.3) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval32        25.399832
n7_interval32        34.082391
n8_interval32        25.680433
b1_interval32       277.631405
total               362.794060

Values of statistical measures:

        statistical measures
AIC              -717.504439
BIC              -700.868054
DIC              -891.604271
PDIC              -81.863122
log(Z)            178.114508

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:41:55  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  3.4070929353327555e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  3.243995779633626e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  3.584842965297231e-05 erg / (s cm2)
20:41:55  INFO        Bin 33 / 72 complete.
20:41:55  INFO      ==== Time bin 34 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -700.96515997339372      +/-  0.11045190307132204
 Total Likelihood Evaluations:        67460
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.07 +0.21 +1.1) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(5.4 -1.2 -0.4) x 10,G
Synchrotron...index,4.99 -0.5 -0.05,
Synchrotron...gamma_cool,(0.33 +0.10 +6) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval33      -231.810875
n7_interval33      -249.566546
n8_interval33      -246.448490
b1_interval33       -19.196959
total              -747.022869

Values of statistical measures:

        statistical measures
AIC              1502.129420
BIC              1518.765804
DIC               723.372196
PDIC             -686.644487
log(Z)           -304.425301

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:46:41  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.9002617923092033e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.8457721793174725e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  1.965336877260132e-05 erg / (s cm2)
20:46:41  INFO        Bin 34 / 72 complete.
20:46:41  INFO      ==== Time bin 35 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -724.75793163175956      +/-   9.6881823018105467E-002
 Total Likelihood Evaluations:        48238
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.35 +0.14 +2.2) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(5.3 -3.2 -0.9) x 10,G
Synchrotron...index,3.90 -0.6 +0.16,
Synchrotron...gamma_cool,(0.063 +0.021 +1.3) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval34      -236.002382
n7_interval34      -250.551922
n8_interval34      -237.463495
b1_interval34       -32.091187
total              -756.108986

Values of statistical measures:

        statistical measures
AIC              1520.301655
BIC              1536.938039
DIC              1293.940435
PDIC             -162.085999
log(Z)           -314.758370

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:51:49  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  8.046008660667646e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  7.459710986779326e-06 erg / (s cm2)

                                               hi bound
Synchrotron: total  8.703818924777172e-06 erg / (s cm2)
20:51:49  INFO        Bin 35 / 72 complete.
20:51:49  INFO      ==== Time bin 36 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -646.38957033325357      +/-   9.5322960305930529E-002
 Total Likelihood Evaluations:        41990
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.26 +0.08 +1.8) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(5.3 -3.3 -0.8) x 10,G
Synchrotron...index,3.97 -0.7 +0.26,
Synchrotron...gamma_cool,(0.057 +0.016 +1.1) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval35      -220.554024
n7_interval35      -225.194505
n8_interval35      -206.840130
b1_interval35       -24.026221
total              -676.614879

Values of statistical measures:

        statistical measures
AIC              1361.313440
BIC              1377.949825
DIC              1204.907219
PDIC              -94.095443
log(Z)           -280.723424

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

20:56:57  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  5.708396599624917e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  5.271865904228339e-06 erg / (s cm2)

                                               hi bound
Synchrotron: total  6.260302010954745e-06 erg / (s cm2)
20:56:57  INFO        Bin 36 / 72 complete.
20:56:57  INFO      ==== Time bin 37 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -443.05121629275487      +/-  0.10094710990453817
 Total Likelihood Evaluations:        53875
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(3.5 +1.1 +8) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(8.4 -3.1 -0.9) x 10,G
Synchrotron...index,4.4 +/- 0.4,
Synchrotron...gamma_cool,(0.15 +0.06 +2.7) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval36      -172.520654
n7_interval36      -169.832396
n8_interval36      -180.796814
b1_interval36        41.774774
total              -481.375091

Values of statistical measures:

        statistical measures
AIC               970.833864
BIC               987.470248
DIC               622.901053
PDIC             -271.823037
log(Z)           -192.414698

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

21:01:23  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.8347719621707573e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.7451414789136757e-05 erg / (s cm2)

                                              hi bound
Synchrotron: total  1.94148184054254e-05 erg / (s cm2)
21:01:23  INFO        Bin 37 / 72 complete.
21:01:23  INFO      ==== Time bin 38 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -535.81066907029663      +/-  0.11006236364641146
 Total Likelihood Evaluations:        69416
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(5.4 +1.5 +7) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(10.0 -2.4 -0.9) x 10,G
Synchrotron...index,4.938 -0.4 +0.005,
Synchrotron...gamma_cool,(0.28 +0.10 +4) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval37      -197.253325
n7_interval37      -211.400662
n8_interval37      -202.278052
b1_interval37        30.325677
total              -580.606362

Values of statistical measures:

        statistical measures
AIC              1169.296407
BIC              1185.932791
DIC              1004.992985
PDIC              -74.141251
log(Z)           -232.699617

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

21:06:17  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  3.331637439469516e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  3.2334663479222374e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  3.4535318814803856e-05 erg / (s cm2)
21:06:17  INFO        Bin 38 / 72 complete.
21:06:17  INFO      ==== Time bin 39 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -842.18828940410083      +/-  0.12065177636902245
 Total Likelihood Evaluations:        97084
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.24 -0.26 +0.15) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.99 -0.6 -0.12) x 10,G
Synchrotron...index,4.999 -0.12 -0.011,
Synchrotron...gamma_cool,(1.1 +0.4 +7) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval38      -275.948469
n7_interval38      -289.027480
n8_interval38      -271.171139
b1_interval38       -56.814671
total              -892.961758

Values of statistical measures:

        statistical measures
AIC              1794.007199
BIC              1810.643583
DIC              1554.396620
PDIC             -136.486567
log(Z)           -365.757727

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

21:12:11  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  5.386420471308274e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  5.272369663765136e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  5.499275025661121e-05 erg / (s cm2)
21:12:11  INFO        Bin 39 / 72 complete.
21:12:11  INFO      ==== Time bin 40 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -321.63578208181769      +/-  0.12027461851053475
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        79991
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.22 -0.10 +0.5) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.998 -0.21 -0.021) x 10,G
Synchrotron...index,4.98 -0.4 -0.06,
Synchrotron...gamma_cool,(8.74 -5 +0.16) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval39      -149.839748
n7_interval39      -161.426571
n8_interval39      -157.200118
b1_interval39        88.459637
total              -380.006800

Values of statistical measures:

        statistical measures
AIC               768.097283
BIC               784.733667
DIC              -495.224852
PDIC            -1146.065535
log(Z)           -139.684645

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

21:17:10  INFO        10 keV-10 MeV flux =                                                   flux  \
Synchrotron: total  7.22884770131765e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  7.045798680234689e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  7.458205139527379e-05 erg / (s cm2)
21:17:10  INFO        Bin 40 / 72 complete.
21:17:10  INFO      ==== Time bin 41 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -866.18017069212215      +/-  0.12535898816861402
 Total Likelihood Evaluations:        89629
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.39 +0.14 +0.9) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.998 -0.08 -0.007) x 10,G
Synchrotron...index,4.55 -0.14 +0.11,
Synchrotron...gamma_cool,(10.0 -4 -0.8) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval40      -280.086658
n7_interval40      -276.538185
n8_interval40      -306.348340
b1_interval40       -58.722877
total              -921.696060

Values of statistical measures:

        statistical measures
AIC              1851.475802
BIC              1868.112187
DIC              1657.478508
PDIC              -80.161058
log(Z)           -376.177268

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

21:22:34  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  0.00010659536161207979 erg / (s cm2)

                                               low bound  \
Synchrotron: total  0.00010392764609712298 erg / (s cm2)

                                                hi bound
Synchrotron: total  0.00010930129385317534 erg / (s cm2)
21:22:34  INFO        Bin 41 / 72 complete.
21:22:34  INFO      ==== Time bin 42 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=   76.761124724007686      +/-  0.11188553228799678
 Total Likelihood Evaluations:        71254
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.22 +0.18 +1.0) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.46 -1.7 -0.35) x 10,G
Synchrotron...index,5.000 -0.26 -0.027,
Synchrotron...gamma_cool,(0.39 +0.09 +5) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval41       -43.019595
n7_interval41       -62.896344
n8_interval41       -59.893005
b1_interval41       193.759592
total                27.950647

Values of statistical measures:

        statistical measures
AIC               -47.817613
BIC               -31.181228
DIC              -398.991905
PDIC             -254.401689
log(Z)             33.336933

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

21:27:29  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  6.349490102692206e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  6.143967430110748e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  6.566816971348553e-05 erg / (s cm2)
21:27:29  INFO        Bin 42 / 72 complete.
21:27:29  INFO      ==== Time bin 43 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -74.499031480658985      +/-  0.11137071203366344
 Total Likelihood Evaluations:        72171
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.34 +0.19 +1.3) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(6.38 -1.3 -0.26) x 10,G
Synchrotron...index,4.968 -0.24 +0.004,
Synchrotron...gamma_cool,(0.35 +0.07 +5) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval42       -85.792088
n7_interval42      -107.382936
n8_interval42       -96.133655
b1_interval42       167.629650
total              -121.679028

Values of statistical measures:

        statistical measures
AIC               251.441738
BIC               268.078122
DIC               152.316304
PDIC               -5.027100
log(Z)            -32.354518

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

21:32:32  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  3.250719148970707e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  3.145178233322054e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  3.3616888341877867e-05 erg / (s cm2)
21:32:32  INFO        Bin 43 / 72 complete.
21:32:32  INFO      ==== Time bin 44 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1472.0828115284678      +/-  0.11488735844133657
 Total Likelihood Evaluations:        77705
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(8.9 +1.6 +10) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(6.2 -1.4 -0.4) x 10,G
Synchrotron...index,4.87 -0.30 +0.05,
Synchrotron...gamma_cool,(0.30 +0.09 +7) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval43      -432.559536
n7_interval43      -442.605175
n8_interval43      -428.554464
b1_interval43      -212.100415
total             -1515.819590

Values of statistical measures:

        statistical measures
AIC              3039.722862
BIC              3056.359247
DIC              2687.555284
PDIC             -262.840586
log(Z)           -639.317442

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

21:37:52  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  2.062798693790909e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  2.021398379241242e-05 erg / (s cm2)

                                              hi bound
Synchrotron: total  2.10995985299337e-05 erg / (s cm2)
21:37:52  INFO        Bin 44 / 72 complete.
21:37:52  INFO      ==== Time bin 45 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -232.16413526114371      +/-  0.11102487157675221
 Total Likelihood Evaluations:        66368
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(9.0 +1.1 +8) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(8.4 -1.8 -0.4) x 10,G
Synchrotron...index,4.996 -0.32 -0.030,
Synchrotron...gamma_cool,(0.33 +0.07 +7) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval44      -131.557921
n7_interval44      -130.340512
n8_interval44      -119.857686
b1_interval44       102.875089
total              -278.881029

Values of statistical measures:

        statistical measures
AIC               565.845741
BIC               582.482126
DIC               173.323750
PDIC             -299.086722
log(Z)           -100.827603

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

21:42:35  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  3.6885311712986616e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  3.567865345797535e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  3.8156298693259605e-05 erg / (s cm2)
21:42:35  INFO        Bin 45 / 72 complete.
21:42:35  INFO      ==== Time bin 46 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -580.56058583541994      +/-  0.11205493438953727
 Total Likelihood Evaluations:        68586
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.93 +0.14 +1.1) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(5.7 -1.4 -0.4) x 10,G
Synchrotron...index,5.000 -0.31 -0.035,
Synchrotron...gamma_cool,(0.25 +0.06 +2.4) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval45      -216.596778
n7_interval45      -220.035534
n8_interval45      -207.886051
b1_interval45        20.104603
total              -624.413760

Values of statistical measures:

        statistical measures
AIC              1256.911202
BIC              1273.547587
DIC               942.886518
PDIC             -224.396615
log(Z)           -252.134259

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

21:47:39  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.8215763855727688e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.7717191135178512e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.8788868718251618e-05 erg / (s cm2)
21:47:39  INFO        Bin 46 / 72 complete.
21:47:39  INFO      ==== Time bin 47 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -603.36981472686421      +/-  0.10674959977530261
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        61189
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(8.6 +1.8 +10) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(4.8 -1.2 -0.4) x 10,G
Synchrotron...index,4.98 -0.6 -0.06,
Synchrotron...gamma_cool,(0.29 +0.08 +6) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval46      -211.149564
n7_interval46      -217.916687
n8_interval46      -211.076972
b1_interval46        -7.840370
total              -647.983593

Values of statistical measures:

        statistical measures
AIC              1304.050868
BIC              1320.687253
DIC              1163.904893
PDIC              -51.302977
log(Z)           -262.040181

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

21:52:09  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.1846096369234586e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.1444430639230595e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  1.236588189992184e-05 erg / (s cm2)
21:52:09  INFO        Bin 47 / 72 complete.
21:52:09  INFO      ==== Time bin 48 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=   417.62707117577634      +/-   8.7440807398396880E-002
 Total Likelihood Evaluations:        32713
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.39 +0.12 +2.1) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(4.4 -2.4 -0.6) x 10,G
Synchrotron...index,3.46 -0.27 +0.9,
Synchrotron...gamma_cool,(0.072 +0.023 +1.9) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval47        58.672523
n7_interval47        42.276693
n8_interval47        51.467498
b1_interval47       232.679041
total               385.095755

Values of statistical measures:

        statistical measures
AIC              -762.107828
BIC              -745.471443
DIC              -842.467359
PDIC              -17.852592
log(Z)            181.373133

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

21:56:10  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  6.767699019666613e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  6.024852591255656e-06 erg / (s cm2)

                                               hi bound
Synchrotron: total  7.819091803500536e-06 erg / (s cm2)
21:56:10  INFO        Bin 48 / 72 complete.
21:56:10  INFO      ==== Time bin 49 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -493.78996545737448      +/-  0.10564973480558051
 Total Likelihood Evaluations:        54943
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.74 +0.08 +1.1) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(4.77 -1.3 -0.23) x 10,G
Synchrotron...index,4.83 -0.5 +0.08,
Synchrotron...gamma_cool,(0.222 +0.025 +2.3) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval48      -189.610588
n7_interval48      -186.147138
n8_interval48      -187.627247
b1_interval48        27.503698
total              -535.881275

Values of statistical measures:

        statistical measures
AIC              1079.846232
BIC              1096.482616
DIC               876.376128
PDIC             -118.719139
log(Z)           -214.450257

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

22:00:34  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.1063565629832374e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.0660270502987205e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.1556047942518054e-05 erg / (s cm2)
22:00:34  INFO        Bin 49 / 72 complete.
22:00:34  INFO      ==== Time bin 50 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -58.473258741419144      +/-  0.10504557810772140
 Total Likelihood Evaluations:        60357
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(5.5 +1.3 +7) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.7 -2.5 -0.8) x 10,G
Synchrotron...index,4.98 -0.5 -0.05,
Synchrotron...gamma_cool,(0.27 +0.09 +5) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval49       -82.118280
n7_interval49       -95.263575
n8_interval49       -79.514119
b1_interval49       152.730815
total              -104.165159

Values of statistical measures:

        statistical measures
AIC               216.414001
BIC               233.050386
DIC               107.371695
PDIC              -19.029604
log(Z)            -25.394614

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

22:04:55  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  3.1266149154991745e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  3.0004796332139857e-05 erg / (s cm2)

                                                hi bound
Synchrotron: total  3.2724939414366874e-05 erg / (s cm2)
22:04:55  INFO        Bin 50 / 72 complete.
22:04:55  INFO      ==== Time bin 51 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=   141.08292248182534      +/-  0.11192246542722455
 Total Likelihood Evaluations:        68639
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.08 -0.07 +0.5) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(10.00 -0.35 -0.04) x 10,G
Synchrotron...index,4.62 -0.28 +0.19,
Synchrotron...gamma_cool,(3.9 -1.4 +4) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval50       -28.348376
n7_interval50       -52.199868
n8_interval50       -44.245869
b1_interval50       210.819794
total                86.025680

Values of statistical measures:

        statistical measures
AIC              -163.967678
BIC              -147.331294
DIC              -366.988847
PDIC              -94.920687
log(Z)             61.271535

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

22:09:20  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  6.541090671296301e-05 erg / (s cm2)

                                              low bound  \
Synchrotron: total  6.265838768662344e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  6.865071481441795e-05 erg / (s cm2)
22:09:20  INFO        Bin 51 / 72 complete.
22:09:20  INFO      ==== Time bin 52 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -151.25863016799073      +/-  0.11033550568548735
 Total Likelihood Evaluations:        65217
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(9.7 +1.3 +9) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(6.73 -1.4 -0.27) x 10,G
Synchrotron...index,4.989 -0.29 -0.023,
Synchrotron...gamma_cool,(0.34 +0.06 +5) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval51      -105.548008
n7_interval51      -110.322884
n8_interval51      -112.962125
b1_interval51       131.311629
total              -197.521387

Values of statistical measures:

        statistical measures
AIC               403.126456
BIC               419.762841
DIC               295.660359
PDIC              -14.974794
log(Z)            -65.690788

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

22:14:10  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  2.6285831130161686e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  2.5383231088037077e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  2.729727222696212e-05 erg / (s cm2)
22:14:10  INFO        Bin 52 / 72 complete.
22:14:10  INFO      ==== Time bin 53 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -606.53089326910151      +/-  0.10914838125468750
 Total Likelihood Evaluations:        65236
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(9.3 +1.2 +10) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(5.20 -1.1 -0.24) x 10,G
Synchrotron...index,5.00 -0.5 -0.05,
Synchrotron...gamma_cool,(0.327 +0.033 +6) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval52      -215.058044
n7_interval52      -228.818581
n8_interval52      -209.342241
b1_interval52         1.565469
total              -651.653398

Values of statistical measures:

        statistical measures
AIC              1311.390477
BIC              1328.026862
DIC              1142.193923
PDIC              -78.779934
log(Z)           -263.413020

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

22:19:09  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.5395070032818216e-05 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.4888389457629446e-05 erg / (s cm2)

                                               hi bound
Synchrotron: total  1.599940164382075e-05 erg / (s cm2)
22:19:09  INFO        Bin 53 / 72 complete.
22:19:09  INFO      ==== Time bin 54 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -537.64958562636957      +/-  0.10466247669082565
 Total Likelihood Evaluations:        53891
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.88 +0.25 +1.4) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(4.0 -1.2 -0.4) x 10,G
Synchrotron...index,4.67 -0.4 +0.19,
Synchrotron...gamma_cool,(0.21 +0.09 +6) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval53      -182.987560
n7_interval53      -200.102635
n8_interval53      -202.254147
b1_interval53         6.207701
total              -579.136641

Values of statistical measures:

        statistical measures
AIC              1166.356964
BIC              1182.993349
DIC               834.305433
PDIC             -249.513581
log(Z)           -233.498248

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

22:23:33  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  9.622153903677078e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  9.232798122686134e-06 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.0133626633117994e-05 erg / (s cm2)
22:23:33  INFO        Bin 54 / 72 complete.
22:23:33  INFO      ==== Time bin 55 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -373.21505426571554      +/-   9.2503186759640948E-002
 Total Likelihood Evaluations:        35729
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.481 +0.018 +3.4) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(3.04 -1.9 -0.04) x 10,G
Synchrotron...index,3.4 -0.4 +0.5,
Synchrotron...gamma_cool,(0.051 +0.004 +1.2) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval54      -134.395054
n7_interval54      -155.233232
n8_interval54      -146.590269
b1_interval54        33.977725
total              -402.240830

Values of statistical measures:

        statistical measures
AIC               812.565342
BIC               829.201727
DIC               669.847401
PDIC              -83.332317
log(Z)           -162.085239

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

22:29:18  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  4.041884351823343e-06 erg / (s cm2)

                                               low bound  \
Synchrotron: total  3.6387919237556316e-06 erg / (s cm2)

                                               hi bound
Synchrotron: total  4.526859872372108e-06 erg / (s cm2)
22:29:18  INFO        Bin 55 / 72 complete.
22:29:18  INFO      ==== Time bin 56 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -1095.7634318564251      +/-   9.2654385962748775E-002
 Total Likelihood Evaluations:        37607
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.72 -0.32 +6) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(3.7 -2.4 +0.6) x 10,G
Synchrotron...index,3.6 -0.8 +0.4,
Synchrotron...gamma_cool,(2.4 -0.5 +6) x 10^5,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval55      -325.763473
n7_interval55      -318.077221
n8_interval55      -309.093601
b1_interval55      -165.373391
total             -1118.307686

Values of statistical measures:

        statistical measures
AIC              2244.699054
BIC              2261.335438
DIC               827.423561
PDIC            -1365.121390
log(Z)           -475.884012

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

22:43:54  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.6663933926158143e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  1.513609443139953e-06 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.8829337886925498e-06 erg / (s cm2)
22:43:54  INFO        Bin 56 / 72 complete.
22:43:54  INFO      ==== Time bin 57 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1586.4029959436514      +/-   8.9256503851829636E-002
 Total Likelihood Evaluations:        36035
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.677 -0.014 +10) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(5.11 -4 -0.14) x 10,G
Synchrotron...index,3.13 -0.9 +0.35,
Synchrotron...gamma_cool,(0.104 +0.017 +1.2) x 10^6,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval56      -424.107364
n7_interval56      -448.469643
n8_interval56      -435.695583
b1_interval56      -295.227309
total             -1603.499899

Values of statistical measures:

        statistical measures
AIC              3215.083480
BIC              3231.719865
DIC             -2428.398779
PDIC            -5601.910692
log(Z)           -688.966067

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

23:02:37  WARNING   Too few points to create valid contours

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

23:02:42  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.1326099359121225e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  9.636364702579418e-07 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.3365532541357115e-06 erg / (s cm2)
23:02:42  INFO        Bin 57 / 72 complete.
23:02:42  INFO      ==== Time bin 58 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -1616.8894872278665      +/-   8.3231323143131822E-002
 Total Likelihood Evaluations:        30145
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.292 +0.022 +3.5) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(5.8 -5 -0.5) x 10,G
Synchrotron...index,3.6 -1.1 +0.4,
Synchrotron...gamma_cool,(1.01 +0.19 +9) x 10^5,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval57      -457.073621
n7_interval57      -437.997913
n8_interval57      -427.947553
b1_interval57      -309.405281
total             -1632.424369

Values of statistical measures:

        statistical measures
AIC              3272.932420
BIC              3289.568804
DIC             -2293.772403
PDIC            -5528.992658
log(Z)           -702.206182

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

23:21:49  WARNING   Too few points to create valid contours

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

23:21:54  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  5.233622776568384e-07 erg / (s cm2)

                                              low bound  \
Synchrotron: total  4.466414846476996e-07 erg / (s cm2)

                                               hi bound
Synchrotron: total  6.527402237922121e-07 erg / (s cm2)
23:21:54  INFO        Bin 58 / 72 complete.
23:21:54  INFO      ==== Time bin 59 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3171.1040574328777      +/-   9.1221074365748625E-002
 Total Likelihood Evaluations:        41469
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.043 +0.027 +7) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(2.9 -2.8 -1.0) x 10,G
Synchrotron...index,2.03 +0.06 +0.4,
Synchrotron...gamma_cool,(0.010 +0.011 +5) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval58      -821.327419
n7_interval58      -828.547477
n8_interval58      -825.504567
b1_interval58      -710.392771
total             -3185.772234

Values of statistical measures:

        statistical measures
AIC              6379.628151
BIC              6396.264536
DIC            -20330.515041
PDIC           -26679.108031
log(Z)          -1377.192994

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

23:29:54  INFO        10 keV-10 MeV flux =                                                   flux  \
Synchrotron: total  4.82830918594077e-07 erg / (s cm2)

                                               low bound  \
Synchrotron: total  3.9231121356357613e-07 erg / (s cm2)

                                               hi bound
Synchrotron: total  5.599046806450367e-07 erg / (s cm2)
23:29:54  INFO        Bin 59 / 72 complete.
23:29:54  INFO      ==== Time bin 60 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -2655.5447842161966      +/-   6.7548034373767912E-002
  analysing data from chains/fit-.txt
 Total Likelihood Evaluations:        22300
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.014 +0.023 +2.2) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(3.1 -3.0 -1.6) x 10,G
Synchrotron...index,2.7 +/- 0.5,
Synchrotron...gamma_cool,(0.011 +0.007 +3.3) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval59      -702.624020
n7_interval59      -697.649668
n8_interval59      -697.021838
b1_interval59      -571.267680
total             -2668.563205

Values of statistical measures:

        statistical measures
AIC              5345.210092
BIC              5361.846476
DIC              3147.830240
PDIC            -2172.258987
log(Z)          -1153.288446

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

23:38:24  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  8.952911187013839e-08 erg / (s cm2)

                                              low bound  \
Synchrotron: total  6.292630152228256e-08 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.3210079621096544e-07 erg / (s cm2)
23:38:24  INFO        Bin 60 / 72 complete.
23:38:24  INFO      ==== Time bin 61 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3772.0743481968434      +/-   3.7495546441903435E-002
 Total Likelihood Evaluations:         7526
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.11 +0.05 +4) x 10^-6,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(0.113 +0.021 +1.0) x 10,G
Synchrotron...index,2.67 -0.20 +1.4,
Synchrotron...gamma_cool,(0.012 +0.019 +3.4) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval60      -971.343658
n7_interval60      -966.612692
n8_interval60      -968.278157
b1_interval60      -850.373585
total             -3756.608092

Values of statistical measures:

        statistical measures
AIC              7521.299867
BIC              7537.936251
DIC              7537.391064
PDIC              -10.681946
log(Z)          -1638.191075

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

23:41:30  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.1516471969899978e-10 erg / (s cm2)

                                              low bound  \
Synchrotron: total  1.012429062422614e-11 erg / (s cm2)

                                               hi bound
Synchrotron: total  9.467327385950876e-10 erg / (s cm2)
23:41:30  INFO        Bin 61 / 72 complete.
23:41:30  INFO      ==== Time bin 62 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1721.1042816022562      +/-   6.0779027752173781E-002
 Total Likelihood Evaluations:        16491
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.21 +0.29 +4) x 10^-5,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.5 -8 -2.2) x 10,G
Synchrotron...index,2.66 -0.23 +1.3,
Synchrotron...gamma_cool,(0.02 +0.07 +4) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval61      -458.455650
n7_interval61      -478.906730
n8_interval61      -461.328709
b1_interval61      -336.543125
total             -1735.234213

Values of statistical measures:

        statistical measures
AIC              3478.552109
BIC              3495.188494
DIC              3431.866356
PDIC              -21.068165
log(Z)           -747.466092

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

23:44:22  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  2.1162891968578495e-07 erg / (s cm2)

                                              low bound  \
Synchrotron: total  1.306040861610113e-07 erg / (s cm2)

                                               hi bound
Synchrotron: total  3.345674156021412e-07 erg / (s cm2)
23:44:22  INFO        Bin 62 / 72 complete.
23:44:22  INFO      ==== Time bin 63 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -2688.8871309185729      +/-   8.6545693330939713E-002
 Total Likelihood Evaluations:        33994
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(1.0 +0.6 +9) x 10^-5,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.9 -7 -2.4) x 10,G
Synchrotron...index,3.1 -0.5 +0.7,
Synchrotron...gamma_cool,(0.052 +0.028 +1.7) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval62      -705.339150
n7_interval62      -713.934596
n8_interval62      -705.651331
b1_interval62      -583.139680
total             -2708.064757

Values of statistical measures:

        statistical measures
AIC              5424.213195
BIC              5440.849580
DIC              5353.138875
PDIC              -29.167659
log(Z)          -1167.768843

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

23:48:28  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  9.154756999416212e-07 erg / (s cm2)

                                             low bound  \
Synchrotron: total  7.95184816148615e-07 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.0849405302980987e-06 erg / (s cm2)
23:48:28  INFO        Bin 63 / 72 complete.
23:48:28  INFO      ==== Time bin 64 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -2380.5180836315944      +/-   9.1282400025763363E-002
 Total Likelihood Evaluations:        38923
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.137 +0.027 +1.3) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(10.0 -7 -1.1) x 10,G
Synchrotron...index,3.4 -0.7 +0.4,
Synchrotron...gamma_cool,(0.32 +0.05 +2.5) x 10^6,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval63      -627.154737
n7_interval63      -633.492885
n8_interval63      -635.119588
b1_interval63      -501.817668
total             -2397.584878

Values of statistical measures:

        statistical measures
AIC              4803.253438
BIC              4819.889823
DIC              4538.242332
PDIC             -223.037116
log(Z)          -1033.845868

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

23:57:14  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  1.104206927227938e-06 erg / (s cm2)

                                              low bound  \
Synchrotron: total  9.730775629756748e-07 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.2744438394342576e-06 erg / (s cm2)
23:57:14  INFO        Bin 64 / 72 complete.
23:57:14  INFO      ==== Time bin 65 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -3077.1173589312084      +/-  0.11186008048322323
 Total Likelihood Evaluations:        55461
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(2.62 +0.08 +0.9) x 10^-5,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.96 -2.0 -0.20) x 10,G
Synchrotron...index,3.27 -0.5 +0.19,
Synchrotron...gamma_cool,(2.120 +0.016 +0.5) x 10^5,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval64      -804.528821
n7_interval64      -809.467382
n8_interval64      -804.244506
b1_interval64      -672.498115
total             -3090.738824

Values of statistical measures:

        statistical measures
AIC              6189.561330
BIC              6206.197715
DIC              6142.098761
PDIC               -1.617435
log(Z)          -1336.375089

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

00:17:43  INFO        10 keV-10 MeV flux =                                                   flux  \
Synchrotron: total  1.92530847030175e-06 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.8037571625066587e-06 erg / (s cm2)

                                               hi bound
Synchrotron: total  2.046497576275386e-06 erg / (s cm2)
00:17:43  INFO        Bin 65 / 72 complete.
00:17:43  INFO      ==== Time bin 66 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -2161.2451426704674      +/-   9.4143317186273570E-002
 Total Likelihood Evaluations:        41309
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.234 +0.024 +1.1) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(9.1 -7 -0.7) x 10,G
Synchrotron...index,3.25 -1.0 +0.24,
Synchrotron...gamma_cool,(1.65 +0.13 +4) x 10^5,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval65      -571.250677
n7_interval65      -579.499107
n8_interval65      -573.268287
b1_interval65      -453.299771
total             -2177.317842

Values of statistical measures:

        statistical measures
AIC              4362.719366
BIC              4379.355751
DIC               498.436133
PDIC            -3821.887616
log(Z)           -938.616840

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

00:33:43  WARNING   Too few points to create valid contours

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

00:33:48  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  1.359177130750161e-06 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.1826332519055626e-06 erg / (s cm2)

                                              hi bound
Synchrotron: total  1.57698836282722e-06 erg / (s cm2)
00:33:48  INFO        Bin 66 / 72 complete.
00:33:48  INFO      ==== Time bin 67 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -1742.8994501592301      +/-   9.5774047200207657E-002
 Total Likelihood Evaluations:        43704
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.449 -0.033 +1.5) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(7.9 -5 +0.5) x 10,G
Synchrotron...index,3.19 -0.9 +0.28,
Synchrotron...gamma_cool,(2.10 -0.12 +3.4) x 10^5,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval66      -471.878378
n7_interval66      -476.067320
n8_interval66      -474.635421
b1_interval66      -338.991024
total             -1761.572144

Values of statistical measures:

        statistical measures
AIC              3531.227969
BIC              3547.864354
DIC               588.999582
PDIC            -2894.960155
log(Z)           -756.931614

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

00:48:52  WARNING   Too few points to create valid contours

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

00:48:56  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  2.229757306722361e-06 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.9625591254669277e-06 erg / (s cm2)

                                                hi bound
Synchrotron: total  2.5474896496389765e-06 erg / (s cm2)
00:48:56  INFO        Bin 67 / 72 complete.
00:48:56  INFO      ==== Time bin 68 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -2165.1437841935140      +/-   9.8931272806748738E-002
 Total Likelihood Evaluations:        42585
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(3.38 -0.31 +2.7) x 10^-5,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(7.9 -2.9 +0.6) x 10,G
Synchrotron...index,3.6 -0.8 +0.5,
Synchrotron...gamma_cool,(1.34 -0.11 +0.7) x 10^5,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval67      -568.798074
n7_interval67      -587.962434
n8_interval67      -580.269873
b1_interval67      -443.906398
total             -2180.936778

Values of statistical measures:

        statistical measures
AIC              4369.957239
BIC              4386.593624
DIC              3767.046858
PDIC             -557.954539
log(Z)           -940.309998

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

01:14:45  WARNING   Too few points to create valid contours

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

01:14:52  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  1.2344313161082805e-06 erg / (s cm2)

                                             low bound  \
Synchrotron: total  1.13554866451758e-06 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.3744936791009292e-06 erg / (s cm2)
01:14:52  INFO        Bin 68 / 72 complete.
01:14:52  INFO      ==== Time bin 69 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt
 ln(ev)=  -2070.2525282293759      +/-   9.5358918683893276E-002
 Total Likelihood Evaluations:        37500
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(2.59 -0.33 +2.6) x 10^-5,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(7.6 -3.2 +0.6) x 10,G
Synchrotron...index,2.9 -0.6 +0.7,
Synchrotron...gamma_cool,(1.01 +0.06 +0.7) x 10^5,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval68      -540.180830
n7_interval68      -565.955491
n8_interval68      -550.120583
b1_interval68      -427.195862
total             -2083.452767

Values of statistical measures:

        statistical measures
AIC              4174.989215
BIC              4191.625600
DIC             -4114.571607
PDIC            -8250.187683
log(Z)           -899.099249

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

01:41:46  WARNING   Too few points to create valid contours

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

01:41:53  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  9.432417510289907e-07 erg / (s cm2)

                                              low bound  \
Synchrotron: total  8.171236668621235e-07 erg / (s cm2)

                                               hi bound
Synchrotron: total  1.096202032913706e-06 erg / (s cm2)
01:41:53  INFO        Bin 69 / 72 complete.
01:41:53  INFO      ==== Time bin 70 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -2242.3118986765376      +/-   8.6142705050890903E-002
 Total Likelihood Evaluations:        33302
  analysing data from chains/fit-.txt
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.0341 -0.0014 +1.8) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(4.678 -4 -0.030) x 10,G
Synchrotron...index,2.8 -0.6 +0.5,
Synchrotron...gamma_cool,(0.107 +0.014 +7) x 10^6,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval69      -591.528206
n7_interval69      -603.713029
n8_interval69      -579.369658
b1_interval69      -482.347288
total             -2256.958181

Values of statistical measures:

        statistical measures
AIC              4522.000044
BIC              4538.636429
DIC            -13455.219329
PDIC           -17941.638645
log(Z)           -973.823684

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

01:57:24  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  5.416885308090759e-07 erg / (s cm2)

                                              low bound  \
Synchrotron: total  4.449449293993842e-07 erg / (s cm2)

                                               hi bound
Synchrotron: total  6.581775379571104e-07 erg / (s cm2)
01:57:24  INFO        Bin 70 / 72 complete.
01:57:24  INFO      ==== Time bin 71 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
 ln(ev)=  -3435.0832305423100      +/-   8.5008661917484657E-002
 Total Likelihood Evaluations:        32333
 Sampling finished. Exiting MultiNest
  analysing data from chains/fit-.txt

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.169 -0.004 +6) x 10^-4,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(4.58 -4 -0.10) x 10,G
Synchrotron...index,3.0 -0.7 +0.5,
Synchrotron...gamma_cool,(0.105 +0.017 +4) x 10^6,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval70      -894.038178
n7_interval70      -891.741813
n8_interval70      -872.210902
b1_interval70      -788.797797
total             -3446.788690

Values of statistical measures:

        statistical measures
AIC              6901.661063
BIC              6918.297447
DIC             -9940.568456
PDIC           -16810.908787
log(Z)          -1491.837692

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

02:12:57  INFO        10 keV-10 MeV flux =                                                     flux  \
Synchrotron: total  2.3785057332377243e-07 erg / (s cm2)

                                               low bound  \
Synchrotron: total  1.9541150690703278e-07 erg / (s cm2)

                                               hi bound
Synchrotron: total  2.890820691800762e-07 erg / (s cm2)
02:12:57  INFO        Bin 71 / 72 complete.
02:12:57  INFO      ==== Time bin 72 / 72 ====

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = 1000
 dimensionality =    4
 *****************************************************
  analysing data from chains/fit-.txt ln(ev)=  -3027.3623904400520      +/-   6.9420208024200861E-002
 Total Likelihood Evaluations:        23454
 Sampling finished. Exiting MultiNest

Maximum a posteriori probability (MAP) point:

,result,unit
parameter,,
Synchrotron.spectrum.main.SynchrotronNumerical.K,(0.011 +0.009 +1.4) x 10^-3,1 / (G keV s cm2)
Synchrotron.spectrum.main.SynchrotronNumerical.B,(3.4 -3.3 -1.4) x 10,G
Synchrotron...index,2.92 -0.7 +0.30,
Synchrotron...gamma_cool,(0.010 +0.008 +3.4) x 10^7,

Values of -log(posterior) at the minimum:

               -log(posterior)
n6_interval71      -769.855484
n7_interval71      -780.108133
n8_interval71      -773.421875
b1_interval71      -715.416887
total             -3038.802380

Values of statistical measures:

        statistical measures
AIC              6085.688442
BIC              6102.324827
DIC              2675.352483
PDIC            -3387.385091
log(Z)          -1314.766781

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

Propagating errors:   0%|          | 0/200 [00:00<?, ?it/s]

processing Bayesian analyses:   0%|          | 0/1 [00:00<?, ?it/s]

02:21:03  INFO        10 keV-10 MeV flux =                                                    flux  \
Synchrotron: total  8.399662097428349e-08 erg / (s cm2)

                                              low bound  \
Synchrotron: total  6.066831197840838e-08 erg / (s cm2)

                                                hi bound
Synchrotron: total  1.1940051474971565e-07 erg / (s cm2)
02:21:03  INFO        Bin 72 / 72 complete.

All 72 bins fitted successfully.

In [23]:
    ## Cell 18 — Save Results to CSV (Synchrotron)

In [24]:
if CONFIG['analysis_type'] in ['time_resolved', 'both']:
    fit_array = np.array(fit_rows)
    synchrotron_fit_param = Table(fit_array, names=PARAM_NAMES)
    synchrotron_fit_param['t_start'] = bb_starts
    synchrotron_fit_param['t_stop']  = bb_stops
    synchrotron_fit_param['dt']      = bb_stops - bb_starts

    csv_path = os.path.join(MODEL_PATHS['root'], 'fit_params.csv')
    synchrotron_fit_param.write(csv_path, overwrite=True)
    print(f'Results saved to: {csv_path}')
    print(f'Shape: {fit_array.shape}  ({n_bins} bins x {len(PARAM_NAMES)} parameters)')
    synchrotron_fit_param

Results saved to: gbm_pipeline_output/synchrotron/fit_params.csv
Shape: (72, 22)  (72 bins x 22 parameters)

## Cell 19 — Time-Integrated Analysis (All Models)

In [25]:
if CONFIG['analysis_type'] in ['time_integrated', 'both']:
    log.info('==== Starting Time-Integrated Analysis ====')
    ti_starts = np.atleast_1d(CONFIG['ti_t_start'])
    ti_stops  = np.atleast_1d(CONFIG['ti_t_stop'])
    
    for ti_s, ti_e in zip(ti_starts, ti_stops):
        log.info(f'==== Processing Time-Integrated Interval: [{ti_s}, {ti_e}] ====')
        
        ti_start = np.array([ti_s])
        ti_stop  = np.array([ti_e])
        ti_dt = ti_stop - ti_start
        
        ti_plugins = {}
        for det in detectors:
            ts = time_series[det]
            ts.create_time_bins(ti_start, ti_stop, method='custom')
            ti_plugins[det] = ts.to_spectrumlike(from_bins=True)[0]
            
        models_to_run = [
            ('cutoffpl', build_cutoffpl_model, CONFIG['priors_cutoffpl']),
            ('band', build_band_model, CONFIG['priors_band']),
            ('bandbb', build_bandbb_model, CONFIG['priors_bandbb']),
            ('cutoffbb', build_cutoffbb_model, CONFIG['priors_cutoffbb']),
            ('synchrotron', build_synchrotron_model, CONFIG['priors_synchrotron'])
        ]
        
        for model_name, builder_func, prior_dict in models_to_run:
            log.info(f'--- Fitting Time-Integrated {model_name.upper()} for [{ti_s}, {ti_e}] ---')
            MODEL_PATHS = get_model_paths(f'ti_{model_name}') 
            
            det_plugins = []
            for det in detectors:
                p = ti_plugins[det]
                if det.startswith('b'):
                    p.set_active_measurements(CONFIG['bgo_range'])
                else:
                    ranges = [r.strip() for r in CONFIG['nai_range'].split(',')]
                    p.set_active_measurements(*ranges)
                det_plugins.append(p)
                
            data_list = DataList(*det_plugins)
            model = builder_func(CONFIG['ra'], CONFIG['dec'], prior_dict)
            
            bayes = BayesianAnalysis(model, data_list)
            bayes.set_sampler('multinest')
            bayes.sampler.setup(n_live_points=CONFIG['n_live_points'], sampling_efficiency=CONFIG['sampling_efficiency'], auto_clean=True)
            bayes.sample()
            
            fig_spec = plot_spectra(
                bayes.results,
                ene_min=1.0, ene_max=1e5, num_ene=200,
                contour_colors='white', contour_style_kwargs=dict(alpha=0.2),
                use_components=True, components_to_use=['total'],
                flux_unit='keV2/(cm2 s keV)',
            )
            ax = plt.gca()
            ax.set_xlabel('Energy (keV)', fontsize=16)
            ax.set_ylabel(r'$\nu\,F_\nu\;[\mathrm{keV\,cm^{-2}\,s^{-1}}]$', fontsize=16)
            ax.set_title(f"{CONFIG['trigger_name']} Time-Integrated [{ti_start[0]:.3f}, {ti_stop[0]:.3f}] s", fontsize=13)
            interval_str = f"{ti_start[0]}_{ti_stop[0]}"
            fig_spec.savefig(os.path.join(MODEL_PATHS['spectra'], f'{model_name}_timeint_{interval_str}_spec.png'), dpi=120, bbox_inches='tight')
            plt.close('all')
            
            fig_corner = bayes.results.corner_plot()
            fig_corner.savefig(os.path.join(MODEL_PATHS['corners'], f'{model_name}_timeint_{interval_str}_corner.png'), dpi=100, bbox_inches='tight')
            plt.close('all')
            
            flux_df = bayes.results.get_point_source_flux(10 * u.keV, 10 * u.MeV)
            f_val = flux_df['flux'].iloc[0].value
            f_low = flux_df['low bound'].iloc[0].value
            f_hi  = flux_df['hi bound'].iloc[0].value
            
            df = bayes.results.get_data_frame('equal tail')
            df = df.drop('unit', axis=1, errors='ignore')
            param_array = df.to_numpy().flatten()
            
            import pandas as pd
            param_names = df.index.tolist()
            columns = []
            for p in param_names:
                columns.extend([p, f'{p}_n_err', f'{p}_p_err', f'{p}_avg_err'])
            columns.extend(['flux', 'flux_low', 'flux_hi', 't_start', 't_stop', 'dt', 'DIC', 'PDIC', 'BIC'])
            
            stat_df = bayes.results.get_statistic_measure_frame()
            dic_val = stat_df.loc['DIC'].iloc[0] if 'DIC' in stat_df.index else np.nan
            pdic_val = stat_df.loc['PDIC'].iloc[0] if 'PDIC' in stat_df.index else np.nan
            bic_val = stat_df.loc['BIC'].iloc[0] if 'BIC' in stat_df.index else np.nan
    
            full_row = np.append(param_array, [f_val, f_low, f_hi, ti_start[0], ti_stop[0], ti_dt[0], dic_val, pdic_val, bic_val])
            ti_table = Table(rows=[full_row], names=columns)
            interval_str = f"{ti_start[0]}_{ti_stop[0]}"
            csv_path = os.path.join(MODEL_PATHS['root'], f'timeint_{interval_str}_fit_params.csv')
            ti_table.write(csv_path, overwrite=True)
            log.info(f'  Saved Time-Integrated {model_name} results to {csv_path}')

## Cell 20 — Pipeline Summary (All Models)

In [26]:
print('=' * 60)
print('  GBM PIPELINE SUMMARY')
print('=' * 60)
print(f'  Trigger          : {CONFIG["trigger_name"]}')
print(f'  Detectors used   : {detectors}')
if 'n_bins' in locals():
    print(f'  Time bins fitted : {n_bins}')
    print(f'  Bin edges (s)    : starts={bb_starts}, stops={bb_stops}')
else:
    print('  Time-resolved    : (skipped)')
if CONFIG['analysis_type'] in ['time_integrated', 'both']:
    print(f'  Time-integrated  : {CONFIG["ti_t_start"]} to {CONFIG["ti_t_stop"]} s')
print('-' * 60)
print('  COMMON OUTPUTS:')
print(f'  Base Directory   : {COMMON_PATHS["root"]}')
print(f'  Lightcurves      : {COMMON_PATHS["lc"]}')
print('-' * 60)
print('  MODEL SPECIFIC OUTPUTS:')

found_models = False
if os.path.exists(COMMON_PATHS['root']):
    for item in sorted(os.listdir(COMMON_PATHS['root'])):
        model_dir = os.path.join(COMMON_PATHS['root'], item)
        if os.path.isdir(model_dir) and item != 'lightcurves':
            found_models = True
            print(f'  Model: [{item.upper()}]')
            print(f'    Spectra plots  : {os.path.join(model_dir, "spectra")}')
            print(f'    Corner plots   : {os.path.join(model_dir, "corners")}')
            csv_file = os.path.join(model_dir, 'fit_params.csv') 
            if os.path.exists(csv_file):
                print(f'    TR CSV results : {csv_file}')
            else:
                print(f'    TR CSV results : (Not generated)')
            
            import glob
            ti_csv_files = glob.glob(os.path.join(model_dir, 'timeint_*_fit_params.csv'))
            ti_csv_files += glob.glob(os.path.join(model_dir, 'ti_fit_params.csv'))
            for tf in ti_csv_files:
                print(f'    TI CSV results : {tf}')
            print()

if not found_models:
    print('  (No model-specific outputs found yet.)')

print('=' * 60)

============================================================
  GBM PIPELINE SUMMARY
============================================================
  Trigger          : bn250919020
  Detectors used   : ['n6', 'n7', 'n8', 'b1']
  Time bins fitted : 72
  Bin edges (s)    : starts=[ -9.99956799  -1.78271401   7.22259593   9.71147192  15.46768796
  17.64251691  19.00998604  19.55233794  21.46287203  21.78090894
  22.94713795  23.95138705  24.29245794  25.03654695  25.58158791
  26.23088396  26.42236698  27.00486797  27.24330795  28.07916594
  28.41358995  28.78744996  28.91535699  29.24994391  29.35126996
  29.50488901  29.66422695  29.99135202  30.27154595  30.417395
  30.52005893  30.59896392  30.76119196  30.83816099  31.22098398
  31.68854392  32.14265496  32.42498803  32.70401996  33.07159787
  33.24419695  33.49145097  33.5938049   33.74374396  34.83411098
  35.0178299   35.34640098  35.71819401  35.82653701  36.1624909
  36.31585497  36.41435498  36.58611292  36.93920398  37.29958296
  37.63099593  38.59061891  40.54509389  42.63914794  60.19475496
  69.244578   110.60793293 113.24236697 122.63177294 128.54242194
 142.65861392 146.94082397 149.23341393 153.55639493 157.51758289
 162.87332797 190.91526598], stops=[ -1.78271401   7.22259593   9.71147192  15.46768796  17.64251691
  19.00998604  19.55233794  21.46287203  21.78090894  22.94713795
  23.95138705  24.29245794  25.03654695  25.58158791  26.23088396
  26.42236698  27.00486797  27.24330795  28.07916594  28.41358995
  28.78744996  28.91535699  29.24994391  29.35126996  29.50488901
  29.66422695  29.99135202  30.27154595  30.417395    30.52005893
  30.59896392  30.76119196  30.83816099  31.22098398  31.68854392
  32.14265496  32.42498803  32.70401996  33.07159787  33.24419695
  33.49145097  33.5938049   33.74374396  34.83411098  35.0178299
  35.34640098  35.71819401  35.82653701  36.1624909   36.31585497
  36.41435498  36.58611292  36.93920398  37.29958296  37.63099593
  38.59061891  40.54509389  42.63914794  60.19475496  69.244578
 110.60793293 113.24236697 122.63177294 128.54242194 142.65861392
 146.94082397 149.23341393 153.55639493 157.51758289 162.87332797
 190.91526598 209.99907196]
------------------------------------------------------------
  COMMON OUTPUTS:
  Base Directory   : gbm_pipeline_output
  Lightcurves      : gbm_pipeline_output/lightcurves
------------------------------------------------------------
  MODEL SPECIFIC OUTPUTS:
  Model: [BAND]
    Spectra plots  : gbm_pipeline_output/band/spectra
    Corner plots   : gbm_pipeline_output/band/corners
    TR CSV results : gbm_pipeline_output/band/fit_params.csv

  Model: [BANDBB]
    Spectra plots  : gbm_pipeline_output/bandbb/spectra
    Corner plots   : gbm_pipeline_output/bandbb/corners
    TR CSV results : gbm_pipeline_output/bandbb/fit_params.csv

  Model: [CUTOFFBB]
    Spectra plots  : gbm_pipeline_output/cutoffbb/spectra
    Corner plots   : gbm_pipeline_output/cutoffbb/corners
    TR CSV results : gbm_pipeline_output/cutoffbb/fit_params.csv

  Model: [CUTOFFPL]
    Spectra plots  : gbm_pipeline_output/cutoffpl/spectra
    Corner plots   : gbm_pipeline_output/cutoffpl/corners
    TR CSV results : gbm_pipeline_output/cutoffpl/fit_params.csv

  Model: [SYNCHROTRON]
    Spectra plots  : gbm_pipeline_output/synchrotron/spectra
    Corner plots   : gbm_pipeline_output/synchrotron/corners
    TR CSV results : gbm_pipeline_output/synchrotron/fit_params.csv

  Model: [TI_BAND]
    Spectra plots  : gbm_pipeline_output/ti_band/spectra
    Corner plots   : gbm_pipeline_output/ti_band/corners
    TR CSV results : (Not generated)
    TI CSV results : gbm_pipeline_output/ti_band/timeint_0.0_55.0_fit_params.csv
    TI CSV results : gbm_pipeline_output/ti_band/timeint_99.97_190.02_fit_params.csv
    TI CSV results : gbm_pipeline_output/ti_band/timeint_0.0_190.0_fit_params.csv

  Model: [TI_BANDBB]
    Spectra plots  : gbm_pipeline_output/ti_bandbb/spectra
    Corner plots   : gbm_pipeline_output/ti_bandbb/corners
    TR CSV results : (Not generated)
    TI CSV results : gbm_pipeline_output/ti_bandbb/timeint_0.0_55.0_fit_params.csv
    TI CSV results : gbm_pipeline_output/ti_bandbb/timeint_99.97_190.02_fit_params.csv
    TI CSV results : gbm_pipeline_output/ti_bandbb/timeint_0.0_190.0_fit_params.csv

  Model: [TI_CUTOFFBB]
    Spectra plots  : gbm_pipeline_output/ti_cutoffbb/spectra
    Corner plots   : gbm_pipeline_output/ti_cutoffbb/corners
    TR CSV results : (Not generated)
    TI CSV results : gbm_pipeline_output/ti_cutoffbb/timeint_0.0_55.0_fit_params.csv
    TI CSV results : gbm_pipeline_output/ti_cutoffbb/timeint_99.97_190.02_fit_params.csv
    TI CSV results : gbm_pipeline_output/ti_cutoffbb/timeint_0.0_190.0_fit_params.csv

  Model: [TI_CUTOFFPL]
    Spectra plots  : gbm_pipeline_output/ti_cutoffpl/spectra
    Corner plots   : gbm_pipeline_output/ti_cutoffpl/corners
    TR CSV results : (Not generated)
    TI CSV results : gbm_pipeline_output/ti_cutoffpl/timeint_0.0_55.0_fit_params.csv
    TI CSV results : gbm_pipeline_output/ti_cutoffpl/timeint_99.97_190.02_fit_params.csv
    TI CSV results : gbm_pipeline_output/ti_cutoffpl/timeint_0.0_190.0_fit_params.csv

  Model: [TI_SYNCHROTRON]
    Spectra plots  : gbm_pipeline_output/ti_synchrotron/spectra
    Corner plots   : gbm_pipeline_output/ti_synchrotron/corners
    TR CSV results : (Not generated)
    TI CSV results : gbm_pipeline_output/ti_synchrotron/timeint_0.0_55.0_fit_params.csv
    TI CSV results : gbm_pipeline_output/ti_synchrotron/timeint_99.97_190.02_fit_params.csv
    TI CSV results : gbm_pipeline_output/ti_synchrotron/timeint_0.0_190.0_fit_params.csv

============================================================